### ISSUE TITLE
All Pages Table

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#100]
# Downhill Tasks (good for contributors)

- [x] datetime formatter for `Modified` and `Created` columns. Library discussion: https://github.com/athensresearch/athens/issues/66#issuecomment-642039741
- [x] responsive widths. see **Collapsed** section on #99

# UI

**Don't worry about showing links within a page.**

![table](https://user-images.githubusercontent.com/8952138/83808125-40b84980-a682-11ea-9d5a-28db364703f7.png)

**Comment by tangjeff0** [comment]
![Screen Shot 2020-06-02 at 6 23 34 PM](https://user-images.githubusercontent.com/8952138/83575727-2d7c7100-a4fe-11ea-983f-a676372ceee8.png)

- No breakpoints / no responsive: doesn't work at all with mobile view.

**Comment by estellerostan** [comment]
I'm shafoo on Discord and I'd like to work on the task "datetime formatter for Modified and Created columns" as my ClojureFam goal to merge my first Pull Request for Athens.

One question, the linked date library is `cljs-time` while `juxt/tick` was chosen for issue #66, is it okay to work with multiple libraries in the same project or is it better to switch to tick here too?

**Comment by tangjeff0** [comment]
@estellerostan I just updated my link. We should stick to one library, but not sure the state of #66. @Bardia95 ?

**Comment by Bardia95** [comment]
@estellerostan I'm not sure what you mean by `cljs-time` being the linked date library, but I think its best if we stuck with just one library. Are there any benefits you see in using `cljs-time` over `juxt/tick`?

**Comment by tangjeff0** [comment]
@Bardia95 I previously linked to cljs-time but have since updated it. @estellerostan I think it's safe to go ahead and try to implement this with `juxt/tick`

**Comment by tangjeff0** [comment]
Can always add more columns, sorting, bulk delete/export, etc. to the table, but I think this is a really good start for v1. Closing!
