### ISSUE TITLE
rfct(css): migrate to TailwindCSS

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#1002]
I've heard @shanberg and @neotyk are scheming on this :eyes: 

Curious what that migration would look like, and how custom CSS/theming would play a role if at all in the approach.

**Comment by shanberg** [comment]
I'm not settled yet on this being the right decision. Tailwind is pretty polarizing, and while there are some clear advantages, I think this needs to be a conversation and not just an issue/refactor.
