### ISSUE TITLE
Multiple block-ref in a block is not parsed.

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#1010]
**Problem**
- Multiple block-ref in a block is not parsed.

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/8164667/115624906-df4aa900-a32d-11eb-8eed-d6d78c819095.png)

**Athens Version**
1.0.0-BETA.71

**Comment by tangjeff0** [comment]
@neotyk
