### ISSUE TITLE
When the content is a header, it messed up the breadcrumb 

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#1014]
**Problem**
1. When the content is a header, it messed up the breadcrumb 

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/8164667/115698441-3173e480-a397-11eb-8074-19dce3aefce4.png)

**Athens Version**
1.0.0.BETA.73

**Comment by juniusfree** [comment]
When there's a block under an image, and when it is opened as a blocked page, the breadcrumb will be broken.

**Comment by tangjeff0** [comment]
cc @shanberg

**Comment by yifanyin** [comment]
When zooming in to a block with headings, it'll get comically huge. And editing the block also causes some kind of glitch.

<img width="506" alt="image" src="https://user-images.githubusercontent.com/15666419/115788506-f936cb00-a3c3-11eb-8603-e3290d2824f9.png">

**Comment by shanberg** [comment]
> When zooming in to a block with headings, it'll get comically huge. And editing the block also causes some kind of glitch.

Can you note your operating system here, and how you're zooming in on the block? Or anyone else seeing the same behavior? I'm not seeing this locally, so just want to understand where it’s happening.

**Comment by avidrucker** [comment]
@shanberg Is this issue resolved and ready to close?
