### ISSUE TITLE
Increase visual signal of "hovered" state of arrows and bullets next to blocks

### ISSUE THREAD

**Issue by shanberg** [athensresearch/athens#1016]
Sometimes it’s hard to tell what your cursor is over, and sometimes the cursor completely covers the arrow or bullet, hiding the current indicator.

**Comment by avidrucker** [comment]
-[ ] mark this with the `ux` label

**Comment by tangjeff0** [comment]
Please begin building habit of using `fix issue` or other keyword. Thank you @shanberg https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
