### ISSUE TITLE
Removal of a daily journal page creates a 404 error

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1022]
**Problem**
Removal of a daily journal page creates a 404 error, instead of returning to the page list as usual

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/24638389/115888515-986fc700-a485-11eb-9b09-6f0e70e7b719.png)

**Athens Version**
1.0.0-BETA.74 - Intel OSX 10.11

**Comment by juniusfree** [comment]
This also happens to any deleted page. I'll check.
