### ISSUE TITLE
Miscellaneous parser bugs

### ISSUE THREAD

**Issue by agentydragon** [athensresearch/athens#1036]
**Problem**

Since I recently updated Athens, I'm getting a few issues with some blocks in my database. I suspect this is probably related to the recent parser refactoring.

**Screenshots/Demo**

Rendering:

![image](https://user-images.githubusercontent.com/714892/115960938-72453800-a514-11eb-9a4e-e61e6316ffe6.png)

Markup:

```
- [[Xavier initialization]] scales weights by $$\sqrt{1/\text{inputs} }$$, [[He initialization]] by $$\sqrt{2/\text{inputs} }$$
- {{[[TODO]]}} learn how to do unsupervised pre-training with [[Restricted Boltzmann machine]]s or what not
- {{[[TODO]]}} ```rnd = np.random.RandomState(seed)
return rnd.randn(len(time))``` [[Anki]]
- {{[[TODO]]}} Pandas autocorrelation plot:
\`\`\`
from pandas.plotting import autocorrelation_plot

autocorrelation_plot(series)\`\`\` [[Anki]]
- {{[[TODO]]}} [[Buy]] at least 2 [[Cha hai]]s and 2 [[Gaiwan]]s from [[Yunnan Sourcing]]
- https://en.wikipedia.org/wiki/File:Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg
```

**Athens Version**

1.0.0-beta.74

**Comment by agentydragon** [comment]
Some issues I see are:

* Parser does not seem to correctly terminate LaTeX
* Some links don't seem to be parsed as such
* Underscores in URL parsed as italics

**Comment by agentydragon** [comment]
The LaTeX seems to have been already reported in https://github.com/athensresearch/athens/issues/1015 and fixed in https://github.com/athensresearch/athens/pull/1017.

**Comment by tangjeff0** [comment]
Hi @agentydragon, would be helpful if you created a checklist of the remaining parser issues and check them off as we address them. cc @neotyk

**Comment by agentydragon** [comment]
Will do, I'll try to reproduce this on master and update.

**Comment by neotyk** [comment]
@agentydragon Thank you for great bug report.
So easy to reproduce 🙏

**Comment by agentydragon** [comment]
Just checked on master.

Already fixed:

* `[[Xavier initialization]] scales weights by $$\sqrt{1/\text{inputs} }$$, [[He initialization]] by $$\sqrt{2/\text{inputs} }$$` (
![image](https://user-images.githubusercontent.com/714892/116320431-84df9b80-a7b8-11eb-9147-5848bcba6422.png))

Still broken:

* `{{[[TODO]]}} learn how to do unsupervised pre-training with [[Restricted Boltzmann machine]]s or what not` (
![image](https://user-images.githubusercontent.com/714892/116320461-9163f400-a7b8-11eb-8ea0-968aa9f3b0ee.png))
* `{{[[TODO]]}} \`\`\`rnd = np.random.RandomState(seed)
return rnd.randn(len(time))\`\`\` [[Anki]]` (
![image](https://user-images.githubusercontent.com/714892/116320514-a5a7f100-a7b8-11eb-92b3-b1a0517174f5.png))
* `{{[[TODO]]}} [[Buy]] at least 2 [[Cha hai]]s and 2 [[Gaiwan]]s from [[Yunnan Sourcing]]` (
![image](https://user-images.githubusercontent.com/714892/116320553-b8222a80-a7b8-11eb-88d9-fb3899def312.png))
* `https://en.wikipedia.org/wiki/File:Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg` (![image](https://user-images.githubusercontent.com/714892/116320571-c2dcbf80-a7b8-11eb-8b7c-427b95d3bd65.png))
