### ISSUE TITLE
Parser: underscores in inline URLs

### ISSUE THREAD

**Issue by agentydragon** [athensresearch/athens#1057]
**Problem**

This block: `https://en.wikipedia.org/wiki/File:Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg`

Is currently parsed as a link only up to `Hans`, and the underscores then are parsed as italics:

![image](https://user-images.githubusercontent.com/714892/116320571-c2dcbf80-a7b8-11eb-8b7c-427b95d3bd65.png)

**Athens Version**

1.0.0-beta.77 454682547046109d0cea3512d17d4fb3095397ec

cc @neotyk

**Comment by agentydragon** [comment]
More examples:

```
https://en.wikipedia.org/wiki/The_Ugly_Duchess/media/File:Quentin_Matsys_-_A_Grotesque_old_woman.jpg
```

```
https://upload.wikimedia.org/wikipedia/commons/7/7f/Henryk_Weyssenhoff_-_Przeczucie_1893.jpg
```

(all of those are from me and my flatmate brainstorming mildly but not overtly unsettling paintings to get as living room decorations :p)

**Comment by neotyk** [comment]
Well this is a tricky one, because it's a raw url.
In 3 staged parser we do:
1. block
2. inline
3. raw-url search

So inline formatting is detected before url and chops input already.

Best way to fix that is to use autolinks like this: `<http://example.com>`.

**Comment by agentydragon** [comment]
Yeah. But most Markdown parsers would be able to auto-linkify this, right?

(This and the fenced code block issue make me think maybe it would be better to not have the stages so clearly separated. I think underscores in URLs are a fairly common thing.)

**Comment by neotyk** [comment]
If we could assume that inline styles have to be separate from other words it would be easy.
But I guess you'd still like to have in_li_ne stiles in words, right?

**Comment by agentydragon** [comment]
Inline styles in words would be nice, but I (personally) think detecting URLs is a bit more important. In an ideal world we could understand that underscores in `http://my.site/my_url_foobar` are parts of the link, but underscores in `in_li_ne` are italics. You could tell a URL maybe just by "does it have `protocol://`".

The solution to remove `_` as a delimiter in https://github.com/athensresearch/athens/pull/1168 works for me. If I remember correctly, you only added underscores as delimiters in the recent refactor, so hopefully removing it doesn't break anyone else's rendering.

**Comment by agentydragon** [comment]
Looks like https://github.com/athensresearch/athens/pull/1168/files also closed this issue. Thanks!
