### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by mikejones3** [athensresearch/athens#1085]
**Problem**

While using the find or create page search at the top nothing shows up when I start typing in the pop up. 

**Athens Version**

1.0.0-beta.77 windows

**Comment by mikejones3** [comment]
after further testing while taking notes today, its just really slow. Once I stop typing it seems like its a full half second before search results populate.

**Comment by Limezy** [comment]
> after further testing while taking notes today, its just really slow. Once I stop typing it seems like its a full half second before search results populate.

Do you have a very heavy database ?

**Comment by mikejones3** [comment]
Nope, only been using it for a week or two. Nothing crazy

**Comment by juniusfree** [comment]
related to https://github.com/athensresearch/athens/issues/969

**Comment by tangjeff0** [comment]
Closed in Discord, just had to wait for debounce. Junius's new perf improvement removes debounce as well.
