### ISSUE TITLE
Create a Facebook Business account for Athens.

### ISSUE THREAD

**Issue by seekanddefine** [athensresearch/athens#1086]
Should this be called Athens Research?

Is there any argument for School of Athens?

Do we have any photos/image content available to populate?

**Comment by sid597** [comment]
I think this should be handled in community TODO or maybe a community todo epic issue. Github issues does not feel like a good place for individual todos because we cannot mark this with appropriate tags.

**Comment by tangjeff0** [comment]
I agree thanks @sid597
