### ISSUE TITLE
Multiuser icon overlapping with block bar

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1112]
**Problem**
User icon is overlapping with block bar when there is an indentation level

**Demo**
![image](https://user-images.githubusercontent.com/24638389/117200981-b393ec80-ae1e-11eb-92e6-6df4dd6a585b.png)

**Athens version**
1.0.0-BETA.78 - Intel OSX 10.11.6 - El Capitan

**Comment by sid597** [comment]
Not an issue anymore because RTC is not ready and the presence ui will change.
