### ISSUE TITLE
Disconnect - Reconnect should be seamless

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1114]
**Problem**
After disconnection with the backend, 
* If there has been some change, then I'll face [that issue](https://github.com/athensresearch/athens-backend/issues/16)
* If there hasn't been any change, when I reconnect I will have a feeling that the whole app is starting again !

**Frontend version**
1.0.0-BETA.78 - Intel OSX 10.11.6 - El Capitan

**Backend version**
Self-hosted on Debian + Yunohost - Commit https://github.com/athensresearch/athens-backend/commit/7516b6091c277142b54540b7f0fa912cac7bc229

**Comment by tangjeff0** [comment]
Same as #1102

**Comment by sid597** [comment]
Related to previous RTC attempt.
