### ISSUE TITLE
Clicking on page list or graph view on "disconnect mode" will freeze the app

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1115]
**Problem**
Suppose I've just disconnected from the backend.
I'm in "disconnect mode", with a red dot on the top and a button to re-connect.
If I don't reconnect but click on page list or graph view instead, the app will completely freeze

**Athens Version**
1.0.0-BETA.78 - Intel OSX 10.11.6 - El Capitan

**Comment by sid597** [comment]
Related to previous RTC attempt.
