### ISSUE TITLE
Block Editing User Presence

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#1116]
- [ ] Users “claim” blocks. Blocks can only be edited by one user at a time.
 - [ ] Claimed blocks are greyed out, show “being edited by {username}”

**Comment by Limezy** [comment]
Hi @jsmorabito, do you mean users can "lock" a block instead of claiming a block ?
Just like in Nextcloud for instance, where you can lock a file while working on it ?
That would be great. In terns of UX I would add a little keylock in front of the block.

However, if you meant that each block could have its own read / write / access, I believe that this would be a nightmare.
I think that Athens should go to the multigraph path, each graph having its own read / write access.
Currently writing a big piece of discussion on the matter 😃

**Comment by shanberg** [comment]
@Limezy "Claiming" in this multiplayer UX concept only means saying "I'm editing this block. Please don't edit this block while I'm editing it". Just a way for the UI to prevent multiple people from editing the same thing at the same time.

Yes, permissioning/rights management is a big deal, and definitely bigger than this issue. Thanks for the work you're doing on it now, I'm looking forward to seeing what you put together.

**Comment by Limezy** [comment]
I see, that's in line with what I had in mind. You can also refer to https://www.youtube.com/watch?v=Li38SmjKNkA to have some ideas about how Nextcloud deals with the UX (even though their use case is quite different)

**Comment by Ejipuh** [comment]
This is a cool idea, as it prevents the intrusive feeling that editing a Google Docs file can give. (This would help even more if blocks weren't bound to a linear arrangement on a given page: if you could draw a text box for a block that grew as you typed more lines, then you could make a nifty little messenger on a multiplayer graph, or organize things spatially.)

Along with what you mention, I wonder what the effect would be if you extended this idea out to certain blocks in a database. You could make a graph where each user could only claim a certain amount of blocks, so they would have to use these well. (Sort of like how the character count feature on Twitter can help to create scarcity around the words you choose when composing a message.) This would create scarcity around certain Roam blocks.

In any case, a web-accessible user presence would be a great source of onboarding--users could share parts of their graph and readers could see who else was reading it. It would feel a lot like [anagora.org](https://anagora.org/), where every page has a shared document/scratchpad that anyone can write on.

**Comment by tangjeff0** [comment]
Defer to #1119
