### ISSUE TITLE
Toolbar Presence

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#1117]
# API

- `username` - required
- `:block/uid` - optional
- `:page/uid` - optional, not in datascript (yet), just derived from `:block/uid`
- Constraints: 10 users max

v2

- click on avatar to **follow** that person
- show more context on hover

# Screenshots

![image](https://user-images.githubusercontent.com/8952138/121932068-474bb900-ccf9-11eb-8ade-480ab3ecd3b6.png)
![image](https://user-images.githubusercontent.com/8952138/121932123-592d5c00-ccf9-11eb-9e64-9df4f05ef276.png)

**Comment by tangjeff0** [comment]
Defer to #1119

**Comment by tangjeff0** [comment]
Closing because we already have PR draft #1361

**Comment by tangjeff0** [comment]
Closing because we already have PR draft #1361
