### ISSUE TITLE
Error importing Roam Research's EDN database file

### ISSUE THREAD

**Issue by mkyos** [athensresearch/athens#1135]
Error message：

```
message=Uncaught #error {:message "Conflicting upsert: [:node/title \"December 20, 2020\"] resolves to 1449, but entity already has :db/id 1273", :data {:error :transact/upsert, :assertion [1449 :node/title "December 20, 2020"], :conflict {:db/id 1273}}}
source=file:///Applications/Athens.app/Contents/Resources/app.asar/resources/public/js/compiled/renderer.js
lineno=4802
colno=204
error=#error {:message "Conflicting upsert: [:node/title \"December 20, 2020\"] resolves to 1449, but entity already has :db/id 1273", :data {:error :transact/upsert, :assertion [1449 :node/title "December 20, 2020"], :conflict {:db/id 1273}}}
```

https://user-images.githubusercontent.com/72077265/117704125-127dab00-b1fd-11eb-9688-29f99ea8f20e.mp4

**Comment by agentydragon** [comment]
For this, it would help a lot if you could share your Roam import file. I think the Roam import needs a bunch more testing and fixes, but I only saw issues on my own EDN import, and didn't yet feel like sharing the EDN.

**Comment by julionav** [comment]
I have the same error:

![image](https://user-images.githubusercontent.com/45607850/118277346-520ef600-b48e-11eb-8ae6-ef60e7f99868.png)

Cannot share my roam import though, but I could try to fix it

**Comment by sawhney17** [comment]
@julionav I think deleting the November 23rd daily note in both Roam and Athens, or just Roam, should do the trick

**Comment by julionav** [comment]
You are right @sawhney17, that should do the trick.

However, I plan to do a contribution to avoid this problem from happening. The issue is that I have more than 1 page that is converted to the same date page in Athens.

My current analysis:
- The problem is caused by a conflict on the transformation of a daily page in [[Roam]] in [[Athens]]. [[Roam]] uses  the ordinal number notation, and [[Athens]] the cardinal notation. 
    - However, In my [[Roam]] database, there are 2 pages that are transformed to [[November 23, 2020]]
        - [[November 23rd, 2020]]
        - And a misspelled [[November 23nd, 2020]]
    - Even though the second date is misspelled, Athens transforms it to [[November 23, 2020]] through a [[Regex]].
        - `#"(?<=\d{1,2})(st|nd|rd|th),(?=\s\d{4})"`
            - This matches `23nd` and `23rd` and treats them the same.
    - **The solution proposed solution is to use a more strict conversion between ordinal notation to cardinal notation** which will only convert actual roam date pages to athens date page.

**Comment by mkyos** [comment]
> Can you try to import again using version 1.0.0-beta.82 @mkyos ?

It's all right now. Thank you very much!
