### ISSUE TITLE
fix(rtc): shape of data - tx-id, user-id in different places

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#1141]
Main issue: sometimes the server throws an error from a transaction because of some improper destructuring where the code incorrectly assumes the shape of data.

Originally discovered this issue with @neotyk but have to repro the steps with the correct branches of FE and BE. Solution seems to be finding which TX's are shaped incorrectly and then standardizing the TX shape for all TX's.

https://github.com/athensresearch/athens/discussions/1082#discussioncomment-711294

**Comment by arkRedM** [comment]
Can you add more info? where and when it's happening?

**Comment by tangjeff0** [comment]
Not able to repro anymore actually @arkRedM
