### ISSUE TITLE
Using keyboard shortcut for italics incorrectly places cursor after, instead of inside asterisks

### ISSUE THREAD

**Issue by ThatAdamGuy** [athensresearch/athens#1161]
When hitting CMD-I on a Mac, Athens pastes in two asterisks.  That's good!
Unfortunately -- unlike with CMD-B for Bold -- the cursor is placed _after_ the asterisks, requiring the user to backspace.

DESIRED BEHAVIOR:
After hitting CMD-I (or CTRL-I on Windows), Athens should paste in two asterisks (as it currently does) and then place the cursor in between the two asterisks (which it does not do)

**Athens Version**
Beta 80

**Comment by sawhney17** [comment]
I've found the source of the issue, I'll try getting a fix in today.
