### ISSUE TITLE
Clicking inside a block with a hyperlink does not work sometimes

### ISSUE THREAD

**Issue by sid597** [athensresearch/athens#1213]
https://www.loom.com/share/e5bd2f75589249079593bf0d131dc670

**Comment by sid597** [comment]
I would like to work on this issue 
- [ ] Other cases where this might arise
- [ ] What is causing the issue 
- [ ] How can this be solved

**Comment by sid597** [comment]
This is what I could gather by just using the chromium dev tools, have not looked at the code : 

First, let's check out how a block with normal text in HTML looks like :
There is some more HTML under the `<div class="block-container"`  but that is not of importance, here focus on `<span class="block">`.

![s1](https://user-images.githubusercontent.com/22994594/119244008-bbc38a00-bb89-11eb-8004-160131f041d8.png)




Now here is the same for a buggy block, focus on  `<span class="block">` :

![s2](https://user-images.githubusercontent.com/22994594/119244037-07763380-bb8a-11eb-8d46-874a3cf47ce6.png)


As you can see this `<span class="block">` has another nested `span` which contains both the block text i.e `A block with link in it is like this ` and the hyperlink. 

From all the various combinations I tried by inserting bold text, italics text, block embeds etc. in a block, I found whenever we have the case of `<span>` containing both the text and hyperlink **and** the hyperlinks `<span>` is not nested in another tag this bug will arise, checkout the video for a few cases.
https://www.loom.com/share/3ddc825e0fd4404ebc2f0a870158565b

**Comment by tangjeff0** [comment]
> I found whenever we have the case of <span> containing both the text and hyperlink and the hyperlinks <span> is not nested in another tag this bug will arise, checkout the video for a few cases.

This is very promising if this is reproducibly true. What I don't understand is why clicking a few times eventually makes it possible to click in to the textarea.

**Comment by sid597** [comment]
> What I don't understand is why clicking a few times eventually makes it possible to click into the textarea.
Yeah me too, I am looking into it.

**Comment by sid597** [comment]
I think there are 2 ways to solve this issue and I am not sure which one would be the right way to go because I am currently not fully aware of the consequences they might have. I will post both the approaches I have: 

1. Make some `z-index` changes : 
     - The current implementation has `z-index`  for ( this is all for parent `div` with  `class = "block-content"`) :
         - `textarea`  : not set i.e 0
         - inside a `span` : all the `span` and `<a>`  have `z-index` `2` 
![Screenshot from 2021-05-25 17-13-14](https://user-images.githubusercontent.com/22994594/119493166-8c756e80-bd7d-11eb-80f1-3409b08a47f3.png)
     - Solution : 
        - Make `z-index`  changes to `textarea`, and **only** the `spans` related to block-ref and page-link, which would have `z-index` higher than the `textarea`.
        - This would allow us to click the page-links and block-ref without getting inside the edit mode and would be able to click the text  inside `span` which contains both plain text and hyperlink.  
      - Cons: 
          - This would not solve the underlying issue of why both plain text and hyperlink are together.

 2. Separate plain-text from hyperlink : 
     - I may be wrong but I think the current implementation of function `text-run-transform` in `athens > parser > impl` is buggy. I currently looking at this and would take this approach over 1. 
 
Outstanding question : Why clicking a few times eventually makes it possible to click into the textarea?

**Comment by sid597** [comment]
Update on the solution mentioned in the last comment: Cannot change the tag from `span` `to something else like `div` or `p` because the `text-run` can be embedded inside another `p` and `p` cannot have `p` or `div` as a descendant. 

This leaves us with solution 1 but the issue with that is, we want all the `span` to have  a `z-index` higher than textarea so that we can click on it without going into edit mode. Now `span` tag is being used for page-link, block-ref, and both of these implementation have more nested `span` without any class name or id so I either have to add id or class name to all these `span`. Moreover a `span` can be nested in other tags also so cannot go for the approach where `z-index` would be applied to specific classes and id. I am thinking of  a way where I add class to the `text-run` span and then exclude that `span` from `z-index` being applied to it. 

What do you think ? @shanberg @tangjeff0 @neotyk

**Comment by shanberg** [comment]
@sid597 There may be a CSS solution here that relies on deactivating pointer-events on non-interactive elements, rather than continuing to fight with the z-index. I can take a deeper look at that if you want.

Alternatively, there may be a solution based on capturing the click events at each layer of the DOM of parser-renderer objects, and creating some rules for how to deal with them.

**Comment by sid597** [comment]
Thank you @shanberg, I will try these approaches and if  I get stuck I will ask you for help.

**Comment by sid597** [comment]
> Cannot change the tag from  `span` to something else like `div` or `p` because the `text-run` can be embedded inside another `p` and  `p`  cannot have `p`  or  `div` as a descendant. 

I gave this approach another shot by changing the `p` to a `div` to get around the issue who can be whos descendant. This solved the current problem but now styles don't get applied to block-ref. This is because now all the plain text now get rendered into `<div class="paragraph">` which overrides the block-ref style. Block-ref style not getting applied is only one bug which I found this might also be in some other places.

**Comment by sid597** [comment]
Even if I fix the current approach of modifying `p` to `div` etc. this approach will remain incorrect, because as mentioned by @shanberg in [discord](https://discord.com/channels/708122962422792194/708124156113321985/847210631907901461) 
> there are accessibility implications to modifying the tags, FYI. Paragraphs ought to be marked with p, anonymous container elements with div, and anonymous spans of text with span

**Comment by sid597** [comment]
I took the approach of deactivating pointer-events shanberg mentioned above, I think now the issue is fixed. I tested it on a few cases and it works as expected. Thank you @shanberg @neotyk
