### ISSUE TITLE
message=Uncaught Error: Index argument to nth must be a number. source=file:///Applications/Athens.app/Contents/Resources/app.asar/resources/public/js/compiled/renderer.js lineno=282 colno=483 error=Error: Index argument to nth must be a number.

### ISSUE THREAD

**Issue by pwobuk** [athensresearch/athens#1220]
**Problem**

Highlight some words and click [[ to create a new page followed by {enter}

That's when I get the error

message=Uncaught Error: Index argument to nth must be a number.
source=file:///Applications/Athens.app/Contents/Resources/app.asar/resources/public/js/compiled/renderer.js
lineno=282
colno=483
error=Error: Index argument to nth must be a number.

I am on a MacBook Pro M1

**Screenshots/Demo**
<img width="953" alt="CleanShot 2021-05-23 at 15 20 58@2x" src="https://user-images.githubusercontent.com/79809647/119264332-a0349f80-bbda-11eb-84da-ad2b3e5c36e8.png">

**Athens Version**
Version 1.0.0-beta.82 (1.0.0-beta.82)

**Comment by datokrat** [comment]
Yes, I can confirm that -- I briefly mentioned it in #1204, although deeply hidden in the fulltext... :) Seems to occur reproducibly on a block where no block or page search panel has been opened before. For example:

1. Create new block. Write down the title of an existing block (page).
2. Select the text.
3. Press `((` (`[[`).
4. Now, no item from the search panel is selected, although there are search results.
5. Press `ENTER`.
6. Enjoy.

A quick fix might be to just check in `auto-complete-inline` whether `index` is `nil` and handle appropriately. A more sustainable fix might be to ensure that `nil` can only occur when there are no results at all (a case that is already properly handled).

**Comment by Em-AK** [comment]
Looks like the same error as in #1134
