### ISSUE TITLE
Adding a todo doesn't place the caret at the end of the component

### ISSUE THREAD

**Issue by julionav** [athensresearch/athens#1250]
**Problem**
Creating a todo `cmd+enter`, places the carent at the start of the block (before the {{[[TODO]]}}) which requires to move the caret at the end of the block to start writting

**Screenshots/Demo**
https://www.loom.com/share/9cddbc24384e457485829ef8659cf958

**Athens Version**
- Beta 85. Was not happening in 82 (I think)

**Comment by shanberg** [comment]
I'm seeing this issue on Windows and Linux, but not macOS.

**Comment by datokrat** [comment]
The problem occurs since I overlooked two occurrences of `(swap! state assoc :string/local new-textarea-value)`, which I should also have replaced. Using these commands doesn't give the browser enough semantic information about the operation we're doing, I think.
