### ISSUE TITLE
AutoSave setting is ignored

### ISSUE THREAD

**Issue by julionav** [athensresearch/athens#1255]
**Problem**
AutoSave setting is ignored.
I have the setting set to 120 seconds, but athens starts autosaving as soon as I create a new block.

**Screenshots/Demo**
https://www.loom.com/share/d51eaee033b946679cbac40857a0b02d

**Athens Version**
- Beta 85

**Comment by sawhney17** [comment]
i don't think that's what the toggle is supposed to do. I think it's just supposed to change the frequency of the files being created. The yellow icion doesn't nessesarily mena that it's saving, just thta you have changes thta need to be saved which will be saved at the completion of the 120 seconds.

**Comment by julionav** [comment]
That makes sense. Although it takes a lot of time to do that "saving", which made me think it was creating a new backup.

Well, maybe it is creating the backup. My backup file is 6gb and I have only been using athens full time for about 2 weeks

**Comment by sawhney17** [comment]
Same for me, it gets huge pretty fast. Every time it autosaves it basically creates a copy of your db. I clear it out every week.
