### ISSUE TITLE
Allow to drop images/files

### ISSUE THREAD

**Issue by julionav** [athensresearch/athens#1257]
I want to be able to drag files from my filesystem and drop them into athens to create a link to the file.

Athens could copy the file, or just have a link to it. I don't have a preference.

**Comment by TillScout** [comment]
Please upvote [this discussion](https://github.com/athensresearch/athens/discussions/1156) and share your thoughts there!

**Comment by sid597** [comment]
Please carry on in the discussion mentioned by @TillScout
