### ISSUE TITLE
Copy-Paste duplicate and destroy embeds

### ISSUE THREAD

**Issue by snird** [athensresearch/athens#1274]
When I copy multiple blocks
And one of the blocks is an embed of a block
It:
- Destroy the embed block that was there. Now it is just plain text
- Duplicate the (now text) embed twice when I paste

Started with Beta 86

**Comment by juniusfree** [comment]
@snird I can't replicate this. When you have time, can you send a video on how to replicate this? Thanks.

**Comment by snird** [comment]
[2021-06-03 11-53-57.zip](https://github.com/athensresearch/athens/files/6590259/2021-06-03.11-53-57.zip)

**Comment by juniusfree** [comment]
@snird Thanks. It looks there are several others who's observing this issue.

**Comment by sid597** [comment]
@snird Can you check this issue in ~latest build?

**Comment by snird** [comment]
This is now fixed.
Thank you guys!
