### ISSUE TITLE
Copy paste is broken after multiple block selection in beta 86

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1278]
**Problem**
When selecting multiple blocks using the newest beta 86, copy-paste will result in broken order and duplicates in the output.
When selecting from bottom to top or from top to bottom, the result will be bad in both cases, but different.

**Screenshots/Demo**
Example, selection from top to bottom
![unknown-23](https://user-images.githubusercontent.com/24638389/120644485-f55d9480-c4a9-11eb-95c5-1e9f44b7dbc7.png)

Example, selection from bottom to top
![unknown-22](https://user-images.githubusercontent.com/24638389/120644503-fd1d3900-c4a9-11eb-973b-9e89cfeac811.png)

**Athens Version**
1.0.0-BETA.86 - Intel OSX 10.15.7

**Comment by Limezy** [comment]
Partly related to https://github.com/athensresearch/athens/issues/1274

**Comment by tangjeff0** [comment]
Can you confirm beta.88 closes this @Limezy ?

**Comment by Limezy** [comment]
@tangjeff0 I confirm that that issue was closed by beta 88.
