### ISSUE TITLE
Block overlapping with sub-block when editted in zoom mode

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1290]
**Problem**
This one is nasty : when a block has between 25 and 29 characters in bold, or between 27 and 31 characters in italic, it will overlapp with its sub-blocks in zoom mode. See below demo. There are other cases, basically you need a rendering key (*, **, ^^ or combination) and a certain length to reproduce it.

**Screenshots/Demo**
https://user-images.githubusercontent.com/24638389/120982541-68695280-c7ab-11eb-8a4b-3bc4fa1fe08c.mov

**Athens Version**
1.0.0-BETA.88 - Intel OSX

**Comment by juniusfree** [comment]
I'll try to fix this one.
