### ISSUE TITLE
exception when up/down-arrow key pressed with empty search (meta-k)

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#1296]
### Discussed in https://github.com/athensresearch/athens/discussions/827

<div type='discussions-op-text'>

<sup>Originally posted by **phrohdoh** March 15, 2021</sup>
On 1.0.0-beta57 (and reproduced on beta60 by @jsmorabito), opening the page create/search popup/view/? and pressing either the up- or down-arrow key without having entered anything will result in an exception.

![](https://cdn.discordapp.com/attachments/802652338619285594/821025006968242246/Screen_Shot_2021-03-15_at_9.20.04_AM.png)

https://github.com/athensresearch/athens/blob/v1.0.0-beta.60/src/cljs/athens/views/athena.cljs#L207-L230

I _suspect_ we'll want to invoke `scroll-into-view` iff `next-el` is non-`nil`.</div>

**Comment by juniusfree** [comment]
I can't reproduce in beta88 windows 10.

**Comment by tangjeff0** [comment]
Pretty sure this was solved somewhere a month ago
