### ISSUE TITLE
Significant usability regressions in v0.85 on Mac

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#1298]
### Discussed in https://github.com/athensresearch/athens/discussions/1267

<div type='discussions-op-text'>

<sup>Originally posted by **ThatAdamGuy** June  2, 2021</sup>
Apologies in advance for not offering detailed bugs tonight due to being pretty time-strapped.

On an M1 Mac Mini running latest Mac Big Sur OS, installed Athens Mac app this morning.

- Block selection is consistently off when selecting a significant chunk via shift and arrow keys (always overshoots)
- Cursor very often disappears
- At least a couple times, was unable to select anything and had to close and restart the app
- Deleted blocks sometimes re-appear

</div>

**Comment by sid597** [comment]
I think this is solved in beta.88
