### ISSUE TITLE
Delete a block and "undo" cannot bring it back

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#1305]
### Discussed in https://github.com/athensresearch/athens/discussions/951

<div type='discussions-op-text'>

<sup>Originally posted by **yifanyin** April 12, 2021</sup>
Has anyone encountered this bug/feature? Once I select a whole block (nodes included, with a blue shade over the block) and delete it. "Undo" will not bring back the block. The same goes with cutting the whole block (see my question [here](https://discord.com/channels/708122962422792194/802652338619285594/830744523268292659)). It is a bit inconvenient if the deleted block has several references attached to it.
</div>

**Comment by sid597** [comment]
It works https://www.loom.com/share/0546b133ac414acb8850255b8e541c4f , https://github.com/athensresearch/athens/pull/991
