### ISSUE TITLE
rearchitect `walk-string` and `parse-for-links`

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#1344]
- current architecture: `:transact` event -> `:transact!` effect -> `d/with` to see new db state -> filter all new datoms that have `:block/string` -> analyze for `:block/refs` to assert or retract -> create this new transaction
  - many problems with this, like #576 
- new potential architecture: whenever `:block/string` is asserted or retracted within a common-event, analyze _in that event_ rather than all `:block/strings` at the end
- TEST - currently not tested at all

**Comment by sid597** [comment]
@tangjeff0 Are you or Alex planning to do this? if  not I would like to take this up

**Comment by tangjeff0** [comment]
@sid597 Haven't made any specific plans for this. You are welcome to get the ball rolling!

**Comment by sid597** [comment]
Starting work on this will keep posting updates in a WIP PR

**Comment by neotyk** [comment]
Currently nested page links or block refs within page links is analyzed in not sufficient way for Linkmaker.

```clojure
(sut/staged-parser->ast "one [[two]] ((three)) #four #[[[[four and a half]] five [[six]]]]")
[:block
 [:paragraph
  "one "
  [:page-link "two"]
  " "
  [:block-ref "three"]
  " "
  [:hashtag "four"]
  " "
  [:hashtag
   [:page-link "four and a half"]
   " five "
   [:page-link "six"]]]]
```

Output we're looking for, so Linkmaker can do it's job:
```clojure
(sut/staged-parser->ast "one [[two]] ((three)) #four #[[[[four and a half]] five [[six]]]]")
[:block {:from "one [[two]] ((three)) #four #[[[[four and a half]] five [[six]]]]"}
 [:paragraph {:from "one [[two]] ((three)) #four #[[[[four and a half]] five [[six]]]]"}
  "one "
  [:page-link {:from "[[two]]"}
   "two"]
  " "
  [:block-ref {:from "((three))"}
   "three"]
  " "
  [:hashtag {:from "#four"}
   "four"]
  " "
  [:hashtag {:from "#[[[[four and a half]] five [[six]]]]"}
   [:page-link {:from "[[four and a half]]"}
    "four and a half"]
   " five "
   [:page-link {:from "[[six]]"}
    "six"]]]]
```

Notice a difference in `{:from "..."}`.

Minimum requirement is to expose `{:from "..."}` at least for:
- [ ] `:page-link`
- [ ] `:hashtag`
- [ ] `:block-ref`
