### ISSUE TITLE
TypeError: Cannot read property 'offsetTop' of null

### ISSUE THREAD

**Issue by elazar** [athensresearch/athens#1360]
**Problem**

```
message=Uncaught TypeError: Cannot read property 'offsetTop' of null
source=file:///tmp/.mount_AthensTZzJa8/resources/app.asar/resources/public/js/compiled/renderer.js
Lineno=285
colno=483
error=TypeError: Cannot read property 'offsetTop' of null
```

**Screenshots/Demo**

This doesn't happen consistently, but appears to correspond to being on a page that's not today's page and then double-clicking the calendar icon to get to today's page. It may or may not require having the originating page designated as a shortcut.

**Athens Version**

Athens 1.0.0-BETA.88

**Comment by mtravers** [comment]
Something similar just happened to me; trigger was clicking the icon for daily notes:
![image](https://user-images.githubusercontent.com/19027/136241421-de6287fe-0c4c-40bc-af48-301ad2173cea.png)
