### ISSUE TITLE
How can I connect a REPL?

### ISSUE THREAD

**Issue by teodorlu** [athensresearch/athens#14]
Most (if not all) of Clojure's options for developments environments allow the option of connecting your editor to the running instance of the program through an editor-integrated REPL. Do we have an option for this?

For athens, this would mean that we could do interactive queries of our roam datascript database _from within the editor_.

Some references:

- https://www.youtube.com/watch?v=3Ogei0FX4AI
- https://shadow-cljs.github.io/docs/UsersGuide.html#browser-repl
- https://clojure.org/guides/repl/introduction
- https://youtu.be/FihU5JxmnBg

**Comment by teodorlu** [comment]
The current setup seems to start nREPL already:

```
% lein dev
shadow-cljs - HTTP server available at http://localhost:3000
shadow-cljs - server version: 2.8.83 running at http://localhost:9630
shadow-cljs - nREPL server started on port 8777
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
WARNING: reagent.interop/$ has been deprecated. Consider using ClojureScript JS-interop forms or goog.object namespace instead.
[:app] Build completed. (604 files, 603 compiled, 0 warnings, 34.71s)
```

**Comment by teodorlu** [comment]
The nREPL server seems to be for Clojure and not for ClojureScript. It might be possible to use the Shadow-CLJS API to "upgrade to a CLJS repl".

**Comment by teodorlu** [comment]
A browser-connected REPL might not be 100 % needed, though. Using the REPL in ClojureScript has allways been more "fiddly" than when using Clojure.

My impression is that almost all Clojure developers use the REPL, while it's more common to just stick with a live-reloading setup without a REPL as we have now for ClojureScript.

**Comment by tangjeff0** [comment]
> For athens, this would mean that we could do interactive queries of our roam datascript database from within the editor.

Currently doing this with Cursive, will post more about my workflow today.

**Comment by tangjeff0** [comment]
Made a tutorial on how to use a browser-connected REPL with shadow-cljls.
Tutorial: https://youtu.be/W4FXpANSJGQ
Notes: https://roamresearch.com/#/app/ego/page/aARLhmFxm

Let me know if this is sufficient @teodorlu

**Comment by teodorlu** [comment]
Sounds great! I'll get back to you when I've tried it out.

Thanks!

**Comment by jorda0mega** [comment]
You can also use VSCode and connect to a running shadow-cljs nREPL

1. Calva connect to a running REPL server in project
![image](https://user-images.githubusercontent.com/484084/81217257-4864cf80-8faa-11ea-8c24-e3acf55d6f61.png)
2. Select shadow-cljs
![image](https://user-images.githubusercontent.com/484084/81217279-51ee3780-8faa-11ea-95b2-252edb2c422a.png)
3. Select the nREPL port mentioned when running `lein dev`
![image](https://user-images.githubusercontent.com/484084/81217341-74805080-8faa-11ea-85ed-34fef64dfd53.png)
![image](https://user-images.githubusercontent.com/484084/81217357-7a763180-8faa-11ea-98b9-730d6181d2dd.png)

**Comment by teodorlu** [comment]
@jorda0mega Does that give you a Clojure REPL or a CLJS repl? Because I seemed to get a Clojure REPL (see post above)

**Comment by avichalp** [comment]
Hey @teodorlu,

I am using Cider. I don't do `lein dev` to begin the workflow instead I use `cider-jack-in-clj&cljs` function provided by Cider. It will launch both the repls and connect to it automatically.

I get both CLJ and CLJS repls. 

<img width="1414" alt="Screen Shot 2020-05-07 at 5 41 05 PM" src="https://user-images.githubusercontent.com/5305984/81314987-0743ec80-908a-11ea-8b50-abf9de37a28e.png">

**Comment by jorda0mega** [comment]
@teodorlu you can also jack-in which uses cider and you get both repls. Seems to be working for me. I've been able to modify the output to the console from it. Are you running into any issues?

**Comment by teodorlu** [comment]
Yeah, I got an error loading the CLJS REPL, so I ended up with two vanilla Clojure REPLs. I might have picked some wrong options after running jack-in.

Are you guys all on vanilla Emacs? I'm on Spacemacs.

**Comment by avichalp** [comment]
@teodorlu : What is the error? Did you figure out?

I use vanilla Emacs. Also, in the earlier comment, I mentioned about two repls. I now realized Athens, for now, is only a CLJS project. So just launching a CLJS repl is enough.

Trying to put down the steps I am using for now. Let us know if this works for you:

1. Make sure `cider-nrepl` is on the classpath. See [here](https://shadow-cljs.github.io/docs/UsersGuide.html#user-config).
2. Do `cider-jackin-cljs` when cider ask "which command to be used" select "shadow-cljs"
3. You should get at a CLJS repl with `shadow.user` as the default ns.
4. Now you can start watching the build and and start the repl for this build
```Clojure
(require '[shadow.cljs.devtools.api :as api])

(api/watch :app)
(api/repl :app)
```
5. Now you can navigate to `localhost:3000`. Once Athens on the Browser connects to the repl. You will be able to do both: eval functions and hot reloading.

**Comment by teodorlu** [comment]
@avichalp with your comment, I was able to get a browser-connected CLJS REPL up and running. Thanks a lot!

Slightly different from your instructions, I had to enter the `:app` build as a REPL option, but I did not have to run `(api/watch :app)` or `(api/repl :app)`.

![image](https://user-images.githubusercontent.com/5285452/81453821-e0211400-918a-11ea-804f-0be7311fb4b5.png)

**Comment by teodorlu** [comment]
> Made a tutorial on how to use a browser-connected REPL with shadow-cljls.
> Tutorial: https://youtu.be/W4FXpANSJGQ
> Notes: https://roamresearch.com/#/app/ego/page/aARLhmFxm
>
> Let me know if this is sufficient @teodorlu

Thanks, @tangjeff0! Just ran thorugh it, and it got me going. Appreciate the effort you're spending on docs & community -- a custom video tutorial for getting started is fine service!

**Comment by teodorlu** [comment]
Closing since I opened and consider this good enough.

If anyone want to discuss merging any of this into docs, feel free to open again.
