### ISSUE TITLE
`:selected/delete-items`

### ISSUE THREAD

**Issue by filipesilva** [athensresearch/athens#1414]

**Comment by sid597** [comment]
The current implementation of this event is partially wrong, here's why with an example:

The terminology used in the example, 
 - every line starting with `-` is a block
 - In `-0 -> 0`  
    - `-0` represents the content inside the block here it is `0`
    - `-> 0` represents the block order of the block here the block order of this block is 0
   
```
Original     | Expected  | Result 
             |           |
-0 -> 0      | -0 -> 0   | -0 -> 0
   -1 -> 0   | -3 -> 1   | -3 -> 2
-2 -> 1      |           |
-3 -> 2      |           |
```
If we select blocks `-2 -> 1` and ` -1 -> 0` **in that order** and then delete them, we will get the result as shown in the example above. 

In general, the issue with the current implementation is, if blocks are selected from down to up then the siblings of the first block that was selected will not be reindexed.
