### ISSUE TITLE
Selecting blocks from down to up makes some events produce wrong results

### ISSUE THREAD

**Issue by sid597** [athensresearch/athens#1451]
This issue was found in #1414, so I will take that event as an example to explain this issue.  

The current implementation of the event (`:selected/delete`) where one selects multiple blocks from down to up  is  wrong, here's why with an example:

The terminology used in the example, 
 - every line starting with `-` is a block
 - In `-0 -> 0`  
    - `-0` represents the content inside the block here it is `0`
    - `-> 0` represents the block order of the block here the block order of this block is 0
   
```
Original     | Expected  | Result 
             |           |
-0 -> 0      | -0 -> 0   | -0 -> 0
   -1 -> 0   | -3 -> 1   | -3 -> 2
-2 -> 1      |           |
-3 -> 2      |           |
```
If we select blocks `-2 -> 1` and ` -1 -> 0` **in that order** and then delete them, we will get the result as shown in the example above. 

In general, the issue with the current implementation is, if blocks are selected from down to up then the siblings of the first block that was selected will not be reindexed.

**Comment by neotyk** [comment]
Please check if it is still the case with new selection fixes in RTC branch.

**Comment by sid597** [comment]
Tested with `:selected/delete` and `:drop` events, working as expected
