### ISSUE TITLE
Will it support something like a Markdown code block?

### ISSUE THREAD

**Issue by changye01** [athensresearch/athens#1460]
**Please ask questions on our [Discord](https://discord.gg/HNmxvpm)**

You will get a response far faster in our Discord, plus the Athenians are awesome :)
Sometimes I want to write some code in my notes, but I don't find a beautiful way to write it,
So I wonder, does Athens support writing like Markdown 
like this
```
code
```
or 
![image](https://user-images.githubusercontent.com/28428761/127463114-fcad69dc-588b-4284-bb22-3a1928c0de3b.png)

**Comment by Victor239** [comment]
Duplicate https://github.com/athensresearch/athens/issues/989

**Comment by changye01** [comment]
Duplicate
