### ISSUE TITLE
Test DB Switcher and refactored code

### ISSUE THREAD

**Issue by sid597** [athensresearch/athens#1469]
Test the following things after #1429 

- [ ] Db switcher: Check if we can switch between local and remote DB
- [ ] Local storage: After refactor check if values that should be persisted are actually being persisted
- [ ] FIlesystem: Check if adding, moving, deleting works for the filesystem
- [ ] Boot: Check if boot works for both local and remote setting

All of the above are also interlinked so can test them in the following way : 
 - [ ]  Add a new DB: Tests Filesystem, boot, and DB switcher
 - [ ]  Restart Athens to see if the newly added DB is there along with all the previous DB: Tests local storage, boot 
 - [ ]  Open a new DB : Tests Filesystem, boot, DB switcher
 - [ ]  Restart Athens to check if DB added in the last session is still there and is selected by default: Tests local storage
 - [ ]  Move the current DB: Tests Filesystem, DB switcher
 - [ ]  Delete a DB: Tests Filesystem, DB switcher
 - [ ]  Restart Athens and check if delete is reflected in the list : Tests local storage
 - [ ]  Select a DB from the list: Tests Filesystem, boot, and DB switcher
 - [ ]  Check sync: Make changes in the current DB and check if the sync is working
 - [ ]  Change DB while sync: Should not be able to switch DB while the sync is in progress in current DB
 - [ ]  Select a db which is deleted from disk : Tests DB switcher and Filesystem
 - [ ]  Delete the last DB in list: Should not be able to delete the last remaining DB in the list : Tests DB switcher
 - [ ]  Remote DB: Some of the above tests can also be donw keeping remote db in mind

**Comment by filipesilva** [comment]
Awesome work getting this together Sid! Moved these into #1427 so we can track them from one place.
