### ISSUE TITLE
TypeError: Cannot read Property 'D' of null

### ISSUE THREAD

**Issue by linjorejoy** [athensresearch/athens#1476]
**Problem**
The Page in the Sidebar still persists even after deleting it with this option.

![image](https://user-images.githubusercontent.com/52414609/128602117-e80e840f-1260-4084-bbae-a72c929c98ba.png)

But it is non-edtable. Probably because it was deleted, but was still being rendered in the Sidebar.

When I tried deleting it again, I got this error.

```
message=Uncaught TypeError: Cannot read property 'D' of null
...AppData/Local//Programs/Athens/resources/app.asar/resources/public/js/compiled/r...
Lineno=4165
colno=345
error=TypeError: Cannot read property 'D' of null
```

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/52414609/128602092-1aebd066-883d-4f50-9bf0-fbd430f5e0c0.png)

**Athens Version**
> Athens 1.0.0-BETA.92

**Comment by juniusfree** [comment]
duplicates #1350
