### ISSUE TITLE
Can't collapse blocks (ALPHA.RTC.1 - Local DB)

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1490]
**Problem**
When using the new ALPHA.RTC.1 with a local DB, I can't collapse any block.
Clic on the arrow won't do anything.

**Athens Version**
1.0.0-ALPHA.RTC.1 - Intel OSX

**Comment by juniusfree** [comment]
Problem: `:drop/open` is not dispatched in remote

**Comment by sawhney17** [comment]
^^You can't uncollapse either
