### ISSUE TITLE
Block doesn't render when clicking outside (ALPHA.RTC.1 - Local DB)

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1491]
**Problem**
When I edit a block, I expect it to be rendering when I clic outside of it.
When using the new ALPHA.RTC.1 with a local DB, I have to edit another block for the block to render.
Clicking outside of it won't work.

**Screenshots/Demo**
https://user-images.githubusercontent.com/24638389/129580265-a8cdd833-46be-4864-9c89-5e1713e7baa6.mov

**Athens Version**
1.0.0-ALPHA.RTC.1 - Intel OSX

**Comment by neotyk** [comment]
Might be that we're not clearing `:editing/uid` after text field loses focus.

**Comment by juniusfree** [comment]
@filipesilva This is the cause of the regression. https://github.com/athensresearch/athens/commit/c44ad773c98f1aa8ce0b06d312bedb19f632c0a0 I'm curious why we shouldn't send the block-uid with `nil`. Should we revert this or find another way to handle the on-blur event for block?

**Comment by filipesilva** [comment]
Fixed by #1562
