### ISSUE TITLE
Problem with the daily pages scroll (ALPHA.RTC.1 - Local DB)

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1492]
**Problem**
When using the new ALPHA.RTC.1 with a local DB, there is a problem with the daily pages scrolling down :
* If the daily page already exists, it will act as usual
* If the daily page doesn't exist, it will create it then jump out of the "daily mode"

And when I click to the "daily page" button, it will jump to the latest opened daily page (not today's page)

**Screenshots/Demo**
https://user-images.githubusercontent.com/24638389/129581245-03edaa74-a340-4ada-b732-ab28dc902c81.mov

**Athens Version**
1.0.0-ALPHA.RTC.1 - Intel OSX

**Comment by filipesilva** [comment]
Fixed by #1492
