### ISSUE TITLE
Some bullets are not round ? (ALPHA.RTC.1 - Local DB)

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1495]
**Problem**
Some bullets are not round.
Couldn't manage to find a systematic way to create these "not round" bullets

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/24638389/129586743-2e30e49e-9a2d-489a-9cba-1ab0ff9fb807.png)

**Athens Version**
1.0.0-ALPHA.RTC.1 - Intel OSX

**Comment by sid597** [comment]
I don't know why but I find this bug funny 😅.

**Comment by Limezy** [comment]
@sid597 could you reproduce it ?

**Comment by juniusfree** [comment]
https://discord.com/channels/708122962422792194/708124156113321985/878291231376023583

**Comment by filipesilva** [comment]
Fixed by #1595
