### ISSUE TITLE
fix: Unable to create a new block (1.0.0-alpha.rtc.1)

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#1499]
**Problem**
GIVEN an empty block, WHEN the user presses enter, THEN a new block should be created.

Current result: 
![image](https://user-images.githubusercontent.com/8164667/129629083-92038701-aa36-4338-887d-7dd7a4e073b3.png)

**Athens Version**
1.0.0-alpha.rtc.1

**Comment by neotyk** [comment]
Not ok with schema and also using `eid` which should not be the case, only `uid`s allowed to be used in events.
