### ISSUE TITLE
Setup unit/generative testing

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#15]
Requested by @anshbansal to test parser functionality.

Resources:
- https://clojurescript.org/tools/testing
- https://shadow-cljs.github.io/docs/UsersGuide.html#_testing
- https://clojure.org/guides/spec#_testing
- https://github.com/lambdaisland/kaocha
- https://github.com/redplanetlabs/specter
- https://github.com/clojure/test.check
- https://www.clojure-toolbox.com/ `ctrl-f` test

**Comment by teodorlu** [comment]
I've been playing around (a tiny bit) with parsing myself, and I think this could be very useful outside of athens; a small `athens.markup-parser` in cljc on Clojars.

**Comment by teodorlu** [comment]
I've got great experiences with Kaocha, though I don't know how well Kaocha plays with Shadow-CLJS: https://github.com/lambdaisland/kaocha

**Comment by tangjeff0** [comment]
>  a small athens.markup-parser in cljc on Clojars.

Please see my response in #5

**Comment by tangjeff0** [comment]
> Kaocha 

Good tip, will check it out. Never a shortage of testing tools. There's JS, CLJS, but some of these libraries could be `cljc` as well.

**Comment by teodorlu** [comment]
> Please see my response in #5

Sorry, I don't understand which response you're referring to. My comments might be better suited for isse #5, though.

**Comment by anshbansal** [comment]
> Requested by @anshbansal to test parser functionality.

Given all the issues that are happening in roam it seems they have not written enough automated tests. If we want this to be reliable IMHO we need to write tests from the beginning and have a good test coverage. Unit tests are a start.

Eye-balling things just does not scale as code base grows and there are more features.

**Comment by teodorlu** [comment]
We could even look into generative testing if we want to get all the "recursive cases" right. Could be interesting to write a generator for "valid roam syntax".

**Comment by tangjeff0** [comment]
After doing some research, I've realized that there are many ways to do testing in Clojure. I edited my initial comment to include more resources. However, I'd like to put a call out for more help here.
