### ISSUE TITLE
fix: `:enter/bump-up` is not working in remote (1.0.0-alpha.rtc.1)

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#1501]
**Problem**
Typo error in https://github.com/athensresearch/athens/blob/feature/rtc-v1/src/cljs/athens/events/remote.cljs#L635
![image](https://user-images.githubusercontent.com/8164667/129637955-57cb1ab2-66de-4254-b65c-1aa02db96b8c.png)

And not registered in schema
![image](https://user-images.githubusercontent.com/8164667/129634022-f98d7172-d9d1-4524-b739-cab73636fe65.png)

**Athens Version**
1.0.0-alpha.rtc.1

**Comment by neotyk** [comment]
typo in remote
