### ISSUE TITLE
fix: unable to create an empty child when the embedded block has no children (1.0.0-alpha.rtc.1)

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#1502]
**Problem**
GIVEN an active embedded block with no children,
AND the cursor is positioned at the end of the block
WHEN the user presses enter,
THEN a new child should be created.

Current result: a new child is not created

**Screenshots/Demo**
![enter-open-block-add-child](https://user-images.githubusercontent.com/8164667/129635850-6a71a313-189e-464b-9ae4-de4b3fc5f707.gif)

**Athens Version**
1.0.0-alpha.rtc.1

**Comment by neotyk** [comment]
Needs investigation

**Comment by juniusfree** [comment]
@sid597 still getting an error.
![image](https://user-images.githubusercontent.com/8164667/129719525-23886b86-a1b5-4aa5-b8d6-8533887e9df7.png)

**Comment by sid597** [comment]
Looking into it
