### ISSUE TITLE
fix: Cannot unindent selected, indented blocks (1.0.0-alpha.rtc.1)

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#1503]
**Problem**
GIVEN selected, indented blocks,
WHEN the user presses SHIFT+TAB,
THEN the blocks should unindent

Current result: The blocks are still indented

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/8164667/129637293-50011a25-b329-4845-8d29-c48a91a85364.png)

**Athens Version**
1.0.0-alpha.rtc.1

**Comment by neotyk** [comment]
Nil event dispatched
