### ISSUE TITLE
fix: unable to indent multiple blocks (1.0.0-alpha.rtc.1)

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#1504]
**Problem**
GIVEN selected, unidented blocks,
WHEN the user presses TAB,
THEN the blocks should indent

Current result: The blocks are not indented

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/8164667/129689549-99169bb1-015c-4916-8cb2-da226b604133.png)

**Athens Version**
1.0.0-alpha.rtc.1

**Comment by neotyk** [comment]
Nil event dispatched
