### ISSUE TITLE
fix: The drop events are not working in remote (1.0.0-alpha.rtc.1)

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#1506]
**Problem**
The following drop events methods are not dispatched:

1. :datascript/drop-child
2. :datascript/drop-multi-child
3. :datascript/drop-link-child
4. :datascript/drop-diff-parent
5. :datascript-drop-multi-diff-source-same-parents
6. :datascript-drop-multi-diff-source-diff-parents
7. :datascript/drop-link-diff-parent
8. :datascript/drop-same
9. :datascript/drop-multi-same-source
10. :datascript/drop-multi-same-all
11. :datascript/drop-link-same-parent 

**Athens Version**
1.0.0-alpha.rtc.1

**Comment by neotyk** [comment]
(maybe) Event types on client side are not in sync
