### ISSUE TITLE
fix: `:remote/unlinked-references-link` is not working (1.0.0-alpha.rtc.1)

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#1507]
**Problem**

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/8164667/129696400-2d570de0-a946-4299-be61-e564eb2fa123.png)

**Athens Version**
1.0.0-alpha.rtc.1

**Comment by neotyk** [comment]
Event types on client side are not in sync
