### ISSUE TITLE
fix: `:remote/unlinked-references-link-all` is not working (1.0.0-alpha.rtc.1)

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#1508]
**Problem**

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/8164667/129696999-eb9ed45e-5aa4-452a-a123-64fddc865342.png)

**Athens Version**
1.0.0-alpha.rtc.1

**Comment by neotyk** [comment]
Event types on client side are not in sync
