### ISSUE TITLE
Presence pic broken for new user

### ISSUE THREAD

**Issue by filipesilva** [athensresearch/athens#1509]
From [Sawney on Discord](https://discord.com/channels/708122962422792194/876710267231305728/877101710697451590)

Investigating and reproduced the issue. When a new user joins the server, for the other users in the sever, the profile pic/letter is not showing but for the person who just joined, they can see everyone else's.

![image](https://user-images.githubusercontent.com/4172079/129697510-03981d7a-b5d1-4d73-ba46-d666bc5fc540.png)

**Comment by juniusfree** [comment]
I'll come back to this later. So far, what I found is that the 1st user has incomplete data of the 2nd user in the app-db.

In this example, the 1st user's ("Dionysus") app-db has incomplete data of the 2nd user ("Zeus"). It has no color, etc.
![image](https://user-images.githubusercontent.com/8164667/129809135-9ce476b2-0ad0-4f82-94d0-ada36d8564f8.png)

This is the app-db of the 2nd user ("Zeus")
![image](https://user-images.githubusercontent.com/8164667/129809503-5d331c0b-7750-423f-b5d3-2f25304ba504.png)

This problem might also be related to https://github.com/athensresearch/athens/issues/1515 & https://github.com/athensresearch/athens/issues/1517
