### ISSUE TITLE
Graph view is broken (1.0.0-ALPHA.RTC.1 - Remote DB)

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1518]
**Problem**
Graph view is broken

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/24638389/129734297-c53e6aae-608b-4430-88a5-a0bfda69b855.png)

**Athens Version**
1.0.0-ALPHA.RTC.1 - Intel OSX

**Comment by sawhney17** [comment]
Unable to repro on an M1 mac.

**Comment by juniusfree** [comment]
Unable to reproduce in WSL2

**Comment by juniusfree** [comment]
I'm still unable to reproduce this. When the `:current-route/name` is `nil`, `match-page` returns to the route to daily page which is the default case.

**Comment by Limezy** [comment]
Turned out to be a problem in my dev environment. Didn't understand what was happening but ticket can be closed.
