### ISSUE TITLE
Can't delete a page (1.0.0-ALPHA.RTC.1 - Remote DB)

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1519]
**Problem**
When deleting a page, nothing happens

**Athens Version**
1.0.0-ALPHA.RTC.1 - Intel OSX

**Comment by juniusfree** [comment]
I can't replicate in the latest update https://github.com/athensresearch/athens/commit/06f7a273c37e3f3f4016583c5d0dd488d3d565d5
