### ISSUE TITLE
Two clients connecting with the same name will break basically everything (1.0.0-ALPHA.RTC.1 - Remote DB)

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#1520]
**Problem**
Everything is in the title !

**Athens Version**
1.0.0-ALPHA.RTC.1 - Intel OSX

**Comment by Limezy** [comment]
Break = both same named users can't create or edit any new block

**Comment by filipesilva** [comment]
Seems to be fixed atm, unsure what PR fixed it though.
