### ISSUE TITLE
Let user know that Lan-Party is over/suspended

### ISSUE THREAD

**Issue by neotyk** [athensresearch/athens#1598]
**What?**

Communicate to user that Athens client is disconnected from Lan-Party.

**Why?**

When we loose connection with Lan-Party player is unaware of it.
We should let the player know that Athens client is disconnected from Lan-Party.

**How?**

*Find 3 Solutions*

**Comment by juniusfree** [comment]
This seems a bug. I'm expecting that given the server is down, and the client is reconnecting, when the client changes from remote db to local db, then the client should stop reconnecting. Currently, it still continues to reconnect. I'll get back to this later.

**Comment by filipesilva** [comment]
Fixed by #1601
