### ISSUE TITLE
fix: error when deleting a block with block ref

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#1603]
I'm expecting that the block should be deleted when backspace is pressed for a block with block ref but the whole text content is removed.

![delete-block](https://user-images.githubusercontent.com/8164667/131242859-18d46aac-c17c-44e0-b403-0acfbf252105.gif)

It seems related to the linkmaker but this could also be just an effect. This is what linkmaker returned.
`[[:db/retractEntity 280] {:db/id [:block/uid "e2138185b"], :block/string "", :block/children []} {:db/id 225, :block/children #{}} [:db/add nil :block/refs [:block/uid "f43cf5ad6"]]]`

Removing `[:db/add nil :block/refs [:block/uid "f43cf5ad6"]` in the transaction fixes the issue.

**Comment by juniusfree** [comment]
3 solutions to fix the linkmaker
1. create an fn to remove retracted blocks
2. refactor `parseable-string-datom` to exclude retracted blocks
3. investigate further why `string-as-lookup-refs` is still returning the block even it uses `db-after`

**Comment by neotyk** [comment]
@filipesilva can you please help Junius here, it's LinkMaker :)

**Comment by filipesilva** [comment]
@juniusfree let's pair on this, would like to see the details about what's happening.

**Comment by juniusfree** [comment]
@filipesilva sure. So far, what I found is that linkmaker is adding a ref to a deleted block that's why this transaction with `nil` eid,  `[:db/add nil :block/refs [:block/uid "f43cf5ad6"]`
