### ISSUE TITLE
Clicking on block references counter throws error

### ISSUE THREAD

**Issue by sawhney17** [athensresearch/athens#1680]
**Problem**
Clicking the block reference counter anywhere throws an error. 
**Screenshots/Demo**
<img width="797" alt="Screen Shot 2021-09-26 at 19 03 32" src="https://user-images.githubusercontent.com/80150109/134813270-9a17e1b9-7c58-4180-8352-38222a8c7d6c.png">
<img width="881" alt="Screen Shot 2021-09-26 at 19 03 49" src="https://user-images.githubusercontent.com/80150109/134813280-b71823d7-a08e-4a5c-bf68-001e578a7a5e.png">

**Athens Version**
Athens Beta 97

**Comment by dyfrgi** [comment]
I am still getting this error in 0.98. Is there some step I need to take after updating? Are the references stored in some way?
