### ISSUE TITLE
Bad work on the Windows 7 x64

### ISSUE THREAD

**Issue by JetV** [athensresearch/athens#1714]
**Problem**
Close/Minimize/Full-Screen buttons not working (after restart application too). 
**Screenshots/Demo**

**Athens Version**
1.0.0-alpha.rtc.17

**Comment by artistro08** [comment]
I have this problem in 1.0.0-alpha.rtc.29

**Comment by mamahnxarya201** [comment]
Same problem on windows 11 x64 21H2 OS Build 22000.282 using 1.0.0-alpha.rtc.31

**Comment by nsvrana** [comment]
This isse remains on Windows 11 for build v2.0.0-beta.3

**Comment by nsriv** [comment]
Experiencing the same issue on Windows 10 with v1.0.0-alpha.rtc.38

**Comment by sid597** [comment]
@JetV @scavi-github @JBuzzard @artistro08 @mamahnxarya201 @nsvrana @nsriv This issue is fixed in Athens 2.0.0-beta.5 you can download the new client [here](https://github.com/athensresearch/athens/releases/tag/v2.0.0-beta.5) 

Thank you @weckd for the PR :)
