### ISSUE TITLE
Demosite down

### ISSUE THREAD

**Issue by letharion** [athensresearch/athens#1718]
**Problem**
Following the link to the demo (https://athensresearch.github.io/athens) from the main github page, initial page load just yields:

```
message=Error: No matching clause: 
source=https://athensresearch.github.io/athens/js/compiled/app.js
lineno=8398
colno=15
error=Error: No matching clause: 
```

**Comment by hustodemon** [comment]
To be fair, I experienced this issue the 1st time I tried athens, too... So I created a PR proposal for basic warnings in case the browser is unsupported #1720.

**Comment by aadilayub** [comment]
Is there a missing feature or something that prevents the app from working on Firefox?

**Comment by D-side** [comment]
I second @aadilayub, it was working just fine in Firefox a couple weeks ago, and now with #1876 it now flat out refuses to.
Would it perhaps be a better idea to revert it for now and consider a less disruptive and more explanatory warning in its place?
With a message along the lines of:
> You are using a browser that might not fully support this live demonstration of Athens. Since the app is built with Electron, it's only expected to run well on Chrome and other Chromium-based browsers. But browser support is not currently a goal for Athens, it's meant to be used as a standalone application.

**Comment by hustodemon** [comment]
Hey guys, for me it never worked with Firefox and since it's an electron app, I supposed it can't even work on non-chrome-based browsers. But I might be wrong. In any case, I think it'd be great if an Athens developer could shed more light on this. Perhaps @filipesilva ?

**Comment by D-side-BL** [comment]
Well, it did 🙂
So I think we're looking at a slight misdiagnosis here at the very least.
Followed up by a good fix, just for an unconfirmed problem. 🤷

At a glance given this symptom I can only hypothesize that there's a `case` form somewhere that didn't produce a match ([here's where this is defined](https://github.com/clojure/clojurescript/blob/r1.10.914/src/main/clojure/cljs/core.cljc#L2368)), so at least the origin is in the realm of ClojureScript. But where and whether it's even in Athens, I didn't get much further, so ideally it would be great to reproduce this problem and investigate the stack trace. I'd love to try, I've done some Clojure before, but my browser was totally okay with the past versions of the live demo, so I don't think I'd get the error in the first place 🤔
…
What I didn't try back then though, is a clean Firefox with no extensions, but I don't think I'm using any that might make it look more like Chrome. And I doubt anything of that caliber can easily bridge browser incompatibilities, though that'd be cool 😅

_My understanding_ (fwiw) of this live demo setup is that it is more of a byproduct of Athens being based on browser tech, which is just a convenient leverage for producing a low-barrier (for lack of download & installation) live demo quickly. And when it works, it works. When it doesn't — ah, well, will have to recommend a full installation, which is a higher entry bar, but at least a full experience.
