### ISSUE TITLE
Athens crashes when you expand the "unlinked references" at the bottom of a page.

### ISSUE THREAD

**Issue by PlunderStruck** [athensresearch/athens#1723]
**Problem**

When trying to expand the "unlinked references" at the bottom of a page, the application throws an error message that reads: 

message=Uncaught TypeError: Cannot read property 'indexOf' of null
.../users/*myname*/AppData/Local/Programs/Athens/resources/app.asar/resources/public/js/compile...
lineno=1428
colno=399
error=Type: Cannot read property 'indexOf' of null

And then the screen goes black until I force close the application.

**Screenshots/Demo**

![bug report](https://user-images.githubusercontent.com/92281127/136721177-e87f5244-46b2-4d28-9fbf-c23a79b69a79.png)

**Athens Version**

1.0.0-ALPHA.RTC.17

**Comment by ryantriangles** [comment]
Also occurring with the Linux AppImage, both v1.0.0-alpha.rtc.28 and v1.0.0-alpha.rtc.29, but with the TypeError being thrown on renderer.js:7291.
