### ISSUE TITLE
Gitbook link in "About" section not working 

### ISSUE THREAD

**Issue by samuel-l-schmidt** [athensresearch/athens#1774]
**Problem**
The link https://app.gitbook.com/@athensresearch/s/handbook/ in your About section takes me to an empty gitbook. 
While searching for similar issues, I found this link: https://handbook.athensresearch.org/ which seems to work. 
I use Firefox. 

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/49971875/139528404-cfd40086-f0af-4b7a-b15e-fde28ab90cfb.png)

**Athens Version**

**Comment by scottrblock** [comment]
perhaps related, this link in the contribution guide is broken for me in mobile safari and desktop chrome — https://athensresearch.github.io/athens/cards.html

I can open a separate issue for this, but seems related.

**Comment by tangjeff0** [comment]
Updated for both! Please see https://github.com/athensresearch/athens/tree/feature/rtc-v1/doc/adr if you want more docs, that haven't been merged yet.

Components are now on Storybook at https://athens-lovat.vercel.app/?path=/story/concepts-welcome--many-databases
