### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#18]
Core meat of this issue is writing logic to scan through user's `:node/title`s and `:block/string`s when the input is changed, and showing first N recommendations. Don't worry too much about nice looking dropdown and other UX things. Can be handled by later issues when making user-friendly.

Search with `[[]]` and `(())` are actually subproblems of the search bar, since the search bar queries titles and blocks.

# Demo
![search](https://user-images.githubusercontent.com/8952138/81104703-eab88080-8ee0-11ea-80c8-b64afcde1a42.gif)

**Comment by jeroenvandijk** [comment]
FYI made a start here #20

**Comment by tangjeff0** [comment]
Superseded by #126 
- [ ] should be trivial to do inline search now
