### ISSUE TITLE
Youtube Embed is not working on desktop application

### ISSUE THREAD

**Issue by learnuidev** [athensresearch/athens#1889]
**Problem**

Youtube Embed is not working on desktop application

**Screenshots/Demo**

https://user-images.githubusercontent.com/67298065/144722526-6e9773d1-206a-4608-bfa7-aacb770dfc61.mov

**Athens Version**

Version 2.0.0-beta.1 (2.0.0-beta.1)

**Comment by learnuidev** [comment]
Might have to do something with same origin issue
<img width="1424" alt="Screen Shot 2021-12-04 at 3 13 37 PM" src="https://user-images.githubusercontent.com/67298065/144723324-41f2549d-e4ec-4dd4-af82-8f71e629f41d.png">

**Comment by sid597** [comment]
Not anymore :) fixed in v2.0.0-beta.5
