### ISSUE TITLE
Can not delete a [[]] page

### ISSUE THREAD

**Issue by l2dy** [athensresearch/athens#1913]
**Problem**
I can not click into a page with empty title in all pages or graph view. In 1.0.0, I can click into that page from all pages and delete it.

**Athens Version**
v2.0.0-beta.5

**Comment by l2dy** [comment]
v2.0.0-beta.4 automatically generates a [[]] page in a new database, and can be used to reproduce the problem.

**Comment by sid597** [comment]
This issue is fixed in v-2.0.0-beta.5

**Comment by l2dy** [comment]
> but we still need to fix for users that already have this empty page in their db

That is the point of this issue.
