### ISSUE TITLE
Displaying incorrect icon when expanding and closing the content on the right side bar.

### ISSUE THREAD

**Issue by prabhath6** [athensresearch/athens#200]
**Displaying incorrect icon when expanding and closing the content on the right side bar.**
Displays ChevronRight icon all the time.

**Expected Behavior**
* Display the ExpandMore icon when the content is collapsed.
* Display the ChevronRight icon when the content is expanded.

**To Reproduce**
Pull in latest master, build and deploy.

**Screenshots**
![collapse and expand](https://user-images.githubusercontent.com/10682370/86205221-eef2ca00-bb2e-11ea-968f-7ab8e66f6cbf.gif)

**Solution**
Since the [button function](https://github.com/athensresearch/athens/blob/master/src/cljs/athens/devcards/buttons.cljs#L65) is returning the label I think it is as simple as checking the state and retuning the icon.

**Comment by prabhath6** [comment]
If no one is working on the fix currently, i want to take this issue. I have tested the fix locally and it works.

**Comment by tangjeff0** [comment]
Hi @prabhath6 , great work. I think @shanberg already made a fix locally but it hasn't been pushed yet.

You don't need to ask for permission. Next time just create the PR directly so we can review your code!
