### ISSUE TITLE
fix(icons): replace `r/create-element` with `r/adapt-react-class`

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#207]
- no longer need `span`
- can pass `style` directly too as second parameter. see [here](https://github.com/reagent-project/reagent/issues/369)

**Comment by itsrainingmani** [comment]
Hi Jeff,

I've made the changes to `icons.cljs` on a branch and tested that the icons render on my localhost version of `devcards`.

Can I submit a PR for this?

**Comment by tangjeff0** [comment]
@itsrainingmani please first enable GitHub actions so I can see a demo :)

**Comment by itsrainingmani** [comment]
@tangjeff0 Got the GitHub Actions to [work](https://github.com/itsrainingmani/athens/actions/runs/158825275) but I don't see the deploy yet. I'm assuming it takes some time the first time around?

**Comment by tangjeff0** [comment]
@itsrainingmani have to Push again

**Comment by itsrainingmani** [comment]
@tangjeff0 Ok It's deployed now :). https://itsrainingmani.github.io/athens/cards.html#!/athens.devcards.icons

**Comment by tangjeff0** [comment]
Submit a PR now!
