### ISSUE TITLE
Create daily notes of past days

### ISSUE THREAD

**Issue by martin-braun** [athensresearch/athens#2099]
Today I had to reset my clock to yesterday, because it was after midnight and I wanted to create the page for the day that had just past. Creating a daily note by hand would not mark it to be a daily note for the graph, so I had to adjust my system date to create a proper daily note for yesterday.

It would be nice if I could create a daily note of past days, so I'm not forced to start the daily note on the day that it's referring to.

**Comment by ofer1992** [comment]
I think this happens if you scroll down in the "daily page" page

**Comment by martin-braun** [comment]
@ofer1992 Haha, I had no idea I could scroll down the today's page to go back into the past and even generate missing dates this way. Thank you for teaching me.

I assume that there is no issue with it, so I will try this next time I miss to document a day. 

@tangjeff0 maybe it makes sense to show a little visual indicator on the bottom of the daily page so it's intuitive to the user that he/she can scroll further down to access earlier days.
