### ISSUE TITLE
Athens photo with gradient pixelization

### ISSUE THREAD

**Issue by neuroradiology** [athensresearch/athens#210]
This is an unsolicited modification; I know that's a bit obnoxious, and I'm starting off on the wrong foot. Having said that, I tried to discuss on discord but after I followed the link, created an account, confirmed my email, and went to the channel I couldn't post. (The error was "You do not have permission to send messages in this channel" showed up in the chat submission box.)

Anyway: this is basically an aesthetic/art-based pull request consisting of a modified version of the Athens photo that appears on the github front page. Since there's no code, there's nothing to actually "push"; so sorry again if I'm going about this the wrong way.

It is stylized to be highly pixelated in the upper left corner, and full-res in the bottom right.

It's meant to symbolize the functionality of Athens, which captures any information in the real world, and casts it in digital form.

I permit all uses without restriction under a CC0 copyright, and hereby assign all future copyright to the github user "athensresearch".

If you don't like it, I'm totally fine with silent rejection :). I'll take the hint if the thread is closed :)

![athens-puk-patrick-pixel-gradient](https://user-images.githubusercontent.com/8550951/86469799-2799cb80-bd08-11ea-9b0f-ea1e7cdfed78.jpg)

**Comment by tangjeff0** [comment]
Hi @neuroradiology, thanks so much for this. This is a really interesting idea, I wonder what @athensresearch/designers thinks?

Regarding the Discord, make sure you react to the message in `#welcome`. Then you should have access to the `#introductions` channel!
