### ISSUE TITLE
2.0.0beta30 on Linux (Gnome, Wayland): minimize, maximize, close buttons don't work

### ISSUE THREAD

**Issue by seltzered** [athensresearch/athens#2153]
**Problem**
In the UI experienced in switching from 2.0.0beta20 to 2.0.0beta30, the minimize, maximize, and close buttons don't respond to mouse clicks.

**Screenshots/Demo**

https://user-images.githubusercontent.com/297435/164135879-8113b0ba-a57a-4fdc-ace0-2aa96192ad0d.mp4

**Athens Version**
2.0.0beta30 appimage. Did not experience issue in 2.0.0beta20
Gnome 40.5, Ubuntu 21.10

**Comment by filipesilva** [comment]
Heya, #2154 released in 2.0.0-beta.31 should fix this, sorry for the trouble!
