### ISSUE TITLE
Adding an invalid database URL will always return successful

### ISSUE THREAD

**Issue by kinekt4** [athensresearch/athens#2178]
**Problem**
Hi Devs,
* Athens web client allows you to add **any** arbitary endpoint as a database URL, even when no Athens server exists at that endpoint
* It even allows incomplete URLs
* There is no indication anything is wrong in the UI
* If you open up the console in developer tools you can see the following errors:
    * `:remote/client-connect! health-check failure`
    * `:remote/connection-failed`
    * `:stage/fail-db-load`
* And yet, the database details get added to the menu anyway
* Tested on Chrome, Chromium, Firefox, Opera

**Screenshots/Demo**
* Go here: https://athensresearch.github.io/athens
* Go to left menu
* Click `Add Database`
* Complete the form. Enter any string in the database URL.
* Click `Join`
* **Screenshot**: [database add](https://imgur.com/KxqyLJ1)

**Athens Version**
* <https://athensresearch.github.io/athens/>
* Windows: v2.0.0-beta.33
* Linux: v2.0.0-beta.33

**Comment by kinekt4** [comment]
Hi @filipesilva, I did a quick test and I can see an alert dialogue box has been added. However, after clicking `OK` the (invalid) database was still added to the database list. Should that be the case?

**Comment by filipesilva** [comment]
@kinekt4 that's the implemented behaviour right now, but I agree it's confusing and should change. Thanks for opening the issue for it!
