### ISSUE TITLE
Unable to run on Windows

### ISSUE THREAD

**Issue by anonieee** [athensresearch/athens#23]
When trying to run this on Windows with `lein dev` I'm getting a lot of `OutOfMemoryError`. When I visit `localhost:3000`, there's only a blank page (but with the correct tab title and icon). Is my computer simply not powerful enough to run this?

Also, the blank page's source code says this:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>athens</title>
  </head>
  <body>
    <noscript>
      athens is a JavaScript app. Please enable JavaScript to continue.
    </noscript>
    <div id="app"></div>
    <script src="js/compiled/app.js"></script>
  </body>
</html>
```

**Comment by nthd3gr33** [comment]
What version of JDK are you using?

**Comment by anonieee** [comment]
I'm using version 14.0.1, should I downgrade?

**Comment by anonieee** [comment]
I figured it out, I registered my JDK path entry too low in the order, so it was picking up an older version of java instead. Should've checked `java -version`

**Comment by nthd3gr33** [comment]
I just set up 14.0.1 on a PC to help troubleshoot. Glad you got it figured out! 👍
