### ISSUE TITLE
Editable Block is overlaying on Athena

### ISSUE THREAD

**Issue by yg** [athensresearch/athens#230]
**Problem**

Editable Block is overlaying on **Athena**

#126

**Expected Behavior**

Editable Block **should not** overlay **Athena**

**To Reproduce**

1. Open Athens https://athensresearch.github.io/athens
2. Load test data
3. Open Athena and search (Ex: type athens)

**Screenshots**

https://www.loom.com/share/26289fcdaf88458babc0e2cda096687d

**Comment by tangjeff0** [comment]
CC @shanberg
