### ISSUE TITLE
Consider moving documents from Roam

### ISSUE THREAD

**Issue by JohnAtl** [athensresearch/athens#24]
Roam has been brought to its knees by the influx of new users. This means the documents linked from here to Roam are hard to access. Would it be possible to export them as markdown, and host them locally here on github?

**Comment by tangjeff0** [comment]
This is a great idea. There are also many "secret-features" all over Twitter, the help DB, public Roams, and Youtube. Would be great to aggregate all of them into a more authoritative source.

**Comment by FalconBFR** [comment]
Coda.io? Notion? Or Github wiki? I am happy to help, as long as someone provides clear instructions :)

The benefit of Coda.io over notion is that it has a commenting feature so we can comment over a some specific text. Both services are billed centrally, unlike slack, for around $10 dollars a month so participants don't have to pay a hefty price to contribute.

**Comment by tangjeff0** [comment]
Between Notion and Coda, I have used Notion much more than Coda.io. That being said, I think if there is any documentation in Notion, it should be limited to Notion-unique features, such as tables and embeds. I've already created an Athens Notion [here](https://www.notion.so/athensresearch/Public-67e1c6068cb449ff935d10e882fd9b05).

For most documentation, I think we should stick to a more standard platform, such as Github wiki as you suggest. Another alternative would be to add continue adding documentation to `doc` and generate a Gitbook (e.g. [reitit](https://metosin.github.io/reitit/), [practicalli](https://practicalli.github.io/clojure/)).

**Comment by FalconBFR** [comment]
No Problem. You are the owner of the project. Just set it up and I can help you migrate it while learning more about Clojure and how to manage a open source project :)

**Comment by tangjeff0** [comment]
Now that I think about it, I believe Notion is the strongest choice. The key differentiators for Notion are its tables and its usability. 
- Tables. Notion tables are second only to Airtable tables.
- Usability. Notion is the most general-purpose tool, in terms of both function and form. I imagine many end-users of Athens won't code, and I would prefer to steer away from the connotation of git, whether that be GitBooks or Github wiki.

The downside to Notion is that it is necessarily hosted (until we make an open-source version 🤔). Ultimately, I feel this tradeoff is worth it. Happy to hear any others' thoughts on these platforms or others not mentioned.

**Comment by tangjeff0** [comment]
Imported several docs that were on Roam to Notion. Find them in README.md and CONTRIBUTORS.md.

**Comment by tomisme** [comment]
Is the notion open or do we need an invite? I can't get in with the link above

**Comment by tangjeff0** [comment]
The root-level home page is not public yet, but you should be able to go to any of the links in the README or CONTRIBUTORS.md

**Comment by tangjeff0** [comment]
@tomisme The root-level home page is not public yet, but you should be able to go to any of the links in the README or CONTRIBUTORS.md
