### ISSUE TITLE
Add docs for connecting to REPL

### ISSUE THREAD

**Issue by prabhath6** [athensresearch/athens#248]
Update the contributing docs with details on how to connect to REPL.

- [x] [Cursive](https://cursive-ide.com/)
- [x] [CIDER](https://github.com/clojure-emacs/cider)
- [x] [Calva](https://marketplace.visualstudio.com/items?itemName=betterthantomorrow.calva)
- [ ] VIM plugins
   - [ ] [vim-iced](https://github.com/liquidz/vim-iced)
   - [ ] [conjure](https://github.com/Olical/conjure)
   - [ ] [fireplace](https://github.com/tpope/vim-fireplace)
- [ ] A video explaining on how/when to load namespaces and evaluate forms to iterate quickly while developing using REPL.

Include name and version number of the operating system, editor and any other plugins involved used by the editor for the development.

**Comment by tangjeff0** [comment]
@juniusfree did a mini tutorial on Discord for Calva: https://discord.com/channels/708122962422792194/708375112537342025/729621272987959396

**Comment by itsrainingmani** [comment]
CIDER - 

Editor - GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.3.0, Carbon Version 162 AppKit 1894.3) of 2020-04-27
OS - MacOS Catalina v10.15.5

Process - 

1. Navigate to any file within your local `athens` folder.
2. `M-x cider-jack-in-cljs`

<img width="421" alt="Screen Shot 2020-07-13 at 8 26 55 PM" src="https://user-images.githubusercontent.com/10191300/87369921-43db0b00-c547-11ea-8ed0-eaf3ddfe6252.png">

3. Choose `shadow-cljs`

<img width="568" alt="Screen Shot 2020-07-13 at 8 28 15 PM" src="https://user-images.githubusercontent.com/10191300/87369990-72f17c80-c547-11ea-9406-5f0dc98bec75.png">
You should see something like - 
<img width="568" alt="Screen Shot 2020-07-13 at 8 28 57 PM" src="https://user-images.githubusercontent.com/10191300/87370024-8866a680-c547-11ea-90fd-93b9fb3c9c7d.png">

4. Choose `shadow` and then you should be able to choose which `shadow-cljs` build to run
<img width="608" alt="Screen Shot 2020-07-13 at 8 35 12 PM" src="https://user-images.githubusercontent.com/10191300/87370382-615ca480-c548-11ea-85e6-853279ca3ec3.png">

5. You should see a new buffer open within your current Emacs window with a ClojureScript REPL - 
<img width="568" alt="Screen Shot 2020-07-13 at 8 33 36 PM" src="https://user-images.githubusercontent.com/10191300/87370474-a84a9a00-c548-11ea-8d10-72a24f812769.png">

**Comment by prabhath6** [comment]
Hey @itsrainingmani, I have my cursive changes almost done I can either include your CIDER config in that or, you can create a PR. Let me know what you prefer to do.

**Comment by itsrainingmani** [comment]
@prabhath6 Thanks for adding CIDER instructions 🙂 ! Didn't make sense for me to submit a separate PR for it.

**Comment by juniusfree** [comment]
@baibhavbista has written a detailed instruction for wsl+vscode users https://www.notion.so/Beginner-Clojure-Environment-Setup-Windows-36f70c16b9a7420da3cd797a3eb712fa

**Comment by prabhath6** [comment]
@juniusfree thanks for the link i will add it to the doc.

**Comment by baibhavbista** [comment]
Yeah, would love for the guide I wrote to be included in the doc. Meant to make a pull request but seem to have forgotten. A single PR like this, is better though. Separate PRs for separate environments would very soon be very overwhelming XD

**Comment by juniusfree** [comment]
I forgot to mention this. For vscode+calva, when you're in a project, you can connect to the repl just by running the `jack-in` command

https://github.com/athensresearch/athens/blob/master/CONTRIBUTING.md#calva is for .clj files outside a project.

**Comment by tangjeff0** [comment]
Closing this issue, good enough for now. Can re-open or start a new one when we have a larger chunk of docs we want to do.
