### ISSUE TITLE
Parse and render md images

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#25]
Basic markdown syntax: `![description](url)`

See the [linked md libraries](https://github.com/athensresearch/athens/issues/5#issuecomment-623520922).

Tricky part might be making the HTTP request.

No need to worry about resizing image since that requires writing datoms (e.g. Roam writes the height and width to `:block/props`). Can do that in Phase 2.

**Comment by jeroenvandijk** [comment]
@tangjeff0 Why do you think the HTTP request is tricky? Shouldn't that be automatic when React renders `<img src="<url-here>" />`? I might be missing something

**Comment by tangjeff0** [comment]
Hmm no I don't think you are. I believe I forgot about the `<img>` tag 😆 thought we needed an API call.

**Comment by jeroenvandijk** [comment]
Better safe, than sorry 😎

**Comment by gunar** [comment]
Head's up — I am on it (might take me little while but not too long)

**Comment by tangjeff0** [comment]
Sounds good - hope you've used Instaparse/EBNF-notation before! By the way, we're having more conversations in the Discord now, check out https://discord.gg/KaGuGV

**Comment by gunar** [comment]
I am familiar with EBNF. Will join Discord! Thanks

**Comment by gunar** [comment]
Draft PR: #149
