### ISSUE TITLE
fix(blocks): mobile editing not working under current keyboard event implementation

### ISSUE THREAD

**Issue by thesophiaxu** [athensresearch/athens#255]
*If you aren't sure about your bug, you can always join our [Discord](https://discord.gg/HNmxvpm) and ask in #agora or #engineering!*

**Problem**
The current method of catching keyboard events doesn't work for editing blocks on mobile.

**Expected Behavior**
When entering text on mobile, the corresponding content should be entered.

**Dependencies**
All recent builds using the new keyboard events system

**To Reproduce**
Try <https://athensresearch.github.io/athens/> using a phone and enter anything. The text would not appear correctly.

**Comment by itsrainingmani** [comment]
Hi @HaojiXu ,

What mobile browser did you try this on? I gave it a try using Chrome, Safari and Firefox on iOS and I'm able to edit and enter text inside blocks.

**Comment by HaojiXu** [comment]
@itsrainingmani I was using an android w/ lstest Chrome + Google keyboard. Perhaps Android handles keyboard input different than iOS?

**Comment by tangjeff0** [comment]
I do get input on mobile, but `[` doesn't auto-close.

**Comment by tangjeff0** [comment]
Not supporting mobile for now~
