### ISSUE TITLE
Right sidebar

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#26]
# Tasks

- [x] ~ drag and drop to re-order. We are using re-frame to manage right sidebar state as a hashmap. We want to be using datalog. This will allow us to persist **multiple** right sidebar states at once (these might be better called "Workspaces" and requires design). As it stands now, this is already better than Roam's. See #183 for an idea of how to re-order indices with datalog.
 - [x] fix the flicker on start. The right sidebar has a conditional class based on the open state (see code below). This is in contrast to the left sidebar, which has two completely distinct components based on open state. The good part about the former is that it gives us more control over animations via CSS keyframes. The downside is that we have to write more conditions within the component, which is more complex and is harder to maintain. This seems to be an engineering-design tradeoff, though there may be better workarounds. UPDATE: closed by #238

```
;; right sidebar 
  [:div (use-style sidebar-style {:class (if open? "is-open" "is-closed")})

...

;; left sidebar
    (if (not @open?)
```

### Original Post
<details>
  <summary>Click to open</summary>

# Re-design

The consensus seems to be that the right sidebar in Roam is not a finished feature, in its current state. I've included some of my personal likes and dislikes of the right sidebar below.

Ultimately, I believe the ambitious designers and product people will want to recreate the right sidebar from the ground-up.

Thus, my questions to them would be:

- What is the user's actual goal here?
- What are they trying to accomplish?
- Given this user goal, is a sidebar even the best solution?

Please provide a user story or flow to help me understand the problem and solution. 😄 

# Thoughts on Current Sidebar

### Likes
- The very fact that it exists is extremely useful. Even an incomplete right sidebar seems to beat not having one at all (sorry Notion!)
- The way that links are arranged as a stack allows the user to have many potential contexts just a click away. I've never felt that there wasn't enough space. I just collapsed the other links. This is consistent with the collapsible block philosophy that Roam and Workflowy both use.

### Dislikes
- The blue headers (big and medium) on blue background is not ideal for visual contrast.
- The light gray "Linked reference" and "Unlinked references" are nearly imperceivable because of lack of contrast and small font-size.
- Sections can be toggled open and close with `+` and `-` **or** a caret.
- The number you can click to expand references is consistent with Roam's block references, but it seems to be underemphasized for how important it is.
- When you do click on the number, a  **Mentions of: X** is added to the top of the stack. This feels a little awkward, as the font is small and black, and it seems as if it should be logically grouped under the large blue header, not added to the top of the stack.

# Demo
![right-sidebar](https://user-images.githubusercontent.com/8952138/81120099-011f0600-8efa-11ea-9f99-a13809a2e9d4.gif)
</details>

**Comment by anshbansal** [comment]
Here is another implementation that I think can be interesting https://notes.andymatuschak.org/Peripheral_vision

**Comment by Bardia95** [comment]
Working on it!

**Comment by tangjeff0** [comment]
@Bardia95 please wait a few days. The designers are thinking of ways to re-design this interaction from the ground up. I will rewrite this issue today. 🙂

**Comment by Bardia95** [comment]
Ok @tangjeff0, who are the designers? I want to work w them on this

**Comment by tomisme** [comment]
> Ok @tangjeff0, who are the designers? I want to work w them on this

Jump into the #design channel on discord: https://discord.com/channels/708122962422792194/708124073544122399

**Comment by jacobmorse** [comment]
I am currently organizing the UI exploration file and will start sharing some concepts for this story very soon.

**Comment by PiotrSss** [comment]
"Andy Matuschak mode" works in Obsidian https://forum.obsidian.md/t/andy-matuschak-mode-v2/170 and in my experience it's much, much, much more flexible than Roam's sidebar. Please consider creating something like that instead of copying 1:1 Roam UI.

Live preview is another great idea, implemented now in Roam-toolkit browser extension https://twitter.com/ViktorTabori/status/1261267174741741568

**Comment by jacobmorse** [comment]
@PiotrSss We are in complete agreement. I am _extremely_ resistant to copying Roam. I'm much more interested in understanding what people love to do in Roam, what they desire most from a "connected thinking app," where current tools (including Roam) fail them, and synthesizing that into significantly improved features and UX. The sidebar is a perfect example of a feature we are discussing a **lot**. First of all, it isn't complete in Roam. Secondly, we all know it can be extremely powerful. We have quite a few ideas in the works among the design team.

**Comment by marketmann** [comment]
Hey @jacobmorse, 
> **I'm much more interested in understanding what people love to do in Roam**, what they desire most from a "networked thinking app," where current tools (including Roam) fail them, and synthesizing that into significantly improved features and UX.

Me too.  Is there a specific place you're talking about all that fun stuff?

**Comment by tangjeff0** [comment]
Hi @marketmann, sorry for the late response. Jacob's agency just got billed a COVID tracking app, so he's not returning to an active role at least until that's in a good place. Feel free to DM me or @shanberg on Discord.
