### ISSUE TITLE
Application becomes unresponsive after entering a short query in Athena

### ISSUE THREAD

**Issue by alaq** [athensresearch/athens#269]
**Problem**

Entering a short query (one or two characters) in Athena will freeze the application. The only way out of it is to close the tab. You need to have data for this.

**Expected Behavior**

The application should remain responsive and show a list of results in Athena.

**Dependencies**

- Athens: latest master
- browser: Chromium, Firefox

**To Reproduce**

https://athensresearch.github.io/athens/ then load test data, input one or two characters in Athena. The application will freeze.

**Comment by jorda0mega** [comment]
the main issue is with the `get-root-parent-node` function in `db.cljs`. After loading the Test DB,  if you type `"a"` the `search-in-block-content` function will return 1780 records. Looping through all of the children blocks of 1780 records will freeze the application. A possible solution would be to limit the query results to 20 to begin with. The code is already limiting the search results to 20 in `athena.cljs`

```clojure
(defn get-root-parent-node
  [block]
  (loop [b block]
    (if (:node/title b)
      (assoc block :block/parent b)
      (recur (first (:block/_children b))))))
```

**Comment by itsrainingmani** [comment]
@jorda0mega I think datascript has a `:limit` option that should allow us to limit how many search queries are returned. I'm going to test that and see what the best option is.

**Comment by jorda0mega** [comment]
So I tried the :limit in datomic pull syntax but that's only for a many attribute. In this case I think we would need the cap the entire list of results rather than one of the attributes. Might be wrong though so let me know if it works

**Comment by itsrainingmani** [comment]
I also tried just putting a `(take 20)` inside the `search-in-block-content` which seems to fix this issue. There is still some latency though.

https://github.com/itsrainingmani/athens/blob/a0ac5c37b9c80f117c21cb422fe98674953fc4e3/src/cljs/athens/db.cljs#L305

**Comment by jorda0mega** [comment]
Nice. That's what I was thinking as well but I feel there has to be a way to do this at the query level

**Comment by itsrainingmani** [comment]
I looked at the datascript source and I can't find an option for that. So maybe not.

**Comment by tangjeff0** [comment]
@jorda0mega I don't believe there is! The datalog query is set-based, so if there was a native `limit` within the query, I think it would essentially be doing the same thing as `take` outside the query. Different from the typical mental model of SQL dbs!
