### ISSUE TITLE
Athena Result list does not scroll when navigating with arrow keys

### ISSUE THREAD

**Issue by itsrainingmani** [athensresearch/athens#271]
*If you aren't sure about your bug, you can always join our [Discord](https://discord.gg/HNmxvpm) and ask in #agora or #engineering!*

**Problem**

When using arrow keys to navigate up and down through the list of search results, the list does not automatically scroll as you move past the first few items. The user is unable to see which search result is currently selected.

**Expected Behavior**

Like Roam, when you select a search result is that is initially beyond the visible items, the search result list should scroll to bring the selection into view.

**To Reproduce**

https://athensresearch.github.io/athens/ then load test data, search for a term in Athena and use the arrow keys to go down the result list.

**Screenshots**

https://www.loom.com/share/90714b294cdb4c77a0d2f69d1fe56396

**Comment by tangjeff0** [comment]
Should list wrap around? i.e. if you press up at index 0 or press down at index N.

**Comment by itsrainingmani** [comment]
We're currently working on eliminating the flicker that happens in the current implementation. Idea is to use react refs to imperatively perform the scrolling.

**Comment by tangjeff0** [comment]
Haven't used react refs once yet. What's your use case?

**Comment by jorda0mega** [comment]
> Should list wrap around? i.e. if you press up at index 0 or press down at index N.

That's the current implementation in roam. Wrote up a quick implementation so that key up/down wrap around

```clojure
(= key KeyCodes.UP)
      (swap! state update :index #(dec (if (= 0 %) (count results) %)))

(= key KeyCodes.DOWN)
      (swap! state update :index #(inc (if (= (count results) %) 0 %)))
```

**Comment by itsrainingmani** [comment]
> > Should list wrap around? i.e. if you press up at index 0 or press down at index N.
> 
> That's the current implementation in roam. Wrote up some quick code so that key up/down wrap around
> 
> ```clojure
> (= key KeyCodes.UP)
>       (swap! state update :index #(dec (if (= 0 %) (count results) %)))
> 
> (= key KeyCodes.DOWN)
>       (swap! state update :index #(if (= (- (count results) 1) %) 0 (inc %)))
> ```

Thanks for the code @jorda0mega ! That was helpful 🙂

**Comment by nthd3gr33** [comment]
We have observed the flickering issue in other areas of the project, not just in Athena. 

So far we have observed it when:
- navigating the list of elements in Athena  
- navigating blocks on Daily Pages with the down arrow key  
- dropdown menu for inline search

We think that the flickering is because of the `selected` class changing on re-render, but we have not successfully proven this yet. At this point, we are thinking the flickering issue could be a rabbit hole and will likely make a separate issue.

**Comment by tangjeff0** [comment]
Can you post a demo of flickering?

**Comment by tangjeff0** [comment]
Nice job @jorda0mega. This is unsolicited, but another implementation of the same logic could be

```
(if (zero? %)
  (dec (count results))
  (dec %))

(if (= (inc %) (count results))
  0
  (inc %))
```

**Comment by itsrainingmani** [comment]
> Can you post a demo of flickering? @nthd3gr33 

@tangjeff0 this is an example from Athena - https://www.loom.com/share/09d3f7b3b6334f22b5d9cd4b8dd91ee3

**Comment by jorda0mega** [comment]
> Nice job @jorda0mega. This is unsolicited, but another implementation of the same logic could be
> 
> ```
> (if (zero? %)
>   (dec (count results))
>   (dec %))
> 
> (if (= (inc %) (count results))
>   0
>   (inc %))
> ```

That's way more readable. I'd go with that :) I've noticed the flickering as well. Along these lines, should the up/down modify the cursor position in the input box?

**Comment by nthd3gr33** [comment]
Thanks for posting a demo from Athena @itsrainingmani 

> Can you post a demo of flickering? @nthd3gr33  

@tangjeff0 Here is a demo from the Daily Pages:

https://www.loom.com/share/2813f14fe47d4b54ae6c42d96ae230ae

**Comment by itsrainingmani** [comment]
@jorda0mega Thanks for pointing out the cursor position thing. I fixed that with the latest commit.
