### ISSUE TITLE
Workspaces

### ISSUE THREAD

**Issue by txnka** [athensresearch/athens#281]
### Prototype
[Link to the Figma prototype](https://www.figma.com/proto/QR47RdiCVV4QdAPTAclBwy/Athens-Sidebar-Sandbox?node-id=55%3A20&viewport=-1493%2C-1905%2C0.5&scaling=contain)

### Feature Description
Workspaces in Athens could serve as a way to group related pages and blocks in order to facilitate long-form writing by being able to remix (edit, change, rearrange) content without having to worry about changing the original blocks. Therefore it would be important for blocks / pages moved into a workspace to be copied into the workspace (instead of embedding them), while keeping a reference to the original. This could also serve as a way of versioning and allow the export of e.g. a whole essay with citations.
Workspaces could also be extended by introducing „view modes“ - different visualizations of the workspace content e.g. a graph view of just the workspace contents (instead of a graph of the whole DB), an outline view, a versioning view, a relationship view (how blocks relate to each other), etc. The view modes could also change automatically based on zoom level.

### Tasks

- [ ] Refinement of the feature scope

**Comment by tangjeff0** [comment]
Closing, need to improve core product before we can get to this new feature
