### ISSUE TITLE
When does Athensresearch release ?

### ISSUE THREAD

**Issue by nhanvu327** [athensresearch/athens#283]
Hi, just curious if you guys still release this on 1 August ? I've seen that statement somewhere before but looks like it has been removed so just want to confirm because I am looking forward to it.

**Comment by prabhath6** [comment]
Self-hosted MVP will be available on August 1st.

**Comment by nhanvu327** [comment]
wow, can't wait, what features does the MVPhave ?

**Comment by tangjeff0** [comment]
Statement was not removed. Use discord for these kinds of questions.

**Comment by HaojiXu** [comment]
Also just FYI @nhanvu327, we've made quite a bit of progress recently and you can track our progress here: https://twitter.com/AthensResearch

You can also try the demo page in the README file, it pretty much contains everything we have so far excluding filesystem access (for local persisted data) and Roam import - they would be included in the August release.

If you want to get involved more in our community, check out the discord invite link also in the README file. The discord is not only a place to talk about Athens the app, but also about general tools for thought and much more!
