### ISSUE TITLE
Pages - Team Seneca

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#292]
#96 

- [x] deletion
- [ ] merging
- [ ] link filters

**Comment by nthd3gr33** [comment]
Can you try to assign yourselves @itsrainingmani @alaq?

**Comment by itsrainingmani** [comment]
Just did @nthd3gr33

**Comment by alaq** [comment]
For reference, for whoever picks this up later (us or someone else):

- The code we currently have lives [here](https://github.com/itsrainingmani/athens/tree/link-filters).
- We have made the popup show  when clicking on the filter icon next to linked references. See https://github.com/itsrainingmani/athens/commit/243060004f7611f183d5db9e17abcb68ea23084d
- We have positioned the popup correctly (stays put when scrolling for instance -- but still very rough). See https://github.com/itsrainingmani/athens/commit/7c27739bd738b51d17b53cd237c3cd4cc67b3e11
