### ISSUE TITLE
Slash commands menu selection moves off the visible area

### ISSUE THREAD

**Issue by jorda0mega** [athensresearch/athens#298]
*If you aren't sure about your bug, you can always join our [Discord](https://discord.gg/HNmxvpm) and ask in #agora or #engineering!*

**Problem**

When the slash command menu appears by typing / and you scroll up/down you can move off the visible area. The index does not wrap around the number of items.

**Expected Behavior**

When reaching the bottom or top of the options it should wrap around and begin on the opposite end. 

**Dependencies**

- Athens: commit 7e9e658b7ea2c2888c76e37a5f94099bf5ebdaf3
- browser: Brave v1.11.97
- JVM: 13
- node.js: 14.5.0

**To Reproduce**

Load up Athens > Load Test Data > type / in one of the blocks to get the slash command menu > press down or up arrow keys to scroll through the options (keep going until you are able to get to an option that's not visible in the area)

**Screenshots**

![CleanShot 2020-07-24 at 01 34 54](https://user-images.githubusercontent.com/484084/88363418-0009b200-cd4e-11ea-9fb1-1051f01f22e3.gif)

**Comment by nthd3gr33** [comment]
We can probably apply the same fix we made in #280 to this issue. 
cc @alaq @itsrainingmani

**Comment by jorda0mega** [comment]
@nthd3gr33 exactly! I was playing around with but couldn't figure out where :search/index is getting updated. Would love to get you guys' feedback on it.

**Comment by alaq** [comment]
@jorda0mega Hope you don't mind, I went ahead an opened #304 for this, since it's almost exactly the code we had in #280

**Comment by jorda0mega** [comment]
@alaq  no worries at all. I can now read your PR to understand. I'm curious, were you familiar with the code? I had the right idea of putting the logic in key-bindings.cljs but didn't realize the key-down event was back on the block element instead on the slash command menu. Is there a way to trace this behavior in cljs through the chrome inspector like one would do with js? Can it be done with the repl?

I'm having a hard time following the code when components render dynamically. I'm wondering if there are any tricks I can use that make this behavior easier to understand.

**Comment by alaq** [comment]
@jorda0mega I'm afraid I won't be of much help here, I have not been using any of the fancy clojure features. I have not even spent the time to get the REPL to work correctly (I know I am missing out), or even tried to use the devtools. We had done something almost identical for Athena in #280 so I merely looked for the key up/down events for the slash command and found them in `keybindings.cljs`. Then it was just adapting the Athena code to the slash commands.
