### ISSUE TITLE
Athena Regex issues

### ISSUE THREAD

**Issue by itsrainingmani** [athensresearch/athens#301]
Athena/Athens has some issues when you enter any unterminated regex special characters `[`, `(` into the text input.

**Problem**

The main issue is when you try to navigate to a page that has an unterminated `[`, `(` in the title. The entire page freezes and doesn't render anything.
Entering special characters like `[`, `(` in Athena and trying to create a new page also has some weird behavior. Depending on the combination of characters, Athena doesn't display the page creation button, or the page is created but with some characters missing.

**Expected Behavior**

@nthd3gr33 tested the behavior on Roam and there are no issues with navigating to pages with unterminated `[`, `(` characters in the title.
* Navigating to a page that has `[`, `(` in the title should not freeze the whole page.
* Entering these characters into Athena should not cause Athena to freeze and/or should create the page with all the input characters.

**Dependencies**

- Athens: Latest Master
- browser: Firefox, Edge, Chrome

**To Reproduce**

For Page Creation issue - 
1. Open Athena
2. Enter search text that has unterminated `[`, `(` characters. For example - `Athens [(`. And try to create the page

For Page Freezing issue - 
1. Load the Test Data
2. Open Athena
3. Search for "Athens" and click on the result "Athens [ATH" in the search results
4. Page should freeze

**Screenshots**

https://www.loom.com/share/725a748a7d90433dae55faa10b92af28

![image](https://user-images.githubusercontent.com/10191300/88372755-27677b80-cd5c-11ea-8c3c-cf0e3faa249d.png)

**Comment by itsrainingmani** [comment]
@tangjeff0 I have some code that fixes this issue by escaping the string that we pass to any `re-pattern` calls in `node_page.cljs` or Athena search.

https://github.com/itsrainingmani/athens/commit/37449a5b04078044157156f216d85605130ef7c9

Is this worth submitting a PR for?

**Comment by tangjeff0** [comment]
It sounds like a good bug fix so yes @itsrainingmani
