### ISSUE TITLE
blocks: block flickering issues

### ISSUE THREAD

**Issue by thesophiaxu** [athensresearch/athens#302]
*If you aren't sure about your bug, you can always join our [Discord](https://discord.gg/HNmxvpm) and ask in #agora or #engineering!*

**Problem**

- A Reddit user reported that when the user changes block content and then change block indentation, there will be a short time when the block is empty.
- If the changed block content contains links (for link detection) and the cursor is moved away from the block, modified content would not be visible for a short time.

**Expected Behavior**

Content display should be consistent without flickering.

**Dependencies**

[ Please specify your environment and software dependencies, with versions. ]

- Athens: latest master, my dev build
- browser: Chrome (macOS)
- JVM: java8u251
- node.js: v13.12.0

**To Reproduce**

See _problem_ section.

**Comment by HaojiXu** [comment]
self assigning because I might have a lead on this - will fix it tomorrow

**Comment by HaojiXu** [comment]
I dug this around and found that we might need some macro-level fix for the block editing ui to be more smooth for the user. My intuitive fix is to add a `:editing/string` (and possibly `:editing/cursor-pos` for butter-smooth experience) field to cache what the user has entered, but this is a global app state change.

Any ideas @tangjeff0 ?

**Comment by sid597** [comment]
Bug is resolved.
