### ISSUE TITLE
Implement "import JSON from Roam"

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#31]
Assigned to @jeroenvandijk 

This issue covers importing **only Roam**'s JSON export.

Requires generating `:block/uid`s for pages since Roam's export lacks them... 🤷‍♂️🧐

Also, there are some properties in the JSON that may need to be omitted otherwise the datascript transaction throws an exception. Consider using `clojure.spec`, `specter`, or something like that to ignore non-essential attributes for now.

- map JSON fields to attributes, using https://github.com/athensresearch/athens/blob/master/src/cljs/athens/db.cljs#L8-L25
- add to or refactor https://github.com/athensresearch/athens/blob/master/src/cljs/athens/db.cljs#L30-L39
- file upload should accept multiple file formats and shapes of data. Again, something like `clojure.spec` can be used to determine the shape of the data: https://github.com/athensresearch/athens/blob/master/src/cljs/athens/db.cljs#L57-L63
- Attribute reference: https://www.notion.so/athensresearch/Datascript-Attribute-Table-afd0e5c9556b404880a0b149f87e9d6d

**Comment by jeroenvandijk** [comment]
@tangjeff0 I did some exploratory work. I pretty printed the json dump and I did some analysis on the attributes https://gist.github.com/jeroenvandijk/6713bf0af4fe5bc82ebf4a261766537b#file-pretty_print_json_export-edn

I think there is more information in the dump than you thought? For instance, in many cases there is a `:block/uid`, but it's at not at the top level, only under children it seems. Also in the diagrams many things are actually uid (e.g. `from`, `to`, `id`, maybe more).

Might take some time to get this right. Maybe we can do a cross reference with your datom export to make sure we are not missing any data.

**Comment by tangjeff0** [comment]
Yeah, last I recall `:block/uid` was present for all child blocks, but not for some pages. I didn't dig into diagrams, but all of them use blocks under the hood. You can see how that would look in datoms [here](https://www.notion.so/athensresearch/Attribute-Table-afd0e5c9556b404880a0b149f87e9d6d?p=f4705c341930497da2e414f72c517868).

**Comment by jeroenvandijk** [comment]
Making some progress with Meander ([gist](https://gist.github.com/jeroenvandijk/62e3a52550f3aef5b69e4f0e91b73d18#file-meander_import-clj-L19-L82)) It's not there yet, it's still missing some mapping, but slowly getting there. I think/hope it's a matter of understanding Meander better. The expected result is an  self-explaining import script. I'm asking for help in the #meander slack channel

**Comment by jeroenvandijk** [comment]
Some more WIP and background here:

- https://clojurians-log.clojureverse.org/meander/2020-05-08
- https://clojurians-log.clojureverse.org/meander/2020-05-12

Transformation is more or less complete. Next step is getting it in the right shape to transact to Datascript

**Comment by palashkaria** [comment]
@jeroenvandijk @tangjeff0 I have been thinking of this for a while, but I have a couple of ideas here:

1. Instead of supporting roam JSON (which has incomplete info, as you mention, page UIDs are missing), why don't we just use the query method? 
    - The advantage: we get the whole data
    - I can see concerns with this method being hard to use, but we can easily build this into a browser extension, say [roam-toolkit](https://github.com/roam-unofficial/roam-toolkit),(or a tiny one of our own/a small script)


2. There are other ways to get data out - for eg by taking a dump of the local indexeddb - this might be a useful idea for exporting stuff from Athens itself
   -For example, the memex extension by worldbrain, they run a local server & save files to your hard drive - it's basically a dump of the db which works on import

    -  they use [worldbrain/storex](https://github.com/WorldBrain/storex) for this, which is a way to descrive schema which can talk across types of DBs/devices. For example, you can have the same db running on both browser's indexedDb (via Dexie) * SQLite in React-native ([sorex docs](https://worldbrain.github.io/storex-docs/#/guides/quickstart/)). They also have something called storex-sync in the works for cross device syncing of this data, offline (via a local server)

**Comment by tangjeff0** [comment]
@palashkaria I think `roam-toolkit` could be a great solution if we decide to go with `roamAlphaApi`. The only problem here is that this export is not perfect. If you look at the return value of `roamAlphaApi.q`, you can see we lose all the namespaces for attributes.

- This means we don't know if the attribute `"time"` maps to `:edit/time` or `:create/time`. 
- We don't know if `"email"` maps to `:create/email` or `:edit/email`.

On the plus, this export seems to export data structures well like the `refs` attribute, which is a set of 3 vectors.

There may be other export issues I'm not aware of. If we can find an interoperable example of each attribute [described in Notion](https://www.notion.so/athensresearch/Datascript-Attribute-Table-afd0e5c9556b404880a0b149f87e9d6d), I'm happy to use this method. I don't think `:x/email` or `:x/time` attributes are that important ultimately. I think `:block/uid`, `:node/title`, and `:block/string` are the most important.

---

Regarding your second point, I love worldbrain. How do we query and pull data from IndexedDB? If we can get it out in datom format, that'd be great!

**Comment by palashkaria** [comment]
@tangjeff0 to get around that, we can use `.pull`, maybe; Something like this:

`const data = window.roamAlphaAPI.q(`[:find ?e :where [?e ?a ?v]]`).map(dbId => window.roamAlphaAPI.pull('[*]', dbId[0]))`;

Although I'm think it might be possible to do it in one query too; not quite sure how.

**Comment by tangjeff0** [comment]
Wow, great idea using pull syntax. This query works perfectly! @palashkaria 

```
roamAlphaAPI.q(`[:find [?e ...] :where [?e ?a ?v]]`).map(e => roamAlphaAPI.pull('[*]', e))
```

Want to begin making the `roam-toolkit` plugin?

FYI the way to do it one query is:
```
roamAlphaAPI.q(`
[:find [(pull ?e [*] ) ...]
 :where [?e ?a ?v]]`)
```

But this again loses the namespace attributes 😢  but we can still use your JS `map` idea

How about `IndexedDB`? What can we pull from there?

**Comment by palashkaria** [comment]
@tangjeff0 is this all the data?


```

window.roamAlphaAPI.q(`[:find ?e ?a ?v :where [?e ?a ?v]]`).map(x => window.roamAlphaAPI.pull('[*]', x[0]))


``

**Comment by palashkaria** [comment]
@tangjeff0 IndexDb is pretty involved, & can look very weird with roam internals exposed
You can go to your Application tab in inspect > storage & look at dbs there. What these are useful for is to make a backup of your whole roam db etc

an example of db data

```


tx: "[["~:db.fn/retractAttribute",["~:block/uid","jjXiTSxJe"],"~:block/refs"],["^ ","^1","jjXiTSxJe","^2",[["^ ","^1","MfxMc1zIG"]]]]"


tx: "[["~:db/add","uuid4236c39a-e712-4fc7-bac0-9ecb03ec833e","~:block/uid","Vrv2DiaVE"],["^ ","^1","jjXiTSxJe","~:block/children",[["^ ","~:block/string","","~:create/email","example@gmail.com","~:create/time",1593104696364,"^1","Vrv2DiaVE","~:block/open",true,"~:edit/time",1593104696364,"~:db/id","uuid4236c39a-e712-4fc7-bac0-9ecb03ec833e","~:edit/email","example@gmail.com","~:block/order",1]]]]"

--

```

**Comment by palashkaria** [comment]
Also, please test out the query with more kinds of things - I am unable to verify if everything in notion works properly with this..

I'll also figure out the roam-toolkit if this pans out.

**Comment by tangjeff0** [comment]
Please provide the JS necessary to access the IndexedDB data. We can compare `window.roamAlphaApi` with the IndexedDB data.

What you showed me are not Roam internals. In fact, I believe it is [datascript-transit](https://github.com/tonsky/datascript-transit/blob/master/src/datascript/transit.clj). Athens uses the same thing but with localStorage right now:

![Screen Shot 2020-07-02 at 11 36 55 AM](https://user-images.githubusercontent.com/8952138/86379058-58222c80-bc58-11ea-97ff-91442df691f9.png)
 
We can compare data from these two sources. If they are the same, then it is a perfect export. @palashkaria

**Comment by tangjeff0** [comment]
(But I’m pretty confident that `q-map-pull` works as expected)

**Comment by palashkaria** [comment]
@tangjeff0 ah yes, so that's all there is but no direct schema/datom exports. We can export these transactions using `[Dexie](https://github.com/dfahlander/Dexie.js/)`, as blobs, somewhat like this:

```
import {exportDB} from 'dexie-export-import';
import Dexie from 'dexie';
import { saveAs } from 'file-saver';


Dexie.getDatabaseNames(dbNames => {
	dbNames.forEach((dbName) => {
		const db = new Dexie(dbName);
		db.open().then(() => {
			exportDB(db).then(blob => {
				saveAs(blob, `${dbName}.json`);
			})
		})
	})
})

```

Note: This will download a lot of files - your browser will probably warn you

 - Also, a side note localstorage is synchronous, so it would be slow, indexedDb might be be a better idea for athens eventually (I suggested using it with Dexie.js)

https://web.dev/storage-for-the-web/#other

**Comment by palashkaria** [comment]
@tangjeff0 all considered, let's go ahead with `q-map-pull` itself

**Comment by tangjeff0** [comment]
@palashkaria The datalog semantics are correct. The issue is that namespaced keywords are mostly a Clojure (`edn`) construct that requires additional serialization to export to JSON.

There was recently a good post on [namespaced keywords](https://vvvvalvalval.github.io/posts/clojure-key-namespacing-convention-considered-harmful.html).

**Comment by tangjeff0** [comment]
@palashkaria implemented full import. Feel free to start on the roam-toolkit plugin!

**Comment by sagarjauhari** [comment]
Trying to figure out the status of this feature - is the roam import supported atm?

**Comment by tangjeff0** [comment]
Not supported atm @sagarjauhari , waiting for performance improvements before importing this. Many people have large Roam dbs.

**Comment by Mayeu** [comment]
I don't know if you saw, but there is now a "[loseless edn export](https://roamresearch.com/#/app/help/page/TRyweCpsC)" in Roam.

**Comment by tangjeff0** [comment]
Yeah, that makes it even easier @Mayeu. Thanks!

**Comment by TDHTTTT** [comment]
Hi I am wondering if this is currently being worked on. If not, how can I help? Thanks!

**Comment by tomisme** [comment]
@TDHTTTT I think the latest work is at #561
