### ISSUE TITLE
Outline a governance document

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#32]
According to [OSS Watch](http://oss-watch.ac.uk/resources/governancemodels), "It is never too soon to define a suitable governance model."

Things this governance document should include:

- Athens's objectives
- the software license (EPL right now) and their implications
- roles and responsibilities, e.g.
  - user
  - contributor
  - maintainer
  - committer
- decision-making process

### Model
OSS Watch depicts projects in two dimensions:
- X: [BD](http://oss-watch.ac.uk/resources/benevolentdictatorgovernancemodel) to [Meritocratic](http://oss-watch.ac.uk/resources/meritocraticgovernancemodel)
- Y: [Cathedral to Bazaar](http://catb.org/~esr/writings/cathedral-bazaar/cathedral-bazaar/index.html)

![image](https://user-images.githubusercontent.com/8952138/81291466-cc18cd80-9037-11ea-88c7-1407517a2e83.png)

What matters most to me beyond the categories and labels are **transparency, inclusivity, and collective intelligence**. I like to think we've done a good job of this so far.

**Comment by tangjeff0** [comment]
Closely related to governance is the Code of Conduct. Right now we are using the generic [Contributor Covenant](https://www.contributor-covenant.org/). Should we consider creating a more bespoke CoC as [Future of Coding](https://github.com/futureofcoding/code-of-conduct) has done?

**Comment by FalconBFR** [comment]
I think he means white paper. I am happy to help create that

**Comment by tangjeff0** [comment]
Reminder to include key Athens values in either GOVERNANCE or in the CoC.

**Comment by tangjeff0** [comment]
closed by #82
