### ISSUE TITLE
fix(selection): Show proper selection opacity for nested blocks #241

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#326]
**Feature Issue**: #241 

**Screenshot**

![Screen Shot 2020-08-11 at 3 24 05 PM](https://user-images.githubusercontent.com/8952138/89940014-dfaf7380-dbe6-11ea-9243-e1b5b5e5dd8d.png)

**Steps**

- use [`goog.dom.findCommonAncestor`](https://github.com/google/closure-library/blob/master/closure/goog/dom/dom.js#L1693)
- update `:selected/items` in re-frame db

**Comment by hmaurer** [comment]
@tangjeff0 i am interested in taking up this one!

**Comment by tangjeff0** [comment]
Go for it @hmaurer.
