### ISSUE TITLE
feat(slash): Typeahead filter for slash commands

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#327]
**feature issue**: #59

**demo**: use Notion or Roam. Different behavior

**steps**: 

- store query, probably in `:search/query` of block atom
- filter `slash-options` in `slash-menu-el`

**Comment by bonobo-d** [comment]
@tangjeff0 of line to give this one a shot.

**Comment by tangjeff0** [comment]
Go for it @bonobo-d ! Assigned.
