### ISSUE TITLE
fix(listeners): close dropdowns when user clicks outside of them

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#328]
**parent issues**:  #59 #97 

**demo**: in Roam, slash menu and inline search have slightly different close conditions.

- Slash menu closes when click anywhere outside of block. 
- Inline search closes when click outside of `[[_]]`, where `_` is your caret

**steps**: 

- create a `MOUSEDOWN` listener in `listeners`
- if a close condition is met, dispatch an event
- in `blocks`, if that event is dispatched, reset `search/type` to `nil`. this should close either dropdown

**Comment by alaq** [comment]
I'm going to take a look at this!

**Comment by tangjeff0** [comment]
Great! If there is a way to do this locally, that doesn't use global listeners, that would be ideal. I think `refs` let you do this but not sure.

All the dropdowns where this would apply:

- `context-menu` when clicking on bullets
- page menu
- inline search
- slash command menu
- though not a dropdown, Athena could use this too
