### ISSUE TITLE
Resolve linter warnings

### ISSUE THREAD

**Issue by jeroenvandijk** [athensresearch/athens#39]
[clj-kondo](https://github.com/borkdude/clj-kondo) is helping us to keep code quality high. Right now, there are still many warnings. Let's fix this. Current output can be viewed [here](https://github.com/athensresearch/athens/runs/656191957#step:4:1)

If everything is resolved, the message here will disappear:
https://github.com/athensresearch/athens/runs/656191957#step:4:46

After resolving this, we can configure the linter to fail the build.

**Comment by jeroenvandijk** [comment]
closed by #42

**Comment by borkdude** [comment]
I don't think it makes sense to just copy clj-kondo's own linting config to this project as those settings mostly apply to clj-kondo's own sources :).

**Comment by jeroenvandijk** [comment]
Hi @borkdude I think you are right :) It was the first project I could come up with 🤭We're still learning here. Feel free to educate us 😎

**Comment by borkdude** [comment]
You can just start with an empty configuration. If linting issues arise that you cannot solve yourself using https://github.com/borkdude/clj-kondo/blob/master/doc/config.md then feel free to reach out in the clj-kondo channel on Clojurians Slack.

**Comment by borkdude** [comment]
@jeroenvandijk PR here: https://github.com/athensresearch/athens/pull/58
