### ISSUE TITLE
Improve Contributor Experience

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#4]
[CONTRIBUTING.md](https://github.com/athensresearch/athens/blob/master/CONTRIBUTING.md) lacks sufficient guidelines. Areas to be improved:

- [x] Clojure styleguide
- [x] dev environment setup instructions
- [ ] Git(hub) workflow: how to write issue/commits, how to merge PRs, purpose of labels. See [bitcoin](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) and [status.im](https://status.im/technical/contributor_workflow.html)
- [ ] add a section on governance ([meritocratic](http://oss-watch.ac.uk/resources/meritocraticgovernancemodel), [BD](http://oss-watch.ac.uk/resources/benevolentdictatorgovernancemodel)), particularly on roles/responsibilites and how decisions are made

**Comment by FalconBFR** [comment]
@tangjeff0 Any chance for creating a documentation for Athens? I am happy to help.

**Comment by tangjeff0** [comment]
Splitting this issue:
- documentation #24 
- governance #32 
- git workflow #33

**Comment by notflip** [comment]
Is there another step that has to be taken after running
```
docker build -t athens .
docker run -it -p 3000:3000 -p 8777:8777 -p 9630:9630 athens
```

When I browse to localhost:3000 in my browser I only see a blank screen. thank you
