### ISSUE TITLE
Parse and format markdown-ish syntax

### ISSUE THREAD

**Issue by teodorlu** [athensresearch/athens#44]
Creating an issue for how to work with parsing the markup: how to turn plaintext like `I __very__ much like [[Athens Research]]` into a semantic structure that we can understand.

### Context & prior work

- Our very own [parser.cljs][our-parser] seems to be a bit of a work in progress
- [static-roam][static-roam] relies on serial regex replacement, and does [not go through an AST][static-roam-parser]

[our-parser]: https://github.com/athensresearch/athens/blob/76d0881efd245bceef324bbee90c81f7bc6e78d0/src/cljs/athens/parser.cljs
[static-roam]: https://github.com/TomLisankie/static-roam
[static-roam-parser]: https://github.com/TomLisankie/static-roam/blob/master/src/static_roam/core.clj

### Ideas

I think we'll be able to find an elegant solution to this. Instaparse is powerful. I don't think we should try to "hack some regexes", as that will cause us problems with recursion.

Design proposal:

- Define our AST structure with Clojure Spec. That way, we get validation & generators
- Define symmetric functions so that `(= source (-> source serialize deserialize))`
- Then we should be able to generate ASTs from [Spec generators][1], run them through a serialize & deserialize sequence, and check that they stay the same.

[1]: https://clojure.org/guides/spec#_generators

Hoping that we can reflect the same structure in our `Instaparse` parser and in our specs.

Thoughts?

### Challenges

- How do we represent incomplete ASTS? We need to allow for opening and not closing brackets. Or do we? How do we put `I like [[Athens Research` (missing `]]`) in an AST?

**Comment by teodorlu** [comment]
I'm currently playing around this this: https://github.com/teodorlu/athens/tree/parser-work/src/cljc/athens

**Comment by jeroenvandijk** [comment]
I've commented per sub topic:

### Parsing
Instaparse is a way better option than regexp. It takes a bit to get used to, but eventually combining regexp's will just become a terrible fragile mess. So +1 on that.

### Incomplete AST
What options do we have? In the backend I can imagine we would treat the incomplete AST just normal next. On the front end we might have a special parser that has spelling-checker like behaviour, saying this like "you might want to fix this". We could also annotate (potentially) incomplete ASTs in the database I guess. This would allow one to fix incorrect AST's every now and then and improving the whole database.

### Transformation
Like you said, Instaparse still needs a post-processing step to put it in the right data structure. I've used `clojure.spec` for this in the past and it can work, but it also a bit tricky. I wouldn't say it's ideal. 

For the json import (#31) I was already thinking of experimenting with https://github.com/noprompt/meander to support the transformation from nested maps to datoms. I still need to validate this approach, but I can imagine it can be useful for transforming the ASTs as well. Either way `clojure.spec` should definitely be used to validate the shape of the end result. In the past I've worked with different layers of specs, like compiled form and dsl form. It doesn't have to be one spec layer that does everything.

**Comment by jeroenvandijk** [comment]
In addition to my comment about Meander, I just found this demo of an implementation of a hiccup parser [here](https://github.com/noprompt/meander/blob/epsilon/examples/hiccup.clj#L40). Pretty impressive

**Comment by teodorlu** [comment]
Generally agree with all your points. Interesting application of incomplete AST to provide user error messages.

**Comment by teodorlu** [comment]
> Either way clojure.spec should definitely be used to validate the shape of the end result. In the past I've worked with different layers of specs, like compiled form and dsl form. It doesn't have to be one spec layer that does everything.

Interesting. Gave me some ideas about incomplete ASTs:

- Base spec for valid ASTs or strings
- "Extended frontend spec" that is `(s/or :valid-ast ::valid-ast :ast-with-spell-check-suggest ::ast-with-spell-check-suggest)` (TODO fix names)

**Comment by tomisme** [comment]
https://hazel.org/ are doing some interesting work on running/analyzing incomplete programs using 'holes', could be a (longer term) direction to go in

**Comment by roryokane** [comment]
In the current implementation of the parser, I’ve handled incomplete syntax not with a special “incomplete” type of AST, but by interpreting the syntax as valid plaintext. This is the same way Markdown (at least [CommonMark](https://spec.commonmark.org/dingus/)) handles syntax errors.

I can explain how it works with a simplified version of the parser:

~~~
block = ( block-link / any-char )*
block-link = <'[['> any-chars <']]'>
~~~

Within the `*` repetition, `block` uses ordered alternation `/` to attempt to match the following characters to a `block-link` – `[[` and `]]` with character between them. If `block-link` doesn’t match, the parser consumes one more character with `any-char` and repeats.

That way, a string like `[[foo]` is ultimately not parsed as a special unterminated link, which I imagine might look like this:

~~~clj
[:block [:error-unterminated [:block-link "foo]"]]]
~~~

Rather, it’s interpreted as the literal text “[[foo]”, like this:

~~~clj
[:block "[[foo]"]
~~~

Accepting the syntax as plain text is much easier to implement than trying to detect and correct errors. Accepting the syntax as plain text also ensures that the author’s punctuation will never be hidden by being misinterpreted as incomplete syntax. The downside is that this parser can’t be used to provide error messages in the case that the user truly wanted to use the link syntax.
