### ISSUE TITLE
fix(ui): Blank line ends up inline with next block/subblock

### ISSUE THREAD

**Issue by seltzered** [athensresearch/athens#447]
**Problem**

For a given block, when creating a second blank line it will appears inline with a block or sub-block below it until you write a non-whitespace character.
(this also occurs when having a null page title)

**Expected Behavior**

A new blank line should create a new line / visual spacing for it.

**Dependencies**

- Athens: 1.0.0-beta15
- browser: macOS electron build
- JVM:
- node.js: 

**To Reproduce**

shift+enter on a block to create a new line, particularly one where you have some content underneath. Before typing on the second line observe that it's inline until you write text.

**Screenshots**

![2020-10 athens hidden newline](https://user-images.githubusercontent.com/297435/96401875-69e8fa80-1189-11eb-8ea5-4a49c5b04a9d.gif)

**Comment by tangjeff0** [comment]
https://www.loom.com/share/124aff147a7649b68e3b3779e66ecbbb
