### ISSUE TITLE
Error in re-find query for production builds

### ISSUE THREAD

**Issue by jeroenvandijk** [athensresearch/athens#45]
**version**

all productions builds e.g. 76d0881 ([artifact here](https://github.com/athensresearch/athens/runs/657211506))

**platform**

Production build, Chrome 81.0.4044.138

**problem**

Page doesn't load

Under water:

<img width="664" alt="DevTools_-_file____Users_jeroen_Downloads_athens-app-76d0881_index_html" src="https://user-images.githubusercontent.com/27645/81468891-7a607680-91e2-11ea-8de9-b26871c4a7cc.png">

For some reason the `?s` [here](https://github.com/athensresearch/athens/blob/76d0881efd245bceef324bbee90c81f7bc6e78d0/src/cljs/athens/subs.cljs#L41) in this query is not (always) a string. In dev this doesn't seem to matter or isn't the case 

**repro**

Click on one of the page links or go to `index.html#/page/04-02-2020`

**expected behavior**

Display the page (like in dev)

**Comment by tomisme** [comment]
Changing to `{:optimizations :simple}` lets the app compile. It looks like we're including devcards and some shadow-cljs namespaces in our prod build, I think one of them is causing the issues with `:advanced` optimizations.

**Comment by tangjeff0** [comment]
Good find @tomisme. I tried doing this [here](https://github.com/athensresearch/athens/compare/master...tangjeff0:closure-compiler-simple-optimization) but seem to get some WebSocket error. This screenshot is from `cards.html` but I get the same from `index.html`. Probably lots of shadow-cljs stuff I don't understand.

![Screen Shot 2020-07-05 at 1 38 35 PM](https://user-images.githubusercontent.com/8952138/86538583-d5ea7000-bec4-11ea-9248-89b0d815a925.png)
