### ISSUE TITLE
fix(ui): too tall and too wide when opened near right side of block

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#459]
**slash commands**
![image](https://user-images.githubusercontent.com/8952138/97070185-41973c80-158b-11eb-83de-470e6a6fa058.png)

**inline search**
![image](https://user-images.githubusercontent.com/8952138/97070212-73100800-158b-11eb-93cb-d6eeb29c0513.png)

---

**should be**
![image](https://user-images.githubusercontent.com/8952138/97070707-58d82900-158f-11eb-9a82-378d7769391e.png)

**Comment by shanberg** [comment]
Probably time to look into a React portal solution for these types of popups.
