### ISSUE TITLE
Athens freezes, but doesn't relaunch?

### ISSUE THREAD

**Issue by seltzered** [athensresearch/athens#463]
*If you aren't sure about your bug, you can always join our [Discord](https://discord.gg/HNmxvpm) and ask in #agora or #engineering!*

**Problem**

Cursor/app froze while writing. Doesn't seem to get marked as 'not responding', and was still able to quit the app via menu (athens>Quit) (i.e. force quit wasn't needed).

**Expected Behavior**

App should ideally not freeze, or restart if freezing happens.

**Dependencies**

[ Please specify your environment and software dependencies, with versions. ]

- Athens: 1.0.0-beta19
- OS: macOS 10.15.7

**To Reproduce**

Not sure. I was just starting a new page and typing around, playing with keyboard cursor arrows (will file another bug related to that)

**Screenshots**
Not sure how to debug this, noticed in console.app it was marked as appShouldBeRelaunched, but didn't happen.  
![Screen Shot 2020-10-26 at 10 51 44 PM](https://user-images.githubusercontent.com/297435/97263231-bd89c280-17df-11eb-9dd3-7fc9a1ee02a6.png)

**Comment by tangjeff0** [comment]
I remember this might've happened to me on an auto-update. Did this happen shortly after launching Athens? Your bug reports have been awesome btw :) @seltzered

**Comment by seltzered** [comment]
Possibly, it might have happened a bit after the pop-up to perform an
update occurred or just after updating.
