### ISSUE TITLE
Version management

### ISSUE THREAD

**Issue by jtrakk** [athensresearch/athens#479]
Ideally the full edit history tree would be preserved, like a git revision tree, so I can undo a edit and replace it with another edit, and then compare the two branches. I want to visualize the whole tree. See [tools for visualizing history](https://livablesoftware.com/tools-to-visualize-the-history-of-a-git-repository/). 

That way, no matter what undo/redo operations I apply, I can _always_ understand where I am in the history and how to move to get back to where I was.

---
A related issue on Roam: https://github.com/Roam-Research/issues/issues/64

**Comment by tangjeff0** [comment]
@jtrakk This will be possible when we migrate to a database with history, such as Datomic or Datahike. Versioning of individual blocks would come out of the box (easy). Not sure how visualization is implemented but can learn from [Emacs](https://www.emacswiki.org/emacs/UndoTree) and [Vim](https://github.com/mbbill/undotree). Closing for now until we can action this!

**Comment by jtrakk** [comment]
FWIW, versioning is doable with postgres too. For example, the [Periods](https://github.com/xocolatl/periods) extension provides `SYSTEM VERSIONING` functionality.

**Comment by LoveIsGrief** [comment]
Just FYI fluree has a [`/history`](https://developers.flur.ee/docs/overview/query/history_query/) endpoint. It's also browsable in the [fluree web UI](https://youtu.be/OXY2dJnMzzE?t=116)
