### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by anonieee** [athensresearch/athens#49]
**Is your feature request related to a problem? Please describe.**
This might be a bit too early in the project, but are there plans to make this more performance-friendly? Right now self-hosting takes up more than 500 MB of RAM which is a bit much for someone that don't have the best spec like me.

**Describe the solution you'd like**
I'm not sure what the solution would be, but certain Electron web apps I've tried can be (relatively) lightweight, so maybe it's possible to make this into one?

**Comment by tangjeff0** [comment]
A little early, for future questions like this please feel free to send to our #engineering channel :)
