### ISSUE TITLE
fix: the arrow down key is not working when the cursor is on the page title.

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#501]
*If you aren't sure about your bug, you can always join our [Discord](https://discord.gg/HNmxvpm) and ask in #agora or #engineering!*

**Problem**

The arrow down key is not working when the cursor is on the node/block page title.

**Expected Behavior**

Given the cursor is on the node/block page title, when the user presses the arrow down key, then the cursor should go to the first child block.

**Dependencies**

- Athens: version=1.0.0-beta.21
- browser: electron
- JVM: openjdk 11.0.9.1 2020-11-04
- node.js: v14.4.0

**To Reproduce**

1. Click on the node block / page title
2. Press the arrow down key

**Screenshots**

![title](https://user-images.githubusercontent.com/8164667/99862611-6526c480-2bd5-11eb-9c20-e6e29aca65b6.gif)

**Comment by tangjeff0** [comment]
@juniusfree also make sure this works for block pages too!

**Comment by juniusfree** [comment]
@tangjeff0 noted
