### ISSUE TITLE
Is AthensResearch able to refer to other block ?

### ISSUE THREAD

**Issue by nhanvu327** [athensresearch/athens#503]
The question is self-explanatory. I am RemNote users atm but moving away from it. I would like to ask if AthensResearch have plans to support block referencing, not pages but blocks. And not sure if you guys will support Flashcard features?

**Comment by seelaman** [comment]
Yes to block references, I can't comment on plans for flashcards

![block reference](https://user-images.githubusercontent.com/8989886/101273584-ae395580-374b-11eb-9c29-a45403cfc43f.gif)

**Comment by tangjeff0** [comment]
Yes @nhanvu327, I'm sure flashcards can be supported as a plugin, just not sure on the priority.

Thanks @seelaman
