### ISSUE TITLE
Bug: Desktop app freeze on search

### ISSUE THREAD

**Issue by bboymatt** [athensresearch/athens#511]
**Problem**

Athens desktop app stops working when trying to type in the search bar.

**Expected Behavior**

The app should show my input in the search bar, and allow me to open existing pages or create new ones.

**Dependencies**

MacOS 10.15.17

- Athens: commit 6ce3da906692445b3eb9c8a169475f458ab7f3af
- browser: electron app
- JVM: openjdk version "11.0.9.1" 2020-11-04
- node.js: v12.18.3

**To Reproduce**

I thing this is related to an issue with the DB file since I cannot reproduce it on a new DB.

![Kapture 2020-12-04 at 20 20 24](https://user-images.githubusercontent.com/13032984/101207136-74475100-3670-11eb-865b-c346286ae732.gif)

**Comment by tangjeff0** [comment]
Yeah probably has to do with a corrupted DB. 1) Should somehow prevent DB from getting corrupted, 2) should have safeguards on search that catch errors even if DB gets to an unexpected state (which is pretty likely because of how flexible this DB is)

**Comment by tangjeff0** [comment]
Not sure what the problem in particular is in this case, but created a guard that alerts user if a transaction would lead to an error in #524. Closing now.
