### ISSUE TITLE
Bug: App crashes when deleting full page content

### ISSUE THREAD

**Issue by bboymatt** [athensresearch/athens#512]
**Problem**

The app desktop app crashes when selecting and deleting the full content of a page.

**Expected Behavior**

The content should be deleted, the page should become empty and the app should continue functioning normally.

**Dependencies**

MacOS 10.15.17

Athens: commit 6ce3da9
browser: electron app
JVM: openjdk version "11.0.9.1" 2020-11-04
node.js: v12.18.3

**To Reproduce**

Go to page with content. Select all (CMD+A) then delete (⌫).

**Screenshots**

![Kapture 2020-12-04 at 20 36 09](https://user-images.githubusercontent.com/13032984/101207576-1a935680-3671-11eb-9281-ed51e95b3d8c.gif)

**Comment by iluu** [comment]
It's actually easier to reproduce than that.
In order to make it crash all you have to do is just delete the first item below title. See attached video

https://user-images.githubusercontent.com/666061/103315377-b07a9100-4a25-11eb-9d71-14cb9c245677.mov

**Comment by tangjeff0** [comment]
Thank you @bboymatt for the report and @iluu for the helpful repro. Closed by #523
