### ISSUE TITLE
opening a second instance of the v1.0.0-beta.22 executable might delete the original database

### ISSUE THREAD

**Issue by rpacz** [athensresearch/athens#518]
**Problem**
opening a second instance of the v1.0.0-beta.22 executable does not open the main database (index.transit) but starts one from scratch.  If the first instance is closed, and the second instance keeps getting edited, the original main database is deleted

**Expected Behavior**

The second instance should either edit the original database or be prevented from opening altogether.

**Dependencies**

Windows 10 

- Athens: v1.0.0-beta.22
- browser: firefox
- JVM: java version "1.8.0_271"

**Comment by sid597** [comment]
way ahead of that version
