### ISSUE TITLE
Allow either user-deletion or hiding of Daily Note entries

### ISSUE THREAD

**Issue by seltzered** [athensresearch/athens#528]
As of Athens 1.0.0-beta.25, Daily Note entries get automatically created when scrolling, which is fine, but if they get accidentally created there's no way to delete them. 

Propose for either:

- Allow user to delete Daily Note entries. This is probably easier to implement.

- Hiding null Daily Note entries from the 'All Pages' list and Search. 
I haven't dived into the codebase yet but this *might* make more sense from a backend perspective / consideration of interactions. Particularly when a user is trying to scroll through multiple prior days to intentionally create a Daily Note entry that's from several days ago. In that case with the first option, the user then has to manually delete the other Daily Note entries created.

**Comment by itsrainingmani** [comment]
Allowing users to delete a Daily Note would be pretty easy since the `Delete Page` button is just hidden behind a condition check.

Regarding #2, would it make sense to have a checkbox in the Settings page to the effect of - "Hide empty Daily Notes from All Pages"?

**Comment by seltzered** [comment]
Regarding hiding daily notes from all pages: Yes, a setting might be good enough. Worth noting though that I feel less bothered by this issue less now (on beta37) compared to when I was using beta25 now that the sort order is arranged by number of link references.
