### ISSUE TITLE
macOS - Athens window never re-opens after closing it.

### ISSUE THREAD

**Issue by seltzered** [athensresearch/athens#530]
*If you aren't sure about your bug, you can always join our [Discord](https://discord.gg/HNmxvpm) and ask in #agora or #engineering!*

**Problem**

When using Athens on macOS, the window doesn't re-open after closing it. The current workaround is to Quit Athens and re-launch it. This issue has constantly led me to think Athens went off in the weeds and crashed when I'm trying to use it immediately for something, and led me to not use it as much the past month or two.

**Expected Behavior**
Athens should open the main window when invoked, particularly after it was closed earlier

**Dependencies**

[ Please specify your environment and software dependencies, with versions. ]

- Athens: 1.0.0-beta25 standalone electron build
- browser: 
- JVM:
- node.js: 
- OS: macOS Big Sur 11.0.1

**To Reproduce**

On MacOS:
1) Open Athens.
2) Close window (cmd+W) (athens process still running)
3) Try to open Athens again by clicking the dock icon or invoking via launcher.
4) Observe window won't open again unless user 'Quits' Athens.

**Comment by tangjeff0** [comment]
> When using Athens on macOS, the window doesn't re-open after closing it.

Could you please elaborate or show a demo of this? Not sure I understand.

**Comment by seltzered** [comment]
Yeah, it's specific to how on macOS closing a window (via CMD+W, or clicking the red button) closes the window BUT NOT the Athens process. This is fine, but when trying to open athens again the window doesn't come back. 

In certain applications this might be okay (but isn't common), but only when there is a user path in the menu bar to create a window. Here's a video. Again, in this example I closed the window with cmd+W, but the same problem happens if clicking the  red 'close window' button.

https://user-images.githubusercontent.com/297435/103445610-6bc04700-4c2b-11eb-92fe-b5245ad7d7cf.mov

**Comment by tangjeff0** [comment]
@seltzered I understand the issue now. This should be a simple fix. Thank you!

**Comment by tangjeff0** [comment]
closed by #571
