### ISSUE TITLE
Window Title doesn't update to reflect page when using Back/Forward Navigation Buttons

### ISSUE THREAD

**Issue by seltzered** [athensresearch/athens#531]
*If you aren't sure about your bug, you can always join our [Discord](https://discord.gg/HNmxvpm) and ask in #agora or #engineering!*

**Problem**

When using the Back/Forward buttons to navigate in Athens, Window Title does not update to reflect the page currently being viewed.  

**Expected Behavior**

Expect Window Title to always reflect page currently being viewed.

**Dependencies**

[ Please specify your environment and software dependencies, with versions. ]

- Athens: 1.0.0-beta25
- browser: 
- JVM:
- node.js: 
- MacOS Big Sur 11.0.0.1

**To Reproduce**

1) Try going to at least two different pages by clicking or searching.
2) Try going back and forth between them. Observe window title does not change.

**Screenshots**

https://user-images.githubusercontent.com/297435/103445666-251f1c80-4c2c-11eb-9d4f-c6cf852501db.mov

**Comment by sid597** [comment]
We removed the root cause of this problem i.e window title 😆
