### ISSUE TITLE
Decentralized technologies

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#546]
#9 is for backends. I'd like to separate decentralized and centralized technologies for now. Here's a big list of decentralized projects I've heard a little about. Some are storage related, some are not.

- [OrbitDB](https://github.com/orbitdb/orbit-db) - db
- [Gun](https://gun.eco/) - db
- [3box](https://3box.io/) - storage
- [fission.codes](https://fission.codes/) - storage
- [SourceCred](https://sourcecred.io/) - credit system
- [TheGraph](https://thegraph.com/) - data
- [Underlay](https://underlay.mit.edu/) - public knowledge graph
- [Solid Project](https://solidproject.org/)
- [Mirror.xyz](https://mirror.xyz/) - publishing
- [radicle.xyz](https://radicle.xyz/)
- [uprtcl.io](http://uprtcl.io/)
- [AnyType](https://anytype.io/) - notetaking app
- [Fairmint](https://fairmint.co/) - fundraising
- [Gitcoin](https://gitcoin.co/) - pay outs
- [Scuttlebutt](https://scuttlebutt.nz/) - social network

**Comment by oogetyboogety** [comment]
TheGraph can host defi exchange of datasets using a standard called erasure protocol

**Comment by oogetyboogety** [comment]
The examples use IPFS but could just use IPLD on top of IPFS

**Comment by seltzered** [comment]
holochain (folks behind hylo.com are eventually migrating to it I think)

**Comment by travis** [comment]
we were just starting to think about implementing something very similar to Athens on top of Solid at @itme - would love to chat!

**Comment by gturkoglu** [comment]
- [arweave.org](https://www.arweave.org) - storage
You pay once to store data *permanently*.
