### ISSUE TITLE
Open web links using default browser

### ISSUE THREAD

**Issue by dudelson** [athensresearch/athens#548]
*If you aren't sure about your bug, you can always join our [Discord](https://discord.gg/HNmxvpm) and ask in #agora or #engineering!*

**Problem**

Currently opening a web link (i.e. starting with `http` or `https`) from athens causes it to open in a new electron window, instead of my default browser.

**Expected Behavior**

Web links are opened in my default browser.

**Dependencies**

Arch linux.

- Athens: 1.0.0-beta.25
- browser: Firefox 84.0.2
- JVM: unsure, please let me know if this is relevant and I'll look into it
- node.js: unsure, please let me know if this is relevant and I'll look into it

**To Reproduce**

- Add a web link to a block (e.g. `[athens](https://github.com/athensresearch/athens/)`)
- Go to a new block, such that the link renders as something you can click
- Click the link

**Screenshots**

Please let me know if a screenshot is needed.

**Comment by tangjeff0** [comment]
Thanks @dudelson !
