### ISSUE TITLE
Parse bare links

### ISSUE THREAD

**Issue by dudelson** [athensresearch/athens#549]
*If you aren't sure about your bug, you can always join our [Discord](https://discord.gg/HNmxvpm) and ask in #agora or #engineering!*

**Problem**

Athens does not appear to parse "bare" links (I am not sure if this is the correct term) as such. In particular, I cannot click to open them.

**Expected Behavior**

Bare links will be recognized and rendered as something I can click to open.

**Dependencies**

[ Please specify your environment and software dependencies, with versions. ]

- Athens: 1.0.0-beta.25
- browser: Firefox 84.0.2
- JVM: unsure
- node.js: unsure

**To Reproduce**

- paste a bare link into a block (e.g. `https://github.com/athensresearch/athens/` -- note that it is just the link, without using the markdown link syntax)
- go to a new block such that the block containing the bare link is rendered
- note that the link is just displayed as text, rather than as an entity that can be clicked to open

**Screenshots**

[ Particularly helpful for UI bugs. ]

**Comment by tangjeff0** [comment]
Thanks for this @dudelson. I would love to have this, I'm just not great at parsers. Leaving these files here in case someone sees this and wants to take a stab at it:

- https://github.com/athensresearch/athens/blob/master/src/cljc/athens/parser.cljc
- https://github.com/athensresearch/athens/blob/master/test/athens/parser_test.clj
- https://github.com/athensresearch/athens/blob/master/src/cljs/athens/parse_renderer.cljs

**Comment by acron0** [comment]
+1 for this feature!
