### ISSUE TITLE
Italics shortcut recognised but not converting text into italics

### ISSUE THREAD

**Issue by ddauber** [athensresearch/athens#556]
*If you aren't sure about your bug, you can always join our [Discord](https://discord.gg/HNmxvpm) and ask in #agora or #engineering!*

I am not sure whether it is not implemented yet, but I was surprised about the behaviour below and wondered whether this is indeed a bug.

**Problem**

Turning text into italics by using ⌘+i results in `__italics__`. (two underscores on each side)

**Expected Behavior**

Selecte text + ⌘+i = _Selected text_

**Dependencies**

[ Please specify your environment and software dependencies, with versions. ]

- Athens: Beta.28 (MacOS)
- browser: 
- JVM:
- node.js: 

**To Reproduce**

Create a block with text, select it and press ⌘+i.

**Screenshots**

Let me know if you need one.

**Comment by tangjeff0** [comment]
Good find, I should disable that shortcut for now.

**Comment by tangjeff0** [comment]
Not supporting italics for now, so closed by #611
