### ISSUE TITLE
Should launching Athens go to 'Daily Notes' view or last viewed Block?

### ISSUE THREAD

**Issue by seltzered** [athensresearch/athens#558]
This is a user experience question that may have been discussed earlier. 

Here's the differences I see:
- Upon launching a general text editing tool, it starts with a blank page, user starts writing.
- Upon launching Roam, it starts with the 'daily notes' for the current day, user starts writing.
- Upon launching Athens, it goes to the block you were viewing. That's great if a user was intending to revisit that last page, but makes a user need to click into daily notes before starting to write.

Any opinions on this? I think I prefer just getting into daily notes upon launch since I'm usually quickly trying to write something on my brain upon launch.

**Comment by jsmorabito** [comment]
I personally like opening to daily notes, and i think the ideal solution is to default to daily notes then let the user choose what the default start page is somewhere in settings

**Comment by tangjeff0** [comment]
Sounds good! Should be an easy fix.
