### ISSUE TITLE
User Styling and UI Customization

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#563]
Related to Plugin System #63

For users to customize their notetaking experience in Athens there are several ways forward that we can think about. This issue was inspired by [this question](https://discord.com/channels/708122962422792194/708124073544122399/801367297075183638) on discord. Not high priority at the moment.

Use Case(s)
- special tag styling
- themes for readability

Current Theming in Athens
- native light/dark mode
- using stylefy which creates anonymous names for CSS classes/ids

Option 1 roam/css
- requires: more semantic CSS classes/ids
- pro: could be implemented sooner that native styling solutions?
- requires/con: requires maintaining and supporting a consistent API  

Option 2 native styling
- pro: accessible to non-coding individuals

Inspiration for native theming
- ?

References
- https://maggieappleton.com/paintingroam

**Comment by agentydragon** [comment]
One reason why I'd like this is because the current design has too much white space and uses my screen space inefficiently.

For example:
![image](https://user-images.githubusercontent.com/714892/110250538-0a468c80-7f7c-11eb-9379-7ae422df2f3c.png)

Here I can see only ~2x less text than I could, because of the white space.

**Comment by AoCz** [comment]
I would like to upvote this feature request. I echo the statements from @agentydragon in allowing some level of customizations for white space. I personally use a 32" monitor, and there can sometimes be an absurd level of unused white space. I believe some level of user control would be very beneficial. Ideally, there would be some presets, like in Gmail or Discord, where users can decide between "Comfort", "Moderate", or "Compact" levels—this could also be "Tablet", "Phone", "Touch", "Desktop", "Desktop HiDi", or whatever makes sense for the community. In addition, opening up a .css or .XML document where advanced users can zero in on exact values would be nice.


In addition, I believe that being able to adjust fonts is very important. Typography can make a big difference in the ease of reading and people with dyslexia and other reading disabilities. Monospace sans-serif fonts are the trendier and more common font choices for apps (and better for coding), but they are not ideal in all scenarios. Serif fonts will often work better for more people doing longer reading and writing sessions by working more easily with people's reading heuristics.

**Comment by tangjeff0** [comment]
Roam recently added multi-width support.

![image](https://user-images.githubusercontent.com/8952138/110901175-beb41b80-82b8-11eb-9ce2-37002ac851fe.png)

Agree that there should be an easy way to change fonts.

cc @shanberg

**Comment by bachmeil** [comment]
> Morever, I believe that being able to adjust fonts is very important. Typography can make a big difference in the ease of reading and people with dyslexia and other reading disabilities.

The font Athens comes with makes it unusable for anyone with reduced vision, including almost the entire population over the age of 40.
