### ISSUE TITLE
error when fastly deleting many single characters

### ISSUE THREAD

**Issue by TBu16** [athensresearch/athens#567]
**Problem**

When trying to delete many characters at a time, error message appeared.

**Expected Behavior**

Deleting the characers (maybe even speed up when staying on key for a while...

**Dependencies**

[ Please specify your environment and software dependencies, with versions. ]

- Athens: beta 1.00 0.30
- local electron app
- JVM:
- node.js:  14.15.4
- OS: Linux Pop_OS

**To Reproduce**

Deleting many single characters (staying on delete-key or hitting delete-key multiple times in a fast order...)

**Screenshots**
 
![image](https://user-images.githubusercontent.com/69479623/105742166-71176580-5f3b-11eb-8e1e-60ef84715427.png)

**Comment by jsmorabito** [comment]
![q5VLmAfpbm](https://user-images.githubusercontent.com/46250921/105797736-8baf0600-5f5e-11eb-8804-f9363d38d77f.gif)

maybe similar to this?

**Comment by TBu16** [comment]
> ![q5VLmAfpbm](https://user-images.githubusercontent.com/46250921/105797736-8baf0600-5f5e-11eb-8804-f9363d38d77f.gif)
> 
> maybe similar to this?

yes...
