### ISSUE TITLE
fix(block-page): editing header doesn't lead to updates

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#577]
https://www.loom.com/share/b8eca8413ce244deaf9a2030d6f56c2f

**Comment by lambduhh** [comment]
Bug : Editing header doesn't create a transaction
Acceptance Criteria: When user edits a header, the appropriate transaction occurs to save the content.

**Comment by lambduhh** [comment]
https://github.com/athensresearch/athens/pull/627
