### ISSUE TITLE
Aliases for block

### ISSUE THREAD

**Issue by nhanvu327** [athensresearch/athens#582]
Can we implement a feature to allow aliases for a block? The aliases should be stuck to the original block so that we don't need to make the alias every time we refer to the same block. Does that make sense ?

**Comment by tangjeff0** [comment]
Yes, we need aliases for pages as well @nhanvu327

**Comment by nhanvu327** [comment]
> Yes, we need aliases for pages as well @nhanvu327

Is it already on the roadmap? If so, when?

**Comment by tangjeff0** [comment]
Currently evaluating @nhanvu327 !

**Comment by TBu16** [comment]
> Yes, we need aliases for pages as well @nhanvu327

created a seperate issue: https://github.com/athensresearch/athens/issues/733

**Comment by juniusfree** [comment]
I opened a discussion for this so everyone can vote. 👍👍 https://github.com/athensresearch/athens/discussions/1001

**Comment by BrandonKMLee** [comment]
Namespaces seemed to be a better solution for this https://github.com/athensresearch/athens/issues/647
