### ISSUE TITLE
Right Sidebar not "compacting" content when manually sliding

### ISSUE THREAD

**Issue by brewha51** [athensresearch/athens#588]
When sliding the right sidebar to the right, the content falls off the window when sliding far to the right

![image](https://user-images.githubusercontent.com/76970520/106466905-8c193680-6461-11eb-92bb-b6a8a77135e0.png)

![image](https://user-images.githubusercontent.com/76970520/106466949-9affe900-6461-11eb-8114-f3bf85254824.png)

**Comment by juniusfree** [comment]
This should be fixed now.

https://github.com/athensresearch/athens/issues/696
https://github.com/athensresearch/athens/pull/770
