### ISSUE TITLE
Persistent Pop-up when scrolling

### ISSUE THREAD

**Issue by brewha51** [athensresearch/athens#592]
If you select the (...) beside the page title and then scroll without selecting anything, the popup stays persistent as you scroll...

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/76970520/106511069-5a21c780-6495-11eb-8052-c18f622a3a7f.png)

**Athens Version**
![image](https://user-images.githubusercontent.com/76970520/106511096-61e16c00-6495-11eb-9fd1-e956f84a1c03.png)

**Comment by juniusfree** [comment]
@tangjeff0 https://github.com/juniusfree/athens/pull/3
