### ISSUE TITLE
Daily Journal Date getting cut off at the top

### ISSUE THREAD

**Issue by brewha51** [athensresearch/athens#597]
**Top portion above the " 1 " is getting cut off**

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/76970520/106612259-863d5700-652e-11eb-9dac-8bde7c64a559.png)

**Athens Version 1.0.0 - Beta 3.3**

**Comment by lambduhh** [comment]
Investigated found that this is indeed the way the IBM Plex Mono font renders the number 1.
![image](https://user-images.githubusercontent.com/47534185/106674402-2e7c0b80-6581-11eb-87f7-aa12798751f5.png)


https://fonts.google.com/specimen/IBM+Plex+Mono?preview.text_type=custom&preview.text=1&selection.family=IBM+Plex+Mono:wght@600

**Comment by tangjeff0** [comment]
Good to close then?

**Comment by brewha51** [comment]
Good by me
