### ISSUE TITLE
SHIFT - LEFT CLICK of tags not opening in right-hand side bar

### ISSUE THREAD

**Issue by ddauber** [athensresearch/athens#598]
**Problem**

When `shift-clicking` on a tag, e.g. `#youtube`, it does not open in the right-hand sidebar.
When `shift-clicking` on a page, e.g. `[[youtube]]`, it does open in the right-hand sidebar. 

I would have expected that tags and pages would open in the right-hand sidebar when SHIFT- LEFT CLICKING. Not sure it is a bug or it is by design.

**Athens Version**
1.0.0-BETA.33 (MacOS, M1)

**Comment by tangjeff0** [comment]
This should be an easy fix @ddauber Thanks
