### ISSUE TITLE
Editable blocks

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#60]
# Feature

Usually, blocks are rendered as divs and spans. In order to change their contents (i.e. `:block/string`), you must click on the block. This changes the block to an editable `<textarea>`. When you click out, the block turns back into divs and spans.

# Demo

![textarea](https://user-images.githubusercontent.com/8952138/82100391-83b47c00-96d7-11ea-9dd9-14ee4c24486b.gif)

**Comment by Bardia95** [comment]
Working on it!

**Comment by tangjeff0** [comment]
Are you able to assign yourself? Might be better to use that feature than commenting :)

**Comment by Bardia95** [comment]
#70 
Can you guys code review my pull request when you get a chance? Be as critical as you want, I want as much feedback as you are willing to give me.
@tangjeff0 @jeroenvandijk

**Comment by tangjeff0** [comment]
Awesome will take a look tomorrow @Bardia95

**Comment by roryokane** [comment]
There was more discussion about textarea/input vs. `contenteditable` on Discord. Find the dicussion by searching for messages in the #engineering channel on 2020-05-22 starting with a message by @jelmerderonde (Discord user #1069), or by following [this link][first-message] to that first message.

[first-message]: https://discord.com/channels/708122962422792194/708124156113321985/713326304979583023.
