### ISSUE TITLE
Hover over block with hyperlinked text expands block

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#613]
**Problem**
Hovering over a block with hyperlinked text where the link address is larger than the text in the block will expand the block div(?) 

**Screenshots/Demo**
https://www.loom.com/share/4caa10ac843b44c5a6bf2b6e3df902b1

**Athens Version**
1.0.0-BETA.33

**Comment by tangjeff0** [comment]
I've noticed this as well, but it seems to happen non-deterministically, so hard to reproduce.

**Comment by jsmorabito** [comment]
> I've noticed this as well, but it seems to happen non-deterministically, so hard to reproduce.

one way I'm able to reproduce consistently is by creating a multi line 'hyperlink' when the window is small so that its changing the block div size. If I'm not using the correct technical terms to describe the behavior of the changing block ui size according to screen size please correct me 

![image](https://user-images.githubusercontent.com/46250921/107562918-66e99e00-6bae-11eb-8080-c5986fddc28b.png)

**Comment by tangjeff0** [comment]
I think you are using the right terms, but I'm not able to reproduce this. Not a huge issue atm though!

**Comment by tangjeff0** [comment]
Actually was able to reproduce. There needs to be a block below the block with the hyperlink.
