### ISSUE TITLE
Editing page title renames all occurrences

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#62]
Two edge cases:

- Existing page: #61
- Daily Notes: #66 

# Demo

![rename-page-title](https://user-images.githubusercontent.com/8952138/82101204-e444b880-96d9-11ea-8809-70131a0e3f02.gif)

**Comment by jelmerderonde** [comment]
Wanted to try creating this, but I guess it is easier to wait till #70 is merged.

**Comment by jeroenvandijk** [comment]
One more edge case @tangjeff0: changing the title to something very short like "a". Causes many unlinked references (endless stream of warnings about content-editable in this case). Found after testing #86. We can set a minimum character length for unlinked references I think

**Comment by tangjeff0** [comment]
Good idea. Don’t think Roam even does that. @jeroenvandijk
