### ISSUE TITLE
Navigating with back and forward buttons doesn’t update window title

### ISSUE THREAD

**Issue by james-tindal** [athensresearch/athens#631]
**Problem**
Navigating with back and forward buttons doesn’t update window title

**Screenshots/Demo**
<img src="https://user-images.githubusercontent.com/10291002/107548007-08c8b500-6bc6-11eb-9547-b41aa53ad173.png" alt="" width="400px"></img>

**Athens Version**
1.0.0-beta.37

**Comment by tangjeff0** [comment]
Duplicate #531
