### ISSUE TITLE
Global Keybindings

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#64]
# Keybindings

- [X] `ctrl-z`       : undo
- [X] `ctrl-shift-z` : redo
- [X] `cmd-k`        : toggle athena
- [X] `ctrl-g`       : toggle devtools
- [X] `ctrl-l`       : toggle left sidebar
- [X] `ctrl-r`       : toggle right sidebar

### 06-28-2020

[Implementation at time of this update](https://github.com/athensresearch/athens/blob/95cd758d95ad468338915c77c55e5137b62a3d7e/src/cljs/athens/listeners.cljs#L119-L143). Mapping have not been thought about deeply. But it shouldn't be too difficult to change/customize.

This update is focused on _global_ keybindings. Most other keybindings require block-level context. Thinking about putting block-level keybindings in the #97 issue, because there are many edge cases based on selection, location of block, location of cursor, etc. Copy and paste require some block-specific context, but they are magical so just acknowledging that.

### 05-15-2020

Most of Roam's keybindings are not super necessary. The important ones that stand out to me are:

- `backspace` - deletes block if empty
- arrow keys
- `indent` and `shift-indent`
- `ctrl-o`: open link
- `ctrl-b`: bold
- `cmd-z`: undo
- `cmd-shift-z`: undo
- `cmd-v`: paste (this is its own, lots of magic here)

Do consider how this could fit into a plugin architecture: #63.

## Example keybindings

![Screen Shot 2020-05-15 at 7 32 54 PM](https://user-images.githubusercontent.com/8952138/82103920-e101fa80-96e2-11ea-90bd-44ec9762316f.png)
![Screen Shot 2020-05-15 at 7 33 31 PM](https://user-images.githubusercontent.com/8952138/82103942-f5de8e00-96e2-11ea-977b-62a3707a27be.png)

**Comment by jeroenvandijk** [comment]
@tangjeff0 Many of the keybindings depend on the context. E.g. when editing a block you have ENTER and ESC, to save and cancel your change. Might be good to specify the context in the list above. I can think of the following:
```
indent and shift-indent [the current list item]
ctrl-o: open link [under cursor in sidebar]
ctrl-b: [make selected text] bold
```

**Comment by nixsee** [comment]
If I can make a suggestion, I use OneNote currently and while tab/shift tab will move a block in/out if at the start of the line, you can use alt+shift+arrow keys to move in/out/up/down with the cursor anywhere in the block. Tab within the block creates table columns, and once in a table, enter will create new lines. It would be great to get a similar block movement functionality (the tables are another issue)

**Comment by tangjeff0** [comment]
@nixsee those are great suggestions. Make sure to join our chat!
