### ISSUE TITLE
feat: h1, h2, h3 headers

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#646]
TODO: demo

- https://roamresearch.com/#/app/athensresearch/page/lx_YGD5JN
- the attribute in datascript for Roam is `:block/heading` and the value can be one of `#{1 2 3}`
- [x] remove empty lines like Roam. otherwise creates child blocks under empty lines
- [x] copying `#` `##` `###` automagically turns a block into a header
- [ ] ~ typing `#` etc. then `space` changes the type of block. Backspace at start of line removes block type. Notion pioneered this.

**Comment by dangirsh** [comment]
Without this, pasting markdown from others sources is impractical.

**Comment by kchen0x** [comment]
So how can I use the # to mark a header in Athens now? It has no effect by neither pasting a text with `# ` nor typing it key by key.

**Comment by tangjeff0** [comment]
@kchen0x I think for now you have to paste in `#` with multiple lines. Sorry for the lack of UX for now!

**Comment by kchen0x** [comment]
It works. But it seems I have no way to change the header hierarchy or re-render later...

Can I just keep the plain text `# title h1` `## tile h2` in the block, and the further development will support the full markdown rendering in the future, I suppose?

**Comment by tangjeff0** [comment]
@kchen0x correct, cannot change the header yet.

Some people don't want `#` to be in the block actually.

**Comment by kchen0x** [comment]
Yes, it's quite straightforward for me to type `#` to mark a header since Athens already supported markdown style `**bold**` to emphasize words. 

I also accept the way Notion implement by typing a leading `/` to invoke multiple command including text formatting such as header and emphasis.

**Comment by kchen0x** [comment]
Please refer to Typora's approach to WYSIWYG. I think most of Athens' formatting syntax and implementation scheme is consistent with Typora, and heaher should be handled the same way.

**Comment by tangjeff0** [comment]
Going to start testing out Typora but the new parser handles this! Will be merged this week @kchen0x #957
