### ISSUE TITLE
enhance(hyperlink parsing): edge cases not being caught 

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#650]
related to #549 and #636 

"the root cause is how our parser prioritizes "reserved characters" like # [[ (( and {{.  [https://github.com/athensresearch/athens/blob/9a2abefdf2692b1b142b01bf1d689af78716c8da/src/cljc/athens/parser.cljc#L74](https://github.com/athensresearch/athens/blob/9a2abefdf2692b1b142b01bf1d689af78716c8da/src/cljc/athens/parser.cljc#L74)  

I can think of 3 edge cases for the roam spec
1. `plain-text + # =>` text, 1 hashtag
2. `url + # =>` raw-link, no hashtags
3. `# + # =>` 2 hashtags" -Jeff ([link to discord conversation](https://discord.com/channels/708122962422792194/708124156113321985/810941465769148486))

![image](https://user-images.githubusercontent.com/46250921/107984083-1c449900-6f95-11eb-9297-ab815a04c0b7.png)

**Comment by jsmorabito** [comment]
![image](https://user-images.githubusercontent.com/46250921/108724449-5365fd80-74f3-11eb-85f1-0df588cc99f7.png)

"/" at the end of this url is not being caught by parser

**Comment by jsmorabito** [comment]
![image](https://user-images.githubusercontent.com/46250921/108731384-8495fc00-74fa-11eb-833d-b617aab86ce2.png)

similarly, the "." at the end of this url

**Comment by jsmorabito** [comment]
another edge case: # in link 
![image](https://user-images.githubusercontent.com/46250921/110376797-9f4f9100-8021-11eb-8341-c183605d6dcc.png)

**Comment by agentydragon** [comment]
Should be fixed.

**Comment by tangjeff0** [comment]
Thanks @agentydragon !
