### ISSUE TITLE
Zoom Capability is Stuck

### ISSUE THREAD

**Issue by Mina0824** [athensresearch/athens#658]
**Problem**
- I have been having frequent issues zoom-in and out within Athens. Today it's simply stuck. Restarting Athen's doesn't seem to be helping today. So, I am currently stuck with Athens zoomed-out to the point where I am unable to write within Athens. It seems that I can zoom out but I can't zoom back in.

**Screenshots/Demo**
![Athens Research Zoomed Out and Stuck_1](https://user-images.githubusercontent.com/79154426/108104900-e4535980-7059-11eb-97e6-1aaf03e9be83.jpg)

**Athens Version**
   1.0.0.

**Comment by tangjeff0** [comment]
@Mina0824 in order to zoom-in, you have to press `ctrl shift =`. See #532

**Comment by Mina0824** [comment]
Hi @tangjeff0 thank you for your reply. Doesn't budge.

**Comment by tangjeff0** [comment]
@Mina0824 that's strange. In order to reproduce this, is it possible for you to share a screenrecording of your app with keypresses shown?

**Comment by Mina0824** [comment]
- @tangjeff0 was in the process of recording my screen with key presses when Athens suddenly started working again. If it ever happens again I will make sure to get a recording for you. 👍🏻😁

**Comment by tangjeff0** [comment]
Thanks so much @Mina0824. Closing for now :)
