### ISSUE TITLE
"dead" block without Block-ID

### ISSUE THREAD

**Issue by TBu16** [athensresearch/athens#663]
I somehow managed to create a "dead" block in my athens. It seems as if the block has no block-ID and when I tried to do anything with the block (moving/deleting/editing/copy block reference/...) my athens completely broke.

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/69479623/108346854-20b0c200-71e0-11eb-9538-fad76f894bd1.png)
(this was the error code for moving the block...)

**Athens Version**
Windows x64 - 1.0.0-BETA.40

**Comment by TBu16** [comment]
And, by the way: Anyone an idea how I might get rid of this block in the future?

**Comment by ddauber** [comment]
Have you tried deleting the page? Can you still copy and paste the content from the page into a plain-text file? This would be my amateurish workaround to ensure you don't lose anything from this page. Of course, if the programme broke, then this might likely not be a workable solution.

**Comment by TBu16** [comment]
Yes, I already cut the content from the page, this worked. And when I say the program broke, I don't mean totally broke but just broke untill I restarted it (everytime I tried to edit the block). Deleting the page worked also...

**Comment by tangjeff0** [comment]
@TBu16 what if you shift select to highlight the block and then try to delete it? https://www.loom.com/share/a6a586ca03e84050a11870c163ca0a61

**Comment by TBu16** [comment]
This didn't work... (I now deleted it together with the page...)
