### ISSUE TITLE
Deleting the Welcome page makes Athens crash/freeze on startup

### ISSUE THREAD

**Issue by TillScout** [athensresearch/athens#667]
**Problem**
I deleted the "Welcome" page. Everything worked well from then on, but I noticed that the Welcome page was still in the Shortcuts. Clicking it made Athens crash. Now on startup Athens shows today's notes, but also freezes on startup and notes are not accessible anymore.

**Athens Version** beta 30

**Comment by juniusfree** [comment]
This seems fixed already. I deleted the Welcome page and it's removed from the Shortcuts panel.
![image](https://user-images.githubusercontent.com/8164667/110630711-ae307200-81e0-11eb-8699-e7f26012fa90.png)
