### ISSUE TITLE
Hello, can you please say in Athens will exist feature like Graph view?

### ISSUE THREAD

**Issue by Omnuchka** [athensresearch/athens#678]
Sorry, if miss note about it, but how I see, this is not exist now....
**Athenians are awesome))**

**Comment by juniusfree** [comment]
@Omnuchka Graph visualization is released in Athens 1.0.0-BETA.40

https://twitter.com/AthensResearch/status/1361742803345174530

There's a discussion thread at https://github.com/athensresearch/athens/discussions/605
