### ISSUE TITLE
Unable to delete the initial Calendar page

### ISSUE THREAD

**Issue by Kaszanas** [athensresearch/athens#684]
After opening the Athens I was met with already specified pages such as "Welcome" and "TODO" etc.
One of those seems to be a page with the current date being set up.

I am unable to delete aforementioned page.

![image](https://user-images.githubusercontent.com/34846245/109018516-7beb2480-76b8-11eb-8a45-282e897836a7.png)

Athens version:
1.0.0-beta.42

**Comment by mjio** [comment]
I noticed this as well, but now in version 1.0.0-beta.46 I'm able to delete daily pages, so I think this is fixed now.

**Comment by tangjeff0** [comment]
Good catch @mjio
