### ISSUE TITLE
Down-key press exception while working with links

### ISSUE THREAD

**Issue by Kaszanas** [athensresearch/athens#685]
**Problem**
While attempting to define a link with ```#[[Link to something]]``` and pressing down arrow key I have encountered an error.
This error resulted in the insert line vanishing and I am unable to enter any text into the text box while I can delete its contents.

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/34846245/109021231-fd43b680-76ba-11eb-8be6-ce1b7ff62db4.png)

**Athens Version**
1.0.0-beta.42

**Comment by sid597** [comment]
can't reproduce in 1.0.0-Beta.89, seems issue is fixed.
