### ISSUE TITLE
Mac keybindings don't match the "Welcome" document

### ISSUE THREAD

**Issue by DrHyde** [athensresearch/athens#716]
**Problem**

The welcome document says that C-b should make text bold, but that actually moves the cursor back one place. Apple-b emboldens.

Similarly it says that C-z should undo, but that actually does nothing. Apple-z undoes.

C-a to select all actually goes to the beginning of the line; A-a selects an entire line of text but not all blocks on the page.

Well you get the drift - it seems that Control needs replacing globally with Apple.

**Athens Version**

1.0.0-beta.46

**Comment by sid597** [comment]
@DrHyde Is this still an issue in the ~current version of Athens?

**Comment by DrHyde** [comment]
Yes, using Athens-1.0.0-beta.88.

**Comment by sid597** [comment]
@DrHyde Thank you for clarifying that, by `C-b` you mean `control + b`, what about `cmd + b` does that work?  I think this a doc-related issue as discussed in #824 , can you please check if that's the case?

**Comment by DrHyde** [comment]
Yes, Command-b (ie Apple-b) etc work as expected, I do indeed mean Ctrl-b when I write C-b.

**Comment by sid597** [comment]
@DrHyde Thank you for confirming, I have raised a PR that updates the welcome page documentation, this PR will soon be merged and changes will be reflected in the next release. So I am closing this.

**Comment by DrHyde** [comment]
Thanks!
