### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by mjio** [athensresearch/athens#722]
**Problem**
Athens is crashing on my system, macOS version 11.2.2. I'm using Athens 1.0.0-beta.46. The error happens when I try to update to version 1.0.0-beta.47.

```
message=Uncaught TypeError: Cannot read property '0' of null
source=file:///Applications/athens.app/Contents/Resources/app.asar/resources/public/js/compiled/renderer.js
lineno=15103
colno=505
error=TypeError: Cannot read property '0' of null
```

**Screenshots**
<img width="269" alt="Screen Shot 2021-03-02 at 11 04 57 am" src="https://user-images.githubusercontent.com/20990/109632591-7aea4500-7b47-11eb-8d41-6d3691251230.png">

**Athens Version**
1.0.0-beta.46

**Comment by tangjeff0** [comment]
That’s super strange. Not at my computer right now. Will look into this tomorrow. In the meantime, you can download the latest version directly by using the same Mac download link or rollback to a previous version. Steps are somewhere on discord #troubleshooting I believe.

Sent via Superhuman iOS ( https://sprh.mn/?vip=tangj1122@gmail.com )

**Comment by mjio** [comment]
I've updated manually to version 1.0.0-beta.47 and that works fine. If no one else sees this issue, I guess we can close it.

**Comment by tangjeff0** [comment]
I had this issue too from Linux. Dang!

**Comment by TillScout** [comment]
also occured on Windows, but the installation went through (showing a couple more error messages, though)

**Comment by yifanyin** [comment]
I also encounter this message after clicking the update prompt. After seeing the same message and press "OK", the app turned blank. I just leave it be and seems like Athens still updated itself under the hood and quit afterward. When I restart Athens it is the 1.0.0-beta.47 version. I would suggest a better visual for the update process and automatic restarting after updates.

**Comment by eerohele** [comment]
Got the same error on Big Sur.

**Comment by tangjeff0** [comment]
This bug was introduced after trying to fix another one here: https://github.com/athensresearch/athens/commit/68eb2d8e9364caf6392aa2edef91e19f4c12b903

My guess is that we need a guard for `-webContents` as well.

**Comment by tangjeff0** [comment]
Sentry gives us a more verbose error message:

![image](https://user-images.githubusercontent.com/8952138/110188545-f14da800-7dd0-11eb-8f00-b82b8923e307.png)

**Comment by tangjeff0** [comment]
Sentry gives a more verbose error message:

```
TypeError: Cannot read property '0' of null
    at EventEmitter.i.send.i.sendSync (electron/js2c/renderer_init.js:75:326)
```

This takes us to

https://github.com/athensresearch/athens/blob/66216b190d9c054266b051b6d9a62e27ebe63aa7/src/cljs/athens/core.cljs#L69-L76

**Comment by vtnate** [comment]
Same error happened to me on beta.49. Downloaded new version from github link and installed successfully, as suggested by others.

**Comment by sid597** [comment]
Closing this because this is an issue for past built, we expect a new issue to be created if this bug occurs in later builds so that they can be solved with P0 (highest) priority.
