### ISSUE TITLE
Page alias

### ISSUE THREAD

**Issue by TBu16** [athensresearch/athens#733]
Alias for a page: `[alias]([[page]])`

**Comment by juniusfree** [comment]
Also, alias for a block: `[alias](((block-id))))`

**Comment by juniusfree** [comment]
Or maybe a full support for Markdown?

**Comment by juniusfree** [comment]
https://discord.com/channels/708122962422792194/800442937602342922/819461273833046046

**Comment by sid597** [comment]
This is discussed here also https://github.com/athensresearch/athens/discussions/1001 , seeing the no of reactions I think it would be best to keep this open, but discussions would be a better place for this.
