### ISSUE TITLE
Page links within Linked References not clickable

### ISSUE THREAD

**Issue by yifanyin** [athensresearch/athens#735]
**Problem**
When clicking a page link within the Linked References below a page, the linked block change to edit mode. And I was not able to jump to the page, nor open the page in the sidebar.

https://user-images.githubusercontent.com/15666419/109982169-ebd55c80-7d01-11eb-92bb-614d3186a641.mov

**Athens Version**
1.0.0-BETA.48

**Comment by tangjeff0** [comment]
Take a look at this @arkRedM

**Comment by juniusfree** [comment]
Fixed. Checked in Beta88 windows 10.
