### ISSUE TITLE
revert(analytics): let non-paying users opt-out

### ISSUE THREAD

**Issue by solarkraft** [athensresearch/athens#740]
> Don’t explain your philosophy. Embody it.

— Epictetus

When I found out about Athens I was amazed. Finally an open source app for something so important! Finally an app respecting my privacy that I can use without bad feelings looming in the back of my head! But when I saw this: 

![2021-03-04T16:21:57Z](https://user-images.githubusercontent.com/1337470/109990913-23e09d80-7d0a-11eb-9c1d-b1e0add25e04.png)

my (really high) excitement got dampened a lot. Do you not think non-paying users deserve privacy?

I really thought about becoming a paying user, but now I am hesitant. Are *these* your values?
I never even intended to disable analytics either, I trust(ed you more before this) after all, but this is a pretty big red flag. 
 
Are you willing to overthink your data collection stance?

**Comment by Smittyvb** [comment]
Yeah, it sucks. I've started writing a fork that fixes this

**Comment by tangjeff0** [comment]
I disagree with the frame of your question, but I do believe that there are other ways to monetize that are more aligned with user needs.

Feel free to create PR for this @Smittyvb, otherwise I can revert the code when I have time.

**Comment by benjamindovinh** [comment]
The issue of privacy or not for anyone would not exist if not for someone willing to spend time developing

**Comment by shebang42** [comment]
As far as I can see, only some basic properties like OS, pathname, browser&library version, and a token ID are shared.  Which properties are you worried about?  (Maybe the team can limit this property?)

> Yeah, it sucks. I've started writing a fork that fixes this

Good luck keeping up with the (amazing) development velocity!  (There are far easier ways to limit telemetry data).

**Comment by solarkraft** [comment]
> Which properties are you worried about? 
I'm not particularly worried about any of these. I intend to leave analytics enabled, but I think people should be able to decide. "Thanks for helping making Athens better" when the user doesn't have a choice is sheer mockery. 

I don't mind paid-only features as much as removing people's choice about their data. It looks a bit like disabling security features on a car. 

Either way, thanks for considering this! I plan to become a paying user once this is shipped.

**Comment by benjamindovinh** [comment]
I'm willing to pay for privacy so that others may get it for free. What about you?
