### ISSUE TITLE
[product][feature request] Rethinking the graph view

### ISSUE THREAD

**Issue by gunny-slaps** [athensresearch/athens#746]
Please search our GitHub and Discord to see if your feature has already been requested!

# Problem
The graph view is a pretty promising thing, but I think it lacks some clear use-cases at the moment. This thread isn't meant to be catch-all in any sense, and I'm writing this stuff with no knowledge of the roadmap for this broader feature. Feel free to contradict / contribute!

1. The nodes don't point anywhere; it could be super useful to have them forward the user to the given page when clicked.
2. The nodes don't snap when moved to a new location. My mental model of the knowledge graph is that it should represent a dynamic mind map and help me see links and patterns between topics that I had been interested in. The call to action there for the user (me) is to say, "hey, maybe I should talk to people at a science startup since I know a lot of insights that map science pages to startup pages". It will probably help if I can persist the view and come back to it later to reference the developments over time and space.
3. The nodes include primitives like TODO and date pages. While they are probably also pages in the backend, they don't really contribute much value when I'm looking at the graph. It could be worth re-imagining them as tags on the nodes instead. Date pages in particular grows in an unbounded way and probably will clutter up the graph after weeks / months of use.
4. Aggregation is fairly central to data visualizations. This has probably been thought about, but I think it's worth mentioning again because the power of aggregation differs a cosmetic graph from a useful one. You don't have to generate insights for the user, but you should allow the user to find their own.

**Comment by tangjeff0** [comment]
Please add to #605
