### ISSUE TITLE
macOS app uses 20-30% CPU consistently while backgrounded

### ISSUE THREAD

**Issue by Bogdanp** [athensresearch/athens#759]
**Problem**

macOS (`11.2`) app (`1.0.0-beta.50`) uses 20-30% CPU consistently while backgrounded on the graph view. WindowServer CPU utilisation also seems to be up because of this (normally it would be 5% or less).

**Screenshots/Demo**

<img width="584" alt="Screenshot 2021-03-06 at 15 13 19" src="https://user-images.githubusercontent.com/43347/110207792-8bbff100-7e8e-11eb-853c-83fe4a81a325.png">

**Athens Version**

1.0.0-beta.50

**Comment by phrohdoh** [comment]
FWIW I am not observing this on macOS *11.2.2* with Athens *1.0.0-beta.53*.

**Comment by Bogdanp** [comment]
I've just upgraded to `1.0.0-beta.55`, the issue is still present for me.

<img width="498" alt="Screenshot 2021-03-11 at 09 10 03" src="https://user-images.githubusercontent.com/43347/110749256-9214eb00-8249-11eb-9547-7c8a8c9f5dac.png">

**Comment by tangjeff0** [comment]
@Bogdanp are you on an M1?

**Comment by Bogdanp** [comment]
Nope, I'm using a 2019 MBP:

<img width="698" alt="Screenshot 2021-03-11 at 19 11 04" src="https://user-images.githubusercontent.com/43347/110826312-9ff45b80-829d-11eb-9a98-46aa79758727.png">

Just to clarify, though, this only happens when the app is backgrounded while on the "graph" page. I don't know if there's another name for it, but it's the page where you can see the links between pages. That visualization seems to happen on the GPU and that probably needs to be suspended while backgrounded.

**Comment by phrohdoh** [comment]
> Just to clarify, though, this only happens when the app is backgrounded while on the "graph" page. I don't know if there's another name for it, but it's the page where you can see the links between pages. That visualization seems to happen on the GPU and that probably needs to be suspended while backgrounded.

In the above-described scenario on a 2018 MBP I can repro sustained higher-than-usual CPU utilization:
![image](https://user-images.githubusercontent.com/4861023/110827395-a4982000-825b-11eb-8ae0-f5db6ff16d11.png)

**Comment by tangjeff0** [comment]
Oh clarifying that when it's on the graph page makes a lot of sense.
