### ISSUE TITLE
Quickly succeeding enter/tab/backspace not registered

### ISSUE THREAD

**Issue by solarkraft** [athensresearch/athens#762]
**Problem**
When pressing enter, tab or backspace quickly one after another (in quick succession) the press is either not registered. On quickly succeeding enters and backspaces, the cursor can end up in the wrong node. It can also be observed jumping around, somewhat chasing newly created nodes. 

It's by far the most noticeable and annoying on Return+Tab, as pressing them in quick succession is a key part of the note taking workflow. 

**Screenshots/Demo**

https://user-images.githubusercontent.com/1337470/110221335-0824f500-7ecc-11eb-8f27-b70b99005b8a.mp4

https://user-images.githubusercontent.com/1337470/110221328-fd6a6000-7ecb-11eb-9fa7-61f24f909fca.mp4

https://user-images.githubusercontent.com/1337470/110221329-00655080-7ecc-11eb-8d1c-a79c6a87f038.mp4

https://user-images.githubusercontent.com/1337470/110221331-03f8d780-7ecc-11eb-9d43-b4abac53cff9.mp4

https://user-images.githubusercontent.com/1337470/110221334-06f3c800-7ecc-11eb-99d7-53f9e67b94e9.mp4

**Athens Version**
1.0.0-beta.50 on Arch Linux and XWayland (Wayfire)

**Comment by tangjeff0** [comment]
duplicate #602

**Comment by dangirsh** [comment]
+1 on Ubuntu 20.04

**Comment by tangjeff0** [comment]
Closed by #768
