### ISSUE TITLE
Setup Sentry error tracking

### ISSUE THREAD

**Issue by jeroenvandijk** [athensresearch/athens#78]
(I've applied for a Sentry opensource license 🤞)

Sentry's error tracking is useful to catch errors in production (artificacts) early. This can monitor regressions and help us determine the general health of the application.

https://sentry.io/organizations/athensresearch/

**Comment by tangjeff0** [comment]
Awesome, should we look at other services like Synk?

**Comment by jeroenvandijk** [comment]
Oh I didn't hear about Synk before (too much backend lately maybe). If you have good experience with that, sure.

**Comment by bsvin33t** [comment]
I think Synk and Sentry go hand in hand. Synk is for vulnerability detection and Sentry is for general application error tracking.   😄

**Comment by noorfathima11** [comment]
Can I get this assigned?

**Comment by tangjeff0** [comment]
Sure! Can you walk me through what needs to be done? @noorfathima11

**Comment by sid597** [comment]
Solved by #600
