### ISSUE TITLE
fix: react error from removing material-ui icons

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#792]
**Problem**
#700 - original issue
#790 - led to the error message below (repro'd on Linux and Windows)
#791 - reverts this and deploys `beta.55`

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/8952138/110592977-d1e7af80-812f-11eb-9c42-001b0d80e3cf.png)

**Athens Version**
beta.54

cc @oschmid

**Comment by tangjeff0** [comment]
My guess for why this is is that `shadow-cljs release` minifies code that ultimately can't run, whereas the shadow build-report builds but doesn't actually run any code.

**Comment by oschmid** [comment]
Looks like I should have used `:default` instead of `:as`. I'll create a PR.
