### ISSUE TITLE
Quickly pressing Up + Tab indents wrong block 

### ISSUE THREAD

**Issue by dangirsh** [athensresearch/athens#794]
Similar to #768 , but with Up instead of Enter. Seen on Ubuntu 20.04 on master.

**Comment by tangjeff0** [comment]
Is this fixed @dangirsh? PR was merged.

**Comment by dangirsh** [comment]
It happens on v1.0.0-beta.55. If you mean #768, this still happens with that fix.

**Comment by tangjeff0** [comment]
Please share a screenshot. Not able to reproduce.

**Comment by dangirsh** [comment]
Can't make it happen again consistently - closing
