### ISSUE TITLE
If a block is highlighted and ENTER is pressed, a colored border is seen for a moment

### ISSUE THREAD

**Issue by orphee-celui-qui-ne-sait-rien** [athensresearch/athens#798]
**Problem**
If a block is selected and ENTER is pressed, a colored border is seen for a moment, but, if only a word, or no word/block is highlighted, there's no border. 
**Screenshots/Demo**
https://user-images.githubusercontent.com/79347623/110735494-8399e580-81ef-11eb-8367-92473db086d7.mp4
**Athens Version**
1.0.0-BETA.56
Intel Mac

**Comment by tangjeff0** [comment]
Good catch! I noticed that. Looks kinda cool tho :|
