### ISSUE TITLE
Visual glitch in Windows Version of Athens Research—Gradient extending to scrollbar section

### ISSUE THREAD

**Issue by AoCz** [athensresearch/athens#805]
**Visual glitch in Windows Version of Athens Research**
There exists a glitch where the gradient extends beyond the boundary of the active space in Windows and into the scrollbar section. I have tested on Linux, and Linux is fine. I have not tested on Mac OS. 

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/2354428/110856752-08374300-8286-11eb-896e-f591a9fe25b5.png)

**1.0.0-BETA.46**

**Comment by AoCz** [comment]
I just updated to version 1.0.0-BETA.58 and I'm still seeing the same visual glitch

**Comment by juniusfree** [comment]
Adding this for reference https://discord.com/channels/708122962422792194/708124073544122399/735860796214607983
