### ISSUE TITLE
ClojureFam improvements

### ISSUE THREAD

**Issue by teodorlu** [athensresearch/athens#81]
How do we improve ClojureFam? Let's decentralize the process.

**Comment by teodorlu** [comment]
**How should teams evolve over time?**

Opinion from @teodorlu:

> Riffing on our teams & team names
>
> - Plato, Homer, etc stay as teams
> - Teams can continue taking on new learning pairs
> - Teams coordinate; one needs to commit as "primary mentor" for eligibility to take on new learners
> - Mentors with experience from 1+ team can spawn new teams. Plato may fork off Aristotle

**Comment by teodorlu** [comment]
`emmy`:

> something that came to mind for iterations of clojure fam is finding a way to gamify it. kind of like how groups do advent of code competitively, e.g. there's a leaderboard and each team would compete with each other
>
> with more practical questions geared toward beginners

**Comment by teodorlu** [comment]
> something that came to mind for iterations of clojure fam is finding a way to gamify it. kind of like how groups do advent of code competitively, e.g. there's a leaderboard and each team would compete with each other
>
> with more practical questions geared toward beginners

Two questions spring to mind:

- Can we let the learners curate 4clojure questions for each other?
- Can we keep a simple tracking table?

| Team | p1 | p2 |
|---|--|--|
| Socrates 1 | ✔️ | |
| Aristotle 1 | ✔️ | ✔️ |
| Homer 1 |  | ✔️ |

**Comment by teodorlu** [comment]
More generally, how do we enable learners to improve the learning process for the next cohort of learners? Should we treat this in the same way as we treat code contribution; with issues and pull requests?

**Comment by tangjeff0** [comment]
I think we can start by asking learners how they would improve the learning process for the next cohort. And then ask them to implement those improvements.

For learning materials (curricula, maps, tutorials, etc.), this could be on GH or Notion. For team-building, the teams can become product teams that collaborate on specific open-ended features or projects.

**Comment by teodorlu** [comment]
I like that asking them how they would do it gives them ownership and requires them to think through how that actually would work.

**Comment by jorda0mega** [comment]
to play devil's advocate - learners can identify the pain points but they might not yet know how to improve them (because of lack of knowledge). I think that's where the role of a mentor comes into play - tightening the feedback loop and offering quick advice to prevent the learners from getting overwhelmed with all the tooling, setup, etc.

**Comment by teodorlu** [comment]
@jorda0mega I think that's exactly the kind of learner-mentor dynamic we'll want to aim for. Learner brings an itch, mentor helps diagnose that, prevent scratching, and rather bring some salve.

**Comment by jorda0mega** [comment]
@teodorlu that's awesome!

In reference to
> Do you think "[learners] might not yet know how to improve them" still is a problem if we ask them after completing the mentor program?

Not in my mind. If anything, given how in touch they are with beginner's issues, they will be able to guide up and coming learners better.

**Comment by tangjeff0** [comment]
Please continue discussions at https://github.com/athensresearch/ClojureFam
