### ISSUE TITLE
fix: block-embed bullet pop-up menu is underneath the blocks

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#816]
**Problem**
block-embed bullet pop-up menu is underneath the blocks

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/8164667/111053342-faf4a100-849d-11eb-8dc2-136a697a759a.png)

**Athens Version**
1.0.0-BETA.59

**Comment by sid597** [comment]
Cannot reproduce in beta.89, seems like its fixed.
