### ISSUE TITLE
fix: Checking a TODO item in block embed results to error

### ISSUE THREAD

**Issue by juniusfree** [athensresearch/athens#819]
**Problem**
Checking a TODO item in block embed results to error

To replicate:
1. Create a block with a todo
2. Create a block-embed of the block you made in step no. 1
3. Check the todo in the block-embed

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/8164667/111094405-2fd42700-8576-11eb-9e50-9e6f77e0cb60.png)

**Athens Version**
1.0.0-BETA.60

**Comment by einarmagnus** [comment]
Same issue when trying to check a TODO in a Linked Reference view.

To replicate:

    Create a block with a todo under today
    Go to the TODO page
    Try to check the TODO from there

**Comment by phrohdoh** [comment]
`current-block-content` (result of `(:block/string (db/get-block [:block/uid uid]))`) is `nil` at https://github.com/athensresearch/athens/blob/92b766a8628b95b0c136677b74d2df9fdcfaa042/src/cljs/athens/components.cljs#L15-L23

**Comment by jsmorabito** [comment]
> Same issue when trying to check a TODO in a Linked Reference view.
> 
> To replicate:
> 
> 1. Create a block with a TODO under today
> 2. Go to the TODO page
> 3. Try to check the TODO from there

was able to replicate following these steps

**Comment by TillScout** [comment]
It gets a bit weirder. Assume you have two TODO items in two consecutive block, where the second one is a child of the first:
![grafik](https://user-images.githubusercontent.com/27848761/113252219-bfefcb80-92ed-11eb-9375-ab4c6956e6aa.png)
then on the TODO page (i.e. in the linked references) it looks like this:
![grafik](https://user-images.githubusercontent.com/27848761/113252304-da29a980-92ed-11eb-9fa2-08a73a6d0c14.png)
now when I click the first, second and fourth checkbox, I get the above mentioned error. However when clicking the third box (i.e. the main task, which is already visually distinct from the others, I get this:
![grafik](https://user-images.githubusercontent.com/27848761/113252432-0ba27500-92ee-11eb-8344-ebabecdacc8a.png)
So the nested task is checked, also on the main page, where the tasks were originally defined.

**Comment by kchen0x** [comment]
Same problem here:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/9739009/114638089-66c86480-9cfd-11eb-9199-5418d0e7f135.png">
<img width="260" alt="image" src="https://user-images.githubusercontent.com/9739009/114638109-70ea6300-9cfd-11eb-961a-a24a732ffd2c.png">

**Comment by juniusfree** [comment]
@kchen0x Can you check if your Athens version is at least 1.0.0-beta.67?

https://github.com/athensresearch/athens/blob/master/CHANGELOG.md#100-beta67-2021-04-11

**Comment by kchen0x** [comment]
Fixed after update Athens from beta.66 to beta.68.
