### ISSUE TITLE
When formatting text (bold, italics, etc.) if two or more formatting options are used, only one will work.

### ISSUE THREAD

**Issue by orphee-celui-qui-ne-sait-rien** [athensresearch/athens#820]
**Problem**
When formatting text (bold, italics, etc.) if two or more formatting options are used, only one will work.
**Screenshots/Demo**
https://user-images.githubusercontent.com/79347623/111095220-9cadd980-8502-11eb-8fad-e8e0ad9199bf.mov
**Athens Version**
Mac Intel
1.0.0-BETA.60

**Comment by yifanyin** [comment]
Can I also add: the formatting won't work when text within the formatting contains the same character.
For example:
`__SOLVER_TYPE__` will not turn into _SOLVER_TYPE_
and `**2*5**` will not turn into **2*5**

**Comment by juniusfree** [comment]
https://github.com/athensresearch/athens/issues/979
