### ISSUE TITLE
Export subtree via copy+paste

### ISSUE THREAD

**Issue by dangirsh** [athensresearch/athens#839]
A powerful Roam feature is the ability to view a subtree as a document, then copy+paste it into an email / Google Doc / etc...

This removes the bullets, unlinks page links, treats transclusions as copies, and retains external links + formatting. 

This doesn't always fully eliminate the need for minor cleanup of the pasted content, but often gets 90% of the way there.

**Comment by tangjeff0** [comment]
I think it would be pretty easy to right-click "copy as document" that copies an entire subtree that does what you request

> removes the bullets, unlinks page links, treats transclusions as copies, and retains external links + formatting

**Comment by tangjeff0** [comment]
Hi @dangirsh, can you show me how formatting is removed for you? For me, the dashes are removed, transclusions become plain-text, but [[brackets]] are maintained. Demo: https://www.loom.com/share/d40f4b052b7547f08358c6ccb8847e50


as bullets
```
- bullet 1
- bullet 2
- a link [[Test Copy Unformatted]]
- a transclusion "a link [[Test Copy Unformatted]]"
```

as document
```
bullet 1
bullet 2
a link [[Test Copy Unformatted]]
a transclusion "a link [[Test Copy Unformatted]]"
```

nested children
```
bullet 1
bullet 2
a link [[Test Copy Unformatted]]
a transclusion "a link [[Test Copy Unformatted]]"
    - 123
```

formatting
```
bullet 1
bullet 2
a link [[Test Copy Unformatted]]
a transclusion "a link [[Test Copy Unformatted]]"
    - 123
**bold** formatting
```
