### ISSUE TITLE
Core Product

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#841]
General
- [ ] Link Filters #65 
- [ ] Import from Roam #561 
- [ ] Spell check #870 
- [ ] Plugin system #63 
- [ ] Help popup #649 
- [ ] #931 

Components
- [ ] Queries #845 
- [ ] Kanban
- [ ] Table

Graph Visualization
- [ ] Node focus #788 
- [ ] Text fade threshold #787 
- [ ] New hotkeys #785

**Comment by sid597** [comment]
@jsmorabito I closed #870, I think it would be better if we link spell check to #564 because a solution by Stuart is also described there.

**Comment by tangjeff0** [comment]
Core Product is kinda vague vs just labeling with the relevant feature. Also, I'm not sure we should be using epics anymore. Good labeling basically fulfills these two needs.
