### ISSUE TITLE
allow resizing images

### ISSUE THREAD

**Issue by dbieber** [athensresearch/athens#849]
Feature request: allow resizing images pasted into Athens Research

This idea was mentioned in https://github.com/athensresearch/athens/issues/25 as requiring datoms and being suitable for implementing later after the initial image support was added (maybe that _later_ is now :)).

**Comment by dbieber** [comment]
Ah sorry, it looks like I was supposed to open this under Discussions, not issues. My bad.

**Comment by jsmorabito** [comment]
will reopen when work has started on this by core and/or community. discussion at #850
