### ISSUE TITLE
Suggest connections when select a text

### ISSUE THREAD

**Issue by nhanvu327** [athensresearch/athens#861]
As one of the core principles of the Zettelkasten method, the user should make connections between ideas as much as possible. So when a user selects a text, Athens should do a search to suggest the old blocks or pages for connections.

**Comment by nhanvu327** [comment]
do you agree ? @tangjeff0

**Comment by tangjeff0** [comment]
I think auto-suggestions are a good idea, regardless if text is selected or not, though that could be a good trigger.
