### ISSUE TITLE
Latex being duplicated next to links

### ISSUE THREAD

**Issue by richardrl** [athensresearch/athens#862]
**Problem**
this source code:
`mapping back out with a second [[change of basis]] $$B^{-1}$$
`

produces the below screenshot...

the $$B^{-1}$$ is duplicated incorrectly in the rendering 

If I remove the troublesome segment:

`[[change of basis]] $$B^{-1}$$
`

render latex once, paste back in the segment, and render again

it works

but it does not render correctly the first time
**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/5181990/111945330-ea50b600-8aaf-11eb-95b6-759ce8f764e7.png)

**Athens Version**
Not sure how to check -- latest master as of March 21 2021.

**Comment by sid597** [comment]
Cannot reproduce in beta.89, copy-pasted the above line multiple times each time produced the expected result. This issue could have been fixed between your version and the current one.
