### ISSUE TITLE
Open button freezes

### ISSUE THREAD

**Issue by richardrl** [athensresearch/athens#863]
**Problem**
![image](https://user-images.githubusercontent.com/5181990/111955063-63a3d500-8abf-11eb-9397-ee9836c38d58.png)

This button freezes upon being clicked. 

**Screenshots/Demo**

**Athens Version**
Latest version of Athens, Ubuntu 18.04, built according to Github instructions

**Comment by sid597** [comment]
Not an issue in ~latest versions of ubuntu.
