### ISSUE TITLE
Disable automatically creating daily note

### ISSUE THREAD

**Issue by richardrl** [athensresearch/athens#864]
There should be an option to disable the automatically generated daily note.

**Comment by nishu3210** [comment]
I agree because everyone wants to manage things differently.

**Comment by nishu3210** [comment]
I would like to work on this, but would need some help understanding the current code structure and how I can make change.

**Comment by tangjeff0** [comment]
@richardrl do you not use Daily Notes?

**Comment by lswank** [comment]
Aren’t daily notes cleaned up if they are empty after the day? I thought this was the case. Maybe I’m observing it incorrectly.

**Comment by tangjeff0** [comment]
Don't think they are cleaned up by default, thought I think that makes sense!

**Comment by richardrl** [comment]
> @richardrl @nishu3210 do you not use Daily Notes?

Not at all.

**Comment by snird** [comment]
The fact that they aren't cleaned up creates a massive mess in the graph, and there is no easy way to dispose of all empty notes.
