### ISSUE TITLE
#pagename ≠ #[[pagename]]

### ISSUE THREAD

**Issue by ddauber** [athensresearch/athens#866]
**Problem**

Imagine a page called `tmp`.

Pages which use `#tmp` to refer to the page `tmp` won't show as a linked reference on the page `tmp`.

However, when using `#[[tmp]]`, it will show up properly as a linked reference on the page `tmp`.

I would expect that `#tmp` = `#[[tmp]]`. At the moment `#tmp` would not work as expected.

**Athens Version**
Mac M1 1.0.0-Beta.60

**Comment by yifanyin** [comment]
I found out that tags written as `#foo` will sometimes turn into plain text `foo`. Also, tags written as `#[[foo]]` will turn into `[[foo]]`. I can not exactly reproduce the behavior. But it seems to connect to this issue @ddauber reported.

**Comment by ddauber** [comment]
> I found out that tags written as `#foo` will sometimes turn into plain text `foo`. Also, tags written as `#[[foo]]` will turn into `[[foo]]`. I can not exactly reproduce the behavior. But it seems to connect to this issue @ddauber reported.

It sounds like there is an issue of how `#` are treated. I think it was intended that `#foo = [[foo]]`. Not creating the `[[]]` would explain why it turn into plain text and not a page (maybe).

**Comment by tangjeff0** [comment]
Very strange.

**Comment by sid597** [comment]
@ddauber @yifanyin I cannot reproduce the issues either of you mentioned, `#foo = #[[foo]]` for me both the references are shown as a linked reference. 

beta.89

**Comment by ddauber** [comment]
Yes, I think it works now for me too. 😉

**Comment by yifanyin** [comment]
For absolutely safe, I've been using `#[[]]` at all times now and avoid using only `#`. I had an experience when I update a tag name from `SmartNote` to `smart note`, the `#SmartNote` tag without the brackets got updated to `#smart note` and I was left with a `#smart` tag.
