### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#870]
If you know the dependencies for this please comment! I know it's part of a context menu which I think is related to #869

*Just seeing #564 keeping that one open for context

**Comment by gregd** [comment]
Right now only English lang is supported. When I write a note any other language all text is marked as incorrect which is annoying and almost a show stopper. At least provide an option to disable spell checker please. Ideally I would like to configure spell checker to use other languages than English.

**Comment by mikejones3** [comment]
So English will work for picking what words are miss spelled, but you can not right click and fix spelling yet.

**Comment by sid597** [comment]
@jsmorabito I am closing this, Stuart has commented on #564 describing what can be done.
