### ISSUE TITLE
Settings Menu

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#881]
Current settings menu:
![image](https://user-images.githubusercontent.com/46250921/112663249-fa112700-8e2e-11eb-93e4-71d6e0698fa2.png)

Lots of room for improvement. Trend in similar space (obsidian, roam, more?) is to have modal with left navigation panel and content displayed on right side example:
![image](https://user-images.githubusercontent.com/46250921/112663464-3e042c00-8e2f-11eb-8d89-6e598c88ecc6.png)

**Comment by shanberg** [comment]
Here's a React sketch of a reorganized/restyled Settings page.

<img width="892" alt="Screen Shot 2021-04-05 at 1 55 28 PM" src="https://user-images.githubusercontent.com/98312/113606894-964ce200-9616-11eb-8eb6-772d00e88e1d.png">

Prototype: https://0pcrg.csb.app/
Code: https://codesandbox.io/s/athens-settings-page-0pcrg?file=/src/Settings.jsx

**Comment by tangjeff0** [comment]
@juniusfree would you like to try your hand at this?

**Comment by jsmorabito** [comment]
@shanberg can this design be easily modified to support the tab style menu seen in the obsidian screenshot? this is a super clean aesthetic upgrade but functionally it seems to be the same as our current version (besides the ux improvement), correct me if im wrong. I'm wondering if it might be more resourceful to start speccing out a more robust menu in anticipation of more complicated settings. what do you all think? also i dont want this comment to detract from how beautiful of an improvement this is you did an awesome job 🎉

**Comment by shanberg** [comment]
> @shanberg can this design be easily modified to support the tab style menu seen in the obsidian screenshot?

When we have more settings, sure. I'm just trying to solve for the settings we have now. I'm happy to redesign if needed.

**Comment by juniusfree** [comment]
@tangjeff0 I'll try. 👍

**Comment by avidrucker** [comment]
@tangjeff0 @juniusfree @shanberg  Is this issue is still open for taking? If yes, could you clarify which categories are ready to be added to the settings page?

**Comment by tangjeff0** [comment]
I actually think this is closed for now @avidrucker. Settings in a good spot already, but the next UI places that would get some love are likely #882 and #649!

**Comment by avidrucker** [comment]
@tangjeff0 Request to mark this as closed for now. Also a `paused` label would work.

**Comment by sid597** [comment]
closing, for now
