### ISSUE TITLE
feat: Support importing athens databases into RoamResearch

### ISSUE THREAD

**Issue by Fullstop000** [athensresearch/athens#885]

**Comment by lswank** [comment]
This seems more like a Roam Research feature request, no?

**Comment by tangjeff0** [comment]
Hahahahah yes but I love it @lswank @Fullstop000

**Comment by Fullstop000** [comment]
Oh sorry. What I mean could be a button to export RoamRearch JSON format files from Athens.

**Comment by tangjeff0** [comment]
See #561
