### ISSUE TITLE
Selecting an autocomplete option of linked reference results in text deleting itself. 

### ISSUE THREAD

**Issue by sawhney17** [athensresearch/athens#894]
**Problem**
When I select the autocomplete option of the linked reference and hit either enter or select the thing, it doesn't do anything and if I select out of it, it deletes the text. 

**Screenshots/Demo**
[Loom Link(Explained it better here)](https://www.loom.com/share/290c0bf2bce6448b8457727a6da7b240)

**Athens Version**
Athens Beta 61.0

**Comment by sid597** [comment]
@sawhney17 Works in beta.89, I think this issue is solved in ~current version.
