### ISSUE TITLE
Notarization doesn't work right (amd64/Apple M1) 

### ISSUE THREAD

**Issue by tobi** [athensresearch/athens#904]
**Problem** / **Screenshots/Demo**

Starting Athens after fresh download leads to this (somewhat bizarre) permission issue screen. This is different from normal Gatekeeper failures, so there may be multiple problems. 
![CleanShot_2021-03-22_at_13 00 47](https://user-images.githubusercontent.com/347/113423793-1831d680-939d-11eb-8afb-38404ababf03.png)

**Athens Version**

I've reproduced this with every posted version of Amd64 as well as Intel builds through rosetta. This is a M1 which happens to force gatekeeper to be on through JAMF so I can't test without it. 

![CleanShot 2021-04-02 at 10 28 23](https://user-images.githubusercontent.com/347/113424449-2c2a0800-939e-11eb-90ce-e6e1ada66533.png)

(for completeness: same thing happens with intel build) 

![CleanShot 2021-04-02 at 10 29 10](https://user-images.githubusercontent.com/347/113424535-524fa800-939e-11eb-831e-6007cfa90083.png)

total aside: the .zip files are .tar.gz files. That works in most instances, but... took me a second to figure out why the file didn't `unzip`

**Comment by tangjeff0** [comment]
Signed up for a trial of JAMF Pro and am waiting for their email. I haven't used JAMF before, and not sure others have encountered that issue, so maybe that's the root cause @tobi.

**Comment by tangjeff0** [comment]
@tobi I see that you were unzipping a `.zip` file. Have you tried using a `.dmg` yet?

- silicon: https://github.com/athensresearch/athens/releases/download/v1.0.0-beta.68/Athens-1.0.0-beta.68-arm64.dmg
- intel: https://github.com/athensresearch/athens/releases/download/v1.0.0-beta.68/Athens-1.0.0-beta.68.dmg

**Comment by tangjeff0** [comment]
Need to use `.dmg`, not `.zip` files. I remember removing `.zip` files before, but then I think it led to a bug in auto-update from actually happening. Do you remember what happened @sboesen ?

**Comment by sboesen** [comment]
From what I remember the `zip` files were used  by electron-updater during autoupdates, but I'm not sure how else they differ from the `.dmg` builds. I think removing `.zip` and also reordering `.dmg` and `.zip` appeared to break autoupdate on mac in different ways (not updating at all vs picking the wrong architecture for Intel macs).

**Comment by msutherl** [comment]
I'm currently having this issue with an Intel Mac

**Comment by tangjeff0** [comment]
Did you use `.dmg` @msutherl ?

**Comment by msutherl** [comment]
> Did you download and install `.dmg` @msutherl ?

Yes. Downloaded Intel Mac .dmg, installed, and when I double-click or right-click open the app, I get the same pop-up message (which I've never seen before). One thing I noticed is that the executable in the app bundle isn't executable. When I ran chmod +x  on it, I got a different pop-up message.

**Comment by tangjeff0** [comment]
@msutherl do you get the same result from running the Apple Silicon build `arm64.dmg`?

> One thing I noticed is that the executable in the app bundle isn't executable. When I ran chmod +x on it, I got a different pop-up message.

Interesting, I've never ran `chmod` on a .dmg file!

**Comment by sboesen** [comment]
FWIW works fine for me downloading/launch Athens 68 on intel mac, but without JAMF.

Also checked and the .app looks properly notarized:
```
$ spctl -a -t exec -vvv Athens.app/
Athens.app/: accepted
source=Notarized Developer ID
origin=Developer ID Application: Jeffery Tang (26HYSAT6MJ)
```

Can you double check you don't have parental controls enabled? It looks like it might be related to being unable to launch non-whitelisted programs, see
