### ISSUE TITLE
Ever growing Athens database

### ISSUE THREAD

**Issue by mjio** [athensresearch/athens#912]
**Problem**
I have been using Athens for about two months and noticed that my current Athens database is over 300 MB.
When I move the database to a different location, in Athens, the database shrinks to less than 1 MB, keeping all notes. I guess there is a cache that never gets cleaned up.

I sync my database across different devices and downloading a large database could soon become an issue, especially on a slow internet connection.

**Athens Version**
1.0.0-BETA.64

**Comment by tangjeff0** [comment]
There isn't a persistent cache that you would find on the filesystem, so I wouldn't expect moving the database changes the size. Can you reproduce or share steps to repro? @mjio

**Comment by sawhney17** [comment]
I think you're talking about your database folder. In the folder, there isn't just the database but images you save and backups as well. Just delete all the .bkp files which are safe to delete and you should be good

**Comment by mjio** [comment]
Thanks @sawhney17 Yes, I had a closer look at the files and they are the backup files, that is good to know. There is no need for me to keep syncing 300 MB of backup files, I'll delete them.
