### ISSUE TITLE
Athens hangs when trying to load graph or open TODO page

### ISSUE THREAD

**Issue by syk0saje** [athensresearch/athens#914]
**Problem**

Athens hangs when trying to load graph or open TODO page.

**Screenshots/Demo**

When trying to open the TODO page via a link or ctrl+k:
- the view freezes
- the cursor stays the same (hand if a link was clicked)
- nothing is responsive to mouse events (hovers or clicks) except for the title bar (minimize, restore, and close buttons)

I suspect that my `.transit` file is corrupted somehow, but not sure in what way and how to diagnose further.

**Athens Version**
1.0.0-BETA.65
Experienced on both Ubuntu 20.04 and Windows 10

**Comment by syk0saje** [comment]
Looks like for some reason, some of my TODO entries are broken:

TODO page:
```
["^@",[1435,"^6","TODO",536872768]]
```

Working link:
```
["^@",[1420,"^E","{{[[TODO]]}} Properly linked",536872768]]
```

Broken link:
```
["^@",[1417,"^E","{{[[TODO]]}} Unlinked 1",536872746]]
["^@",[1421,"^E","{{[[TODO]]}} Unlinked 2",536872750]]
```

**Comment by tangjeff0** [comment]
How do you think the entries are broken baed off the data you're sharing from your `.transit` file?

**Comment by syk0saje** [comment]
Sorry, need to clarify that values entered above were after I had done the following:

- Deleted the existing "TODO" entry from the `.transit` file (This alone fixed the problem of hanging when trying to load graph view)
- Recreated the TODO page by making a new `{{[[TODO]]}}` link (the working link)

**Comment by syk0saje** [comment]
The "Working link" shows up under "Linked References" in the new TODO page while the "Broken links" do not.

**Comment by tangjeff0** [comment]
I'm not sure why that would happen. Need to repro this

**Comment by syk0saje** [comment]
I can try to trim down my graph to the smallest possible case and attempt to recreate it from scratch.

fwiw, I'm also getting weird behavior for Daily Notes pages. Not sure if has something to do with me creating these pages before the date itself as a means of scheduling tasks. Notes from the clip below:

- The empty block seems to have been created when the day arrived
- When I press up and down to move and select across blocks, the empty block is skipped.
- When on the empty block, I can't indent it (tab)
- When I indent Task 2 it jumps under Task 1 instead of the empty block


https://user-images.githubusercontent.com/1628229/114121475-03b38800-9921-11eb-948b-855f15b4388a.mp4

Please advise if you think this belongs in another issue.

**Comment by syk0saje** [comment]
I have migrated the issue from the comment above to a new one: https://github.com/athensresearch/athens/issues/981

Unfortunately, I can't seem to replicate this one so I'll close it for now.
