### ISSUE TITLE
Support for importing and exporting to markdown 

### ISSUE THREAD

**Issue by panomitrius** [athensresearch/athens#920]
Support for importing and exporting to markdown, preferably compatible with Obsidian's style of linking.

**Comment by panomitrius** [comment]
> 
> 
> Support for importing and exporting to markdown, preferably compatible with Obsidian's style of linking.

**Comment by sawhney17** [comment]
Importing shouldn't be all that difficult after the code for the roam reserach import was just finished. #918 

> By looking at plain :block/string, it should be easy to reuse the code for markdown import.

**Comment by jsmorabito** [comment]
made #874 since my comment on #761 where i told you to make this! gonna close this issue so the convo can continue there. thank you for getting back on this regardless haha
