### ISSUE TITLE
Make block links "jump" referenced block to top of screen

### ISSUE THREAD

**Issue by richardrl** [athensresearch/athens#921]
![image](https://user-images.githubusercontent.com/5181990/113987817-d1b8fd80-981c-11eb-97a8-2ec7387ed389.png)

In this example, "here" links to the block at the bottom. But when you click on "here", nothing changes. Inter-page linking is a crucial feature, but right now the "here" link effectively does nothing. The referenced block at the bottom should "shift" to the top of the screen when clicking the link.

**Comment by tangjeff0** [comment]
Is this what you mean @richardrl https://www.loom.com/share/bba7c66643184a1ca9fcffb55544174d

**Comment by richardrl** [comment]
@tangjeff0 Yes, the way Notion does it is good. But your video doesn't show part of the effect. if you have a long page, if the 'linked' block is at the bottom, it will pop to the top after you click the link

**Comment by tangjeff0** [comment]
@richardrl Do you mean it should scroll up instead of instantly blinking there?

**Comment by richardrl** [comment]
> @richardrl Do you mean it should scroll up instead of instantly blinking there?

Actually, in the example you posted, there's no way to use scrolling to denote the target of the link. So you probably have to use the highlighting effect

**Comment by tangjeff0** [comment]
@richardrl what do you mean? we could scroll to the target (and then highlight to show)

**Comment by sid597** [comment]
@tangjeff0 I think what you said would be better from a UX point of view.

**Comment by sid597** [comment]
Closing this, this issue is discussed in more depth in #1063
