### ISSUE TITLE
When importing Roam EDN: add the option to download all images from Firebase and link to them locally

### ISSUE THREAD

**Issue by NishantTharani** [athensresearch/athens#928]
It's great to see the Roam import functionality implemented recently! One of the main draws of Athens for me is the privacy-friendly ability to have everything hosted locally. It would be great if the Roam importer could be extended to make this true for images as well.

Roam's approach to images is that whenever you paste an image into a note, the image is uploaded to Firebase, and a link to the image is generated and inserted into your note. The link is publicly accessible. This means that when a Roam EDN is imported into Athens currently, the Firebase link is preserved, so the image displayed in Athens is still pulled from that link.

I would like to suggest that the import process includes a step that downloads all the images from these Firebase links and saves them locally in the ./images subfolder, then links to them there.

There is a topic on the Roam forums where someone has posted some quick code that does this for the markdown export: https://forum.roamresearch.com/t/download-files-uploaded-to-firebase/3808 - the first script looks for matching URLs and downloads each file once, the second script replaces the markdown links with the local file locations. 

I assume this downloading would be OK with Roam, because the images were initially uploaded by the user doing the export/import, so they have the right to access them? It also seems like this would save them bandwidth in the long run, because the Athens user wouldn't be using their firebase each time they view the image.

**Comment by sid597** [comment]
@NishantTharani The forum link you provided does not work.
