### ISSUE TITLE
[all pages] Sort by Modified date

### ISSUE THREAD

**Issue by richardrl** [athensresearch/athens#929]
![image](https://user-images.githubusercontent.com/5181990/114097442-07e29580-988e-11eb-8197-cb095202e7f3.png)

We should be able to click "Modified" and "Created" and sort all the pages in ascending/descending order.

**Comment by tangjeff0** [comment]
Agreed. Same with Linked and Unlinked References too actually

**Comment by Em-AK** [comment]
fixed by #1105
