### ISSUE TITLE
⇧ + clic on linked page title won't open it in the side bar

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#958]
**Problem**
I expect that every time I ⇧ + clic on a link, that will open the link in the side bar.
This works well within the search bar, and also within the main page.
It also works for any link inside a linked reference, but not in the title !

**Screenshots/Demo**
![Capture d’écran 2021-04-13 à 13 42 38](https://user-images.githubusercontent.com/24638389/114511997-2f10dc80-9c6b-11eb-87c5-e95c56a46067.png)

**Athens Version**
1.0.0-BETA.68 - Intel OSX

**Comment by juniusfree** [comment]
@tangjeff0 I'll check. 👍
