### ISSUE TITLE
Links don't work when placed inside **bold markers**

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#962]
**Problem**
When I write `**some bold text including a [[Link]]**`, the link doesn't work

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/24638389/114580136-2e029e00-9cb1-11eb-9e9e-66809c68186a.png)

**Athens Version**
1.0.0-BETA.68 - Intel OSX

**Comment by mikejones3** [comment]
I have the same issue

**Comment by tangjeff0** [comment]
Roam breaks the bold, opting for link. This basically prioritizes links over bold, which makes sense.

![image](https://user-images.githubusercontent.com/8952138/114807077-a5403c80-9d5a-11eb-83b1-dbb193203f9a.png)

https://roamresearch.com/#/app/athensresearch/page/04-14-2021

**Comment by mikejones3** [comment]
Just cause that's how Roam works is that the best way to make decisions for Athens?

**Comment by shanberg** [comment]
If it’s limited due to how we're parsing syntax, then declaring (and documenting) interpretation priority sounds sensible. But if there's not a technical limitation, IMO we should just show a bold/underlined/italicized/monospaced/highlighted. link.

**Comment by neotyk** [comment]
<img width="415" alt="Screenshot 2021-04-16 at 08 06 44" src="https://user-images.githubusercontent.com/19492/114979249-d3bd3500-9e8a-11eb-946a-b7980ade0b24.png">

New parser allows for all sorts of inline "formatting" nesting.

**Comment by tangjeff0** [comment]
WOW @neotyk
