### ISSUE TITLE
Bloc search results and Athena results should be rendered

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#971]
**Problem**
Bloc search or Athena results don't render what they found. 
Would be cleaner and easier not to show these `**`, `__` and `^^` markups and render the results instead !

**Screenshots/Demo**
![image](https://user-images.githubusercontent.com/24638389/114851448-6e2e6180-9e14-11eb-915e-ba0a46bd132f.png)

**Athens Version**
1.0.0-BETA.68 - Intel OSX

**Comment by juniusfree** [comment]
Comments from Jeff about this https://github.com/athensresearch/athens/pull/660#issuecomment-780946803

**Comment by sid597** [comment]
Closing because as mentioned by junius this is how we want to handle Athena rendering.
