### ISSUE TITLE
Daily Pages scroll is slow

### ISSUE THREAD

**Issue by mikejones3** [athensresearch/athens#977]
**Problem**

When on the daily pages and scrolling to another day it is pretty slow to load on both my mac M1 and Windows laptop

**Athens Version**

1.0.0-beta.67

**Comment by agentydragon** [comment]
I think https://github.com/athensresearch/athens/pull/1061 should make this a bit better. No fancy optimizations, just making the past pages start loading a bit earlier than they currently do.

**Comment by juniusfree** [comment]
Fixed in https://github.com/athensresearch/athens/pull/1136
