### ISSUE TITLE
Keyboard shortcuts should toggle text markers

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#978]
**Problem**
Let's say I write some words I want to be bold.
I select them, type ⌘+B and the system will automatically place the `**...**` around. Handy !
But let's say that just after or later I change my mind. I select again the same words and type again ⌘+B. 
--> The system won't behave as I expected, by placing another `**...**` around, and I end up having `****...****` !

The same is true  with all current rendering options.

If I happen to have part of my selection that is not bold, then I'll expect Athens to handle my keystrokes just like any modern text editing software, which is :
* First keystroke, it will move the markers so that the whole selection becomes bold
* Second keystroke, it will remove all bold markers so that the whole selection becomes standard

**Athens Version**
1.0.0-BETA.67 - Intel OSX

**Comment by avidrucker** [comment]
- [ ] mark this with the `ux` label

**Comment by sid597** [comment]
This is the same issue as #806, closing this one because #806 has more no of votes
