### ISSUE TITLE
Text rendering markers can't be combined

### ISSUE THREAD

**Issue by Limezy** [athensresearch/athens#979]
**Problem**
That issue may be removed by the new parser, please feel free to delete my issue if that were the case.
I can't have a text which is both bold and highlighted, or bold and italic and so on... 
The current parser will only compute the most external markers, so if my wording is `**__...__**`, it will show it as bold **`__...__`**

**Athens Version**
1.0.0-BETA.67 - Intel OSX

**Comment by juniusfree** [comment]
WIP https://github.com/athensresearch/athens/issues/962#issuecomment-820933443

**Comment by tangjeff0** [comment]
Duplicate
