### ISSUE TITLE
Lost all content after update from `1.0.0-BETA.67` to `1.0.0-BETA.67`

### ISSUE THREAD

**Issue by jevonearth** [athensresearch/athens#988]
**Problem**

I lost a couple weeks of writing after doing an auto-update (previously I did updates by downloading manually). When Athens started up, I had a blank workspace.

**Screenshots/Demo**

n/a

**Athens Version**

Linux Desktop App.

Updating from `1.0.0-BETA.67` to `1.0.0-BETA.67`

Any tips on recovering my content is greatly appreciated.

**Comment by tangjeff0** [comment]
See last page of https://github.com/ddauber/athens-cheat-sheet/blob/main/athens_cheatsheet.pdf @jevonearth

**Comment by jevonearth** [comment]
Thanks @tangjeff0 but still no luck.

See the screen shot below. I restored my backup file (105k in size) to `index.transit`.
After starting Atehsn it makes a new backup, and both the current `index.transit` and the backup file are only 15k in size.

Athens does not have my content, only the default Welcome pages.

![image](https://user-images.githubusercontent.com/1114943/115445212-6979fc80-a1ca-11eb-89d8-3b3e33c765c2.png)

**Comment by shanberg** [comment]
@jevonearth 

Did you figure out what happened? If we can reproduce it then we can start dulling those edges.
